=== Основные понятия и термины

Рассмотрим эти базовые понятия и термины, прежде чем использовать {project_name} для обеспечения безопасности ваших веб-приложений и служб REST.

пользователей:: Пользователи - это сущности, которые могут войти в систему.  They can have attributes associated with themselves like email,
username, address, phone number, and birthday.  Они могут быть назначены членство в группах и иметь конкретные роли, назначенные им.
аутентификация:: Процесс определения и валидации пользователя.
авторизация:: Процесс предоставления доступа пользователю.
учетные данные:: Учетные данные - это части данных, которые {project_name} использует для проверки личности пользователя.  Some examples are passwords,
one-time-passwords, digital certificates, or even fingerprints.
роли:: Роли идентифицируют тип или категорию пользователя.  `Admin`, `user`, `manager` и `employee` - это типичные роли, которые могут существовать
в организации.  Приложения часто назначают доступ и права для определенных ролей, а не для отдельных пользователей, которые занимаются
с пользователями могут быть слишком тонкими и трудно управлять.
сопоставление ролей пользователя:: Сопоставление ролей пользователя определяет соответствие между ролью и пользователем.  Пользователь может быть связан с нулевыми или более ролями.  This
role mapping information can be encapsulated into tokens and assertions so that applications can decide access permissions on
various resources they manage.
составные роли:: Составная роль - это роль, которая может быть связана с другими ролями.  Например, составная роль `superuser` может быть ассоциирована с ролями
`sales-admin` и `order-entry-admin`.  Если пользователь сопоставлен с ролью «superuser», то он также наследует роли «sales-admin» и «order-entry-admin».
группы:: Группы управляют группами пользователей.  Атрибуты могут быть определены для группы.  Вы также можете сопоставить роли с группой.  Users that become members of a group
inherit the attributes and role mappings that group defines.
области:: Область управляет набором пользователей, учетными данными, ролями и группами.  Пользователь принадлежит и вписывается в реалм.  Realms изолированы друг от друга
и могут управлять только и аутентифицировать контролируемых ими пользователей.
клиенты:: Клиенты - это объекты, которые могут запрашивать {project_name} для аутентификации пользователя.  Most often, clients are applications and services that
want to use {project_name} to secure themselves and provide a single sign-on solution.  Клиенты также могут быть сущностями, которые просто хотят запросить идентификационную информацию
или токен доступа, чтобы они могли безопасно вызывать другие сервисы в сети, которые защищены {project_name}.
клиентские адаптеры:: Клиентские адаптеры - это плагины, которые вы устанавливаете в ваше приложение, чтобы иметь возможность общаться и быть защищенными {project_name}.  {project_name}
имеет несколько адаптеров для разных платформ, которые вы можете скачать.  Также есть сторонние адаптеры, которые вы можете получить в тех средах, которые мы не покрываем.
согласие:: Согласие заключается в том, что вы как администратор хотите, чтобы пользователь дал разрешение клиенту прежде чем этот клиент сможет участвовать в процессе аутентификации.
После того, как пользователь предоставил свои учетные данные, {project_name} откроет экран идентификации клиента, запрашивающего логин и идентификацию
от пользователя.  Пользователь может решить, удовлетворить или нет запрос.
рамки клиентов:: Когда клиент зарегистрирован, вы должны определить сопоставления между протоколами и ролями для этого клиента. It is often useful to store
a client scope, to make creating new clients easier by sharing some common settings. This is also useful for requesting some
claims or roles to be conditionally based on the value of `scope` parameter. {project_name} предоставляет для этого понятие рамок клиента.
роль клиента:: Клиенты могут определять специфичные для них роли.  Это в основном пространство имен ролей, предназначенное для клиента.
идентификационный токен:: Токен который предоставляет идентификационную информацию о пользователе.  Часть спецификации OpenID Connect.
токен доступа:: Токен который может быть предоставлен как часть HTTP-запроса, который предоставляет доступ к вызываемому службе.  Это часть
спецификации OpenID Connect и OAuth 2.0.
утверждение:: Информация о пользователе.  Это обычно относится к блоку XML, который включен в ответ аутентификации SAML, который
предоставил метаданные идентификации пользователя с аутентификацией.
сервисный аккаунт:: Каждый клиент имеет встроенную учетную запись обслуживания, которая позволяет получить токен доступа.
прямой грант:: Способ получения клиентом токена доступа от имени пользователя посредством вызова REST.
protocol mappers:: Для каждого клиента вы можете настроить какие требования и утверждения хранятся в токене OIDC или SAML.  You do this per client by creating and configuring
protocol mappers.
сессия:: При входе пользователя создается сеанс для управления сеансом входа.  Сессия содержит информацию, такую как когда пользователь вошел в систему и что
приложения участвовали в одном вход во время этой сессии.  Как администраторы, так и пользователи могут просматривать информацию о сеансе.
провайдер федерации пользователей:: {project_name} может хранить и управлять пользователями.  Часто у компаний уже есть службы LDAP или Active Directory, которые хранят информацию о пользователе и учетных данных
.  Вы можете указать {project_name} для проверки учетных данных из этих внешних магазинов и получения личных данных.
провайдер идентификации:: Идентификационный провайдер (IDP) - это сервис, который может аутентифицировать пользователя.  {project_name} - это IDP.
федерация идентификационного провайдера:: {project_name} может быть настроен для делегирования аутентификации одному или нескольким IDP.  Social login via
Facebook or Google is an example of identity provider federation.  Вы также можете вызывать {project_name} для делегирования
аутентификации на любой другой OpenID Connect или SAML 2.0 IDP.
карты идентификаторов провайдеров:: При выполнении федерации IDP вы можете сопоставлять входящие токены и утверждения пользовательским и сессионным атрибутам.  Это поможет вам распространить информацию о личности из внешнего IDP
вашему клиенту, запрашивающему аутентификацию.
обязательные действия:: Необходимые действия - это действия, которые пользователь должен выполнить во время процесса аутентификации.  A user will not be able to complete the authentication process until these actions
are complete.  Например, администратор может запланировать пользователям сброс паролей каждый месяц.  Для всех пользователей
будет установлено обязательное действие «обновить пароль».
потоки аутентификации:: Потоки аутентификации - это рабочие потоки, которые пользователь должен выполнять при взаимодействии с определенными аспектами системы.  Поток логина может определить
какие типы учетных данных требуются.  Процесс регистрации определяет, какую информацию профиля нужно ввести пользователю, и следует ли что-то вроде reCAPTCHA
использовать для фильтрации ботов.  Сброс учетных данных определяет, какие действия пользователь должен выполнять, прежде чем он сможет сбросить свой пароль.
события:: События - это потоки аудита, которые администраторы могут просматривать и хуки вкл.
темы:: Каждому экрану, предоставленному {project_name} , поддерживается темой.  Темы определяют HTML шаблоны и таблицы стилей, которые вы можете переопределить по мере необходимости.