=== Возможности

{project_name} предоставляет следующие функции:

* Single Sign-On и Single Sign-Out для приложений браузера.
* Поддержка OpenID Connect.
* Поддержка OAuth 2.0.
* Поддержка SAML.
* Идентификатор брокера - аутентификация с внешним OpenID Connect или SAML идентификаторы.
* Социальный вход - включите вход с Google, GitHub, Facebook, Twitter и других социальных сетей.
* Федерация пользователей - синхронизация пользователей с серверов LDAP и Active Directory.
* Мост Kerberos - Автоматически аутентифицировать пользователей, которые вошли в систему на сервере Kerberos.
* Консоль администратора для централизованного управления пользователями, ролями, ролями, клиентами и конфигурацией.
* Консоль учетной записи, которая позволяет централизованно управлять своей учетной записью.
* Поддержка темы - Настройте все пользовательские страницы для интеграции с вашими приложениями и брендингом.
* Гибкая аутентификация - аутентификация пользователя с различными механизмами, включая пароль, сертификаты X.509. Поддержка аутентификации по шагам
* Двухфакторная аутентификация - поддержка паролей, кодов восстановления и TOTP/HOTP через Google Authenticator или FreeOTP.
* Логин процессы - необязательная регистрация пользователя, восстановление пароля, верификация электронной почты, требуют обновления пароля и т.д.
* Управление сессиями - сами администраторы и пользователи могут просматривать и управлять сессиями.
* Маркеры - карты атрибутов, ролей и т.д. как вы хотите в токены и операторы.
* Отзыв политик недоступен для каждого мира, приложения и пользователя.
* CORS поддержка - клиентские адаптеры имеют встроенную поддержку CORS.
+
ifeval::[{project_community}==true]
* Интерфейсы сервис-провайдера (SPI) - ряд SPI, позволяющих настраивать различные аспекты сервера. Authentication flows, user federation providers,
protocol mappers and many more.
+
endif::[]
* Поддерживает любую платформу/язык, у которой есть библиотека OpenID Connect Relying Party или библиотека провайдера услуг SAML 2.0.