=== Основные операции {project_name}

{project_name} является отдельным сервером, которым вы управляете в своей сети.  Applications are configured to point to and
be secured by this server.  {project_name} uses open protocol standards like link:https://openid.net/developers/how-connect-works/[OpenID Connect]
or link:https://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0.html[SAML 2.0] to secure
your applications.  Браузер приложения перенаправляет браузер пользователя из приложения на сервер аутентификации {project_name}
, где он вводит свои учетные данные.  This redirection is important because users are completely isolated from applications and
applications never see a user's credentials.  Applications instead are given an identity token or assertion that is cryptographically
signed.  Эти токены могут иметь данные о личности, такие как имя пользователя, адрес, адрес электронной почты и другие данные профиля.  They can also
hold permission data so that applications can make authorization decisions.  Эти токены также могут использоваться для защиты
от вызовов на службы REST.