== Обновить рабочий процесс электронной почты (UpdateEmail)

С помощью этого рабочего процесса пользователям нужно будет использовать действие `UPDATE_EMAIL` для изменения собственного адреса электронной почты.

Это действие обеспечивает более безопасный и последовательный поток для обновления электронной почты пользователей, требуя повторной проверки электронной почты перед обновлением своей учетной записи.

Приложения могут отправлять своих пользователей на форму обновления электронной почты, используя UPDATE_EMAIL как <<con-aia_{context},AIA (Application Initiated Action)>>.

Чтобы включить Update Email для реалма, перейдите в меню `Authentication` в административной консоли и нажмите на вкладку `Required actions`.
Переключить переключатель для `UPDATE_EMAIL` на `enabled`.

=== Принуждение пользователей повторно авторизоваться перед обновлением электронной почты

Когда включено действие `UPDATE_EMAIL`, пользователям может потребоваться повторная аутентификация, прежде чем они смогут обновить свою электронную почту, если их последняя аутентификация старше установленной продолжительности.
Это мера безопасности для предотвращения захвата учетной записи в том случае, если учетные данные пользователя неизвестны нападающим, но сеанс взломается.

По умолчанию, пользователю будет предложено повторно авторизоваться, если последняя аутентификация старше 5 минут (300 секунд). You
can change this value by setting the `Maximum Age of Authentication` setting in the `UPDATE_EMAIL` required action configuration.
Установив это значение в `0`, пользователю всегда будет предложено повторно авторизоваться перед обновлением электронной почты.

=== Проверка писем

Если в реалме отключена проверка электронной почты, это действие позволит обновить электронную почту без проверки.

Если в реалме включена проверка электронной почты, действие будет отправлено по электронной почте со ссылкой на новый адрес электронной почты, не изменяя адрес электронной почты.
Только после перехода по ссылке и подтверждения электронной почты, письмо будет обновлено.

При определенных обстоятельствах вы не хотите включать проверку электронной почты на уровне реалмов, но только тогда, когда пользователи обновляют свои письма.
Для этого вы можете установить параметр `Force Email Verification` на `UPDATE_EMAIL` для проверки их электронной почты
хотя проверка электронной почты в конечном итоге отключена на уровне реалмов. По умолчанию проверка электронной почты не включена.

In case the user is updating the email during the authentication flow (e.g.: when running the `UPDATE_PROFILE` required action),
the user will be forced to verify the email if any of the `Verify Email` or the `Force Email Verification` settings are enabled.
В случае, если `Verify Email` включен на уровне реалма, требуемое действие `VERIFY_EMAIL` будет автоматически добавлено в учетную запись пользователя.
Otherwise, if only the `Force Email Verification` is enabled the `UPDATE_EMAIL` required
action will be added instead.

If a user has `Email Verified` set, and both `Verify Email` and `Force Email Verification` are disabled, `Email Verified`
resets after the user updates email.

=== Обновление электронной почты пользователя

Когда включено действие `UPDATE_EMAIL`, пользователь может обновить свои электронные письма:

* Авторегистрация в реалме, если эта возможность разрешена в Realm
* Доступ к консоли аккаунта и щелчок по ссылке «Обновить электронную почту» в разделе «Личная информация»
* Обновление профиля во время процесса аутентификации (например, при запуске `UPDATE_PROFILE` требуется действие), если email еще не установлен.
Если существующий пользователь имеет набор электронной почты при обновлении профиля во время процесса аутентификации, атрибут электронной почты будет недоступен.
* Администраторы при обновлении учетной записи пользователя через консоль администрирования

=== Ожидание подтверждения электронной почты

Когда пользователь инициирует обновление электронной почты, которое требует подтверждения, новый адрес электронной почты хранится в ожидании до тех пор, пока пользователь не нажмёт на ссылку верификации. Если пользователь попытается войти в систему еще раз перед нажатием на ссылку подтверждения, они увидят сообщение с сообщением о том, что письмо с подтверждением было отправлено на новый адрес, с параметрами для повторной отправки электронной почты или введите другой адрес электронной почты.

Администраторы могут управлять этими проверками в ожидании через консоль администратора. На странице сведений о пользователе, когда у пользователя есть подтверждение по электронной почте, отображается предупреждение с указанием состояния проверки. Уведомление покажет, какой адрес электронной почты ожидает подтверждения, и предоставляет ссылку для отмены процесса проверки.

Нажатие на эту ссылку открывает диалоговое окно подтверждения, которое позволяет администраторам удалить проверку, находящуюся в ожидании, или отменить действие.

После подтверждения, это действие будет:

* Удалить атрибут проверки электронной почты
* Подтвердить существующую ссылку для проверки
* Удалите действие `UPDATE_EMAIL` с пользователя

=== Обновить Email и профиль пользователя

If the email attribute is set as required in the user profile configuration, the requirement is kept in the Update Email workflow,
meaning a user won't be able to clear his/her email in update email page. Напротив, если установлен атрибут электронной почты как необязательный
в конфигурации профиля пользователя.

Если атрибут электронной почты установлен в конфигурации профиля пользователя только для чтения, то применяется следующее поведение:

* Ссылка «Обновить email» не будет отображаться в консоли аккаунта
* Требуется действие `UPDATE_EMAIL` будет автоматически пропущено и удалено из учетной записи пользователя
* На странице профиля обновления, если адрес электронной почты пользователя изначально пуст, то поле электронной почты будет скрыто

=== Настройка сообщений

Все сообщения, отображаемые в этом рабочем процессе, включая сообщения консоли администратора, письма с подтверждением, и обновить страничные сообщения электронной почты, можно настроить с помощью стандартной системы настройки сообщений {project_name}.