// Module included in the following assemblies:

//

// server_admin/topics/users.adoc

[id="con-required-actions_{context}"]
= Определение действий при входе в систему

Вы можете установить действия, которые пользователь должен выполнить при первом входе в систему. Эти действия требуются после того, как пользователь предоставит учетные данные. После первого входа эти действия больше не требуются. Вы добавляете необходимые действия на вкладке *Детали* этого пользователя.

Некоторые необходимые действия автоматически запускаются для пользователя при входе в систему, даже если они явно не добавлены этому пользователю администратором. For example `Update password` action can be
triggered if <<_password-policies, Password policies>> are configured in a way that the user password needs to be changed every X days. Или `verify profile`
может потребовать обновления пользователя <<user-profile, User profile>> до тех пор, пока некоторые атрибуты пользователя не соответствуют требованиям в соответствии с конфигурацией профиля пользователя.

Ниже приведены примеры требуемых типов действий:

Обновить пароль:: Пользователь должен изменить свой пароль.
Настройка OTP:: Пользователь должен настроить одноразовый генератор паролей на своем мобильном устройстве, используя приложение Free OTP или Google Authenticator.
Подтвердить email:: Пользователь должен подтвердить свою учётную запись электронной почты. Письмо будет отправлено пользователю с ссылкой подтверждения, что он должен кликнуть. Как только этот процесс будет успешно завершен, пользователю будет разрешено войти в систему.
Обновить профиль:: Пользователь должен обновить данные профиля, такие как имя, адрес, адрес электронной почты и номер телефона.

NOTE: Некоторые действия не имеют смысла добавлять в учетную запись пользователя. Например, `Update User Locale` является вспомогательным действием для обработки некоторых параметров, связанных с локализацией. Другим примером
является действие `Delete Credential`, которое должно быть вызвано как <<con-aia-parameterized_{context}, Parameterized AIA>>.  В связи с этим, если администратор хочет удалить учетные данные некоторых
пользователя, то администратор может сделать это непосредственно в консоли администратора. Действие `Delete Credential` посвящено использованию <_account-service,{project_name} Account Console>>.