// Module included in the following assemblies:

//

// server_admin/topics/users.adoc

[id="con-aia_{context}"]
= Начальные действия приложения

Начатые действия приложения (AIA) позволяют клиентским приложениям запрашивать пользователя для выполнения действия на стороне {project_name}. Обычно когда приложение OIDC клиента
хочет, чтобы пользователь вошел в систему, он перенаправляет этого пользователя на URL входа, как описано в <<con-oidc_{context}, OIDC section>>. После входа пользователь перенаправляется обратно в клиентское приложение.
Пользователь выполняет действия, которые были предприняты администратором, как описано в <<proc-setting-required-actions_{context}, previous section>>
и сразу перенаправляется обратно в приложение. Тем не менее, AIA позволяет клиентскому приложению запросить некоторые необходимые действия у пользователя во время входа. This can be
done even if the user is already authenticated on the client and has an active SSO session. Вызывается путем добавления параметра `kc_action` в URL-адрес входа OIDC со значением, содержащим запрошенное действие.
Например, параметр `kc_action=UPDATE_PASSWORD`.

Пользователь может отменить начатое действие заявки. В этом случае пользователь перенаправляется обратно в клиентское приложение.
URI перенаправления будет содержать параметры запроса `kc_action_status=cancelled` и `kc_action` с именем отмененного действия.

NOTE: Параметры `kc_action` и `kc_action_status` являются проприетарным механизмом {project_name} , не поддерживаемым спецификацией OIDC.

NOTE: Запущенные действия поддерживаются только для клиентов OIDC.

Таким образом, если используется AIA, то такой же приток данных аналогичен следующим образом:

* Приложение клиента перенаправляет пользователя на OIDC логин с дополнительным параметром, таким как `kc_action=UPDATE_PASSWORD`
* Существует поток `browser` всегда запускается, как описано в <_authentication-flows, раздел аутентификации потоков>>. Если пользователь не был аутентифицирован, он должен авторизоваться как при обычном входе в систему.
В случае, если пользователь уже был аутентифицирован, этот пользователь может быть автоматически повторно аутентифицирован по SSO cookie без необходимости активной повторной аутентификации и предоставления учетных данных снова. В этом случае пользователь будет
непосредственно перенаправлен на экран с конкретным действием (в данном случае обновите пароль). Однако, в некоторых случаях требуется активная повторная аутентификация, даже если у пользователя есть SSO
cookie (см. <<con-aia-reauth_{context}, below>> для деталей).
* Экран с конкретным действием (в данном случае «обновить пароль») отображается пользователю, чтобы пользователь мог выполнить определенное действие
* Затем пользователь перенаправляется обратно в клиентское приложение

Обратите внимание, что AIA используется {project_name} <<_account-service, Account Console>> для запроса пароля или для сброса других учетных данных, таких как OTP или WebAuthn.

WARNING: Даже если используется параметр `kc_action`, недостаточно предполагать, что пользователь всегда выполняет действие.  Например, пользователь мог бы вручную удалить
параметр `kc_action` из URL браузера. Поэтому не существует гарантии того, что пользователь имеет OTP для учетной записи после запроса клиента `kc_action=CONFIGURE_TOTP`. If you
want to verify that the user configured two-factor authenticator, the client application may need to check it was configured. Например,
проверяя требования типа 'acr' в токенах.

[id="con-aia-reauth_{context}"]
== Повторная аутентификация во время АИА

В случае, если пользователь уже аутентифицирован в связи с активной сессией SSO, этому пользователю обычно не требуется активно повторная аутентификация. Однако, если этот пользователь активно аутентифицировался более пяти минут назад,
клиент по-прежнему может запросить повторную аутентификацию по запросу некоторых AIA. Из этих руководящих принципов вытекают следующие исключения:

* Для каждого требуемого действия можно настроить максимальный возраст самого действия в <<proc-setting-default-required-actions_{context}, Required actions tab>>.
Если политика не настроена, она по умолчанию будет настроена на пять минут.
* Действие `delete_account` всегда требует активного повторной аутентификации пользователя
* Действие `UPDATE_PASSWORD` может потребовать от пользователя активного повторной аутентификации согласно настроенному <<maximum-authentication-age,Maximum Authentication Age Password policy>>.
В случае, если политика не настроена, также можно настроить его на требуемое действие в <<proc-setting-default-required-actions_{context}, Required actions tab>>
при настройке конкретного обязательного действия. Если политика не настроена ни в одном из этих мест, по умолчанию она занимает пять минут.
* If you want to use a shorter re-authentication, you can still use a parameter query parameter such as  `max_age` with the specified shorter value or eventually `prompt=login`, which will always require user to
actively re-authenticate as described in the OIDC specification. Обратите внимание, что использование `max_age` длиннее 5 минут (или специально настроенного для требуемого действия) не поддерживается.
Значение `max_age` может быть использовано только для того, чтобы сделать значение короче, чем значение по умолчанию пять минут.
* Если <_step-up-flow,Пошаговая аутентификация>> включена и действие - добавление или удаление учётных данных, аутентификация требуется на уровне, соответствующем
данным учетным данным. Это требование существует в том случае, если пользователь уже имеет учетные данные на определенном уровне. Например, если `otp` и `webauthn` настроены в потоке аутентификации как 2nd-factor authenticators
(как в потоке аутентификации на уровне 2) так и у пользователя уже есть учетные данные 2nd-factor (в данном случае `otp` или `webauthn`), пользователь требуется для аутентификации с существующими 2nd-факторными учетными данными для добавления еще одной двухуровневой учётной записи.
Точно так же необходимо удалить существующие учетные данные 2nd-factor (`otp` или `webauthn` в данном случае), аутентификации с существующими учетными данными 2nd-factor уровня. Это требование существует по соображениям безопасности.

[id="con-aia-parameterized_{context}"]
== Параметральная АИА

Некоторые AIA могут потребовать отправки параметра вместе с именем действия. Например, действие `Delete Credential` может быть вызвано только AIA и требует параметра для отправки вместе с именем
этого действия, который указывает на идентификатор удаленной учётной записи. Итак, URL для этого примера будет `kc_action=delete_credential:ce1008ac-f811-427f-825a-c0b878d1c24b`. В этом случае часть
после символа двоеточия (`ce1008ac-f811-427f-825a-c0b878d1c24b`) содержит идентификатор регистрационных данных конкретного пользователя, который должен быть удален. Поле `Delete Credential`
отображает окно подтверждения, где пользователь может подтвердить согласие на удаление учётной записи.

NOTE: <<_account-service,{project_name} Account Console>> обычно использует действие `Удалить учётную запись` при удалении учётной записи 2nd-factor (2-фактор).  Вы можете проверить консоль аккаунтов на примеры, если вы хотите, чтобы
использовать это действие прямо из ваших собственных приложений. Однако, использование консоли аккаунтов лучше всего вместо управления учетными данными из ваших собственных приложений.

[id="con-aia-available-actions_{context}"]
== Доступные действия

Чтобы увидеть все доступные действия, войдите в консоль администратора и выберите `master` реалм. Затем перейдите в правый верхний угол и нажмите на имя пользователя -> выберите вкладку `Realm info` -> `Provider info`. Тогда в таблице найдите SPI `required-action` . В второй колонке
есть доступные провайдеры. Они могут быть использованы как значения параметра `kc_action` (если не параметризованы как описано выше). But note that this can be further restricted based on what actions are enabled for your realm in
the <<proc-setting-default-required-actions_{context}, Required actions tab>>.