// Module included in the following assemblies:

//

// server_admin/topics/users.adoc

[id="proc_creating-otp_{context}"]
= Создание OTP

[role="_abstract"]
Если OTP является условным в вашей сфере, пользователь должен перейти в консоль учетной записи {project_name} для переконфигурирования нового генератора OTP. Если OTP необходим, то при входе пользователь должен перенастроить новый OTP генератор.

В качестве альтернативы вы можете отправить письмо пользователю, который запрашивает сброс OTP генератора. Следующая процедура также применяется, если пользователь уже имеет OTP учетные данные.

.Необходимые предпосылки
* Вы вошли в соответствующий реалм.

//-

.Процедура
. Нажмите *Users* в главном меню. Страница *Пользователи* отображается.
. Выберите пользователя.
. Нажмите на вкладку *Учетные данные*.
. Нажмите *Сброс учетных данных*.
. Установите *Сбросить Действия* на *Настройка OTP*.
. Нажмите *Send Email*. Отправленное письмо содержит ссылку, которая направляет пользователя на страницу установки *OTP*.