// Module included in the following assemblies:

//

// server_admin/topics/users.adoc

[id="proc-creating-user_{context}"]
= Создание пользователей

[role="_abstract"]
Вы создаете пользователей в реалме, где хотите иметь приложения, необходимые этим пользователям. Избегайте создания пользователей в главном мире, который предназначен только для создания других миров.

.Необходимые предпосылки
* Вы находитесь в мире, отличном от мастерского.

//-

.Процедура
. Нажмите *Пользователи* в меню.
. Нажмите *Добавить пользователя*.
. Введите данные для нового пользователя.

ifdef::standalone[]

+
ПРИМЕЧАНИЕ: *Имя пользователя* является единственным обязательным полем.

+
. Нажмите *Сохранить*. После сохранения деталей отображается страница *Управление* для нового пользователя.

endif::[]

ifdef::api-management[]

. Переключить *Проверка электронной почты* на *ВКЛЮЧЕН*.
. Нажмите *Сохранить*.
. В закладке *Учетные данные* установите пароль в обоих полях.
.. Переключитесь *Временно* на *ВЫКЛ*, чтобы избежать сброса пароля при следующем входе в систему.
.. Нажмите *Сбросить пароль*.
.. Нажмите *Изменить пароль*.
.. Нажмите *Сохранить*.
+
endif::[]