// Module included in the following assemblies:

//

// server_admin/topics/users.adoc

[id="proc-setting-password-user_{context}"]
= Установка пароля для пользователя

[role="_abstract"]
Если у пользователя нет пароля, или если пароль был удалён, отобразится раздел *Установить пароль*.

Если у пользователя уже есть пароль, его можно сбросить в разделе *Сбросить пароль*.

.Процедура
. Нажмите *Пользователи* в меню. Страница *Пользователи* отображается.
. Выберите пользователя.
. Нажмите на вкладку *Учетные данные*.
. Введите новый пароль в разделе *Установить пароль*.
. Нажмите *Установить пароль*.
+
NOTE: Если *Временный* *ON*, пользователь должен сменить пароль при первом входе в систему. Чтобы разрешить пользователям хранить указанный пароль, установите *Временное* *ВЫКЛ.* Пользователь должен нажать *Установить пароль* для смены пароля.

= Запрос на сброс пароля

Вы также можете запросить сброс пароля.

.Процедура
. Нажмите *Пользователи* в меню. Страница *Пользователи* отображается.
. Выберите пользователя.
. Нажмите на вкладку *Учетные данные*.
. Нажмите *Сброс учетных данных*.
. Выберите из списка *Обновить пароль*.
. Нажмите *Send Email*. Отправленное письмо содержит ссылку, которая направляет пользователя на окно *Обновить пароль*.
. При необходимости вы можете установить действительность электронной почты. Значение по умолчанию установлено во вкладке *Токен*, в Настройках Регламента*.