// Module included in the following assemblies:

//

// server_admin/topics/users.adoc

[id="proc-searching-user_{context}"]
= Поиск пользователя

Поиск пользователя для просмотра подробной информации о пользователе, такой как группы и роли пользователя.

.Необходимые предпосылки
* Вы находитесь в области, где существует пользователь.

== Поиск по умолчанию

.Процедура
. Нажмите *Users* в главном меню. Эта страница *Пользователи* отображается.
. Введите полное имя, фамилию, имя или адрес электронной почты пользователя, который вы хотите искать в поле поиска. Поиск возвращает всех пользователей, которые соответствуют вашим критериям.
+
Критерии, используемые для соответствия пользователям зависят от синтаксиса, используемого в поле поиска:
.. `"somevalue"` -> выполняет точный поиск строки `"somevalue"`;
.. `\*somevalue*` -> выполняет поиск с ошибками, как `LIKE '%somevalue%'` DB запрос;
.. `somevalue*` или `somevalue` -> выполняет префиксный поиск, как в `LIKE 'somevalue%'` DB запрос.

== Поиск по полям

{project_name} поддерживает прямой поиск пользователей для выбранных полей путем префикса поискового запроса в поле поиска:

* `id:myUUID` -> выполняет точный поиск пользователя по идентификатору для `"myUUID";
* `username:myuser` -> выполняет точный поиск пользователя по имени пользователя `"myuser"`;
* `email:myuser@domain.org` -> выполняет точный поиск пользователя по электронной почте `"myuser@domain.org"`.

Несколько значений могут быть разделены пробелами (например, `id:uuid1 uuid2`) для поиска нескольких пользователей в одном запросе.

== Поиск атрибутов

.Процедура
. Нажмите *Users* в главном меню. Эта страница *Пользователи* отображается.
. Нажмите кнопку *Поиск по умолчанию* и переключитесь на *Поиск атрибутов*.
. Нажмите *Выберите атрибуты* и укажите атрибуты для поиска.
. Установите флажок *Точный поиск* для точного соответствия или оставьте флажком для использования поиска фиксации значений атрибутов.
. Нажмите кнопку *Поиск* для выполнения поиска. Он возвращает всех пользователей, удовлетворяющих критериям.

[NOTE]
====
Поиски, выполняемые на странице *Пользователи* охватывают базу данных {project_name}и настроенные бэкэнды федерации пользователей, такие как LDAP. Пользователи, найденные в федеративных бэкэндах будут импортированы в базу данных {project_name}, если они там не существуют.
====

.Дополнительные ресурсы
* Дополнительную информацию об федерации пользователей см. <_user-storage-federation,User Federation>>.