// Module included in the following assemblies:

//

// server_admin/topics/users.adoc

[id="ref-personal-data-collected_{context}"]
= Личные данные, собранные {project_name}

По умолчанию {project_name} собирает следующие данные:

* Основные данные профиля, такие как электронная почта пользователя, имя и фамилия.
* Базовые данные профиля пользователя, используемые для социальных учетных записей и ссылок на социальную учётную запись при использовании социальной учётной записи.
* Данные устройства, собранные для целей аудита и безопасности, такие как IP-адрес, имя операционной системы и имя браузера.

Информация, собранная в {project_name} , очень легко настраивается. При внесении изменений применяются следующие принципы:

* В регистрационных и учетных бланках могут содержаться такие стандартные поля, как день рождения, пол, гражданство.  Администратор может настроить {project_name} для получения данных от социального провайдера или поставщика хранения данных, таких как LDAP.
* {project_name} собирает учетные данные пользователей, такие как пароль, OTP коды и публичные ключи WebAuthn. Эта информация зашифрована и сохранена в базе данных, поэтому она не видна администраторам {project_name}. Каждый тип учетных данных может включать неконфиденциальные метаданные, видимые администраторам, такие как алгоритм, используемый для хеширования пароля и количество итераций, используемых для хеширования пароля.
* С включенными сервисами авторизации и поддержкой UMA, {project_name} может хранить информацию о некоторых объектах, для которых тот или иной пользователь является владельцем.