[[realm_keys]]
=== Настройка ключей реалма

Протоколы аутентификации, используемые {project_name} , требуют шифрования криптографических подписей, а иногда и
.  Для этого {project_name} использует асимметричные пары ключей, приватный и открытый ключ.

У {project_name} одновременно есть одна активная пара ключей, но также может иметь несколько пассивных ключей. The active key pair
is used to create new signatures, while the passive key pair can be used to verify previous signatures. This makes it
possible to regularly rotate the keys without any downtime or interruption to users.

При создании реалма автоматически создается ключевая пара и самоподписанный сертификат.

.Процедура
. Нажмите *Настройки реалма* в меню.
. Нажмите *Ключи*.
. Выберите *Пассивные ключи* из выпадающего списка для просмотра пассивных ключей.
. Выберите *Отключенные клавиши* из выпадающего списка фильтра для просмотра отключенных клавиш.

Пара ключей может иметь статус `Active`, но до сих пор не выбрана как пара активных ключей для этой сферы.
The selected active pair which is used for signatures is selected based on the first key provider sorted by priority
that is able to provide an active key pair.

==== Поворот клавиш

Мы рекомендуем регулярно вращать ключи. Начните с создания новых ключей с более высоким приоритетом, чем существующие активные ключи. Вместо этого вы можете создать новые ключи с одинаковым приоритетом и сделать предыдущие ключи пассивными.

Как только новые ключи будут доступны, все новые токены и куки будут подписаны с новыми ключами. Когда пользователь аутентифицируется с помощью
приложения, cookie SSO обновляется с помощью новой подписи. When OpenID Connect tokens are refreshed new tokens are
signed with the new keys. В конце концов, все Cookies и токены используют новые ключи и после того как старые ключи могут быть удалены.

Частота удаления старых ключей представляет собой компромисс между безопасностью и убедитесь, что все cookies и токены обновляются. Подумайте о создании новых ключей каждые три-шесть месяцев и удалите старые ключи от одного до двух месяцев после создания новых ключей. Если пользователь не был активен в период между добавляемыми новыми ключами и удаляемыми старыми ключами, этому пользователю придется пройти повторную аутентификацию.

Поворот клавиш также применяется к автономным токенам. Чтобы убедиться, что они обновляются, приложениям необходимо обновить токены перед удалением старых ключей.

==== Добавление сгенерированной пары ключей

Используйте эту процедуру для создания пары ключей, включая самоподписанный сертификат.

.Процедура
. Выберите область в консоли администратора.
. Нажмите *Настройки реалма* в меню.
. Нажмите на вкладку *Ключи*.
. Нажмите на вкладку *Поставщики*.
. Нажмите *Добавить провайдера* и выберите *rsa-generated*.
. Введите число в поле *Приоритет*. Это число определяет, станет ли новая пара ключей активной парой ключей. Наибольшее число делает пару ключей активным.
. Выберите значение для *AES Key size*.
. Нажмите *Сохранить*.

Changing the priority for a provider will not cause the keys to be re-generated, but if you want to change the keysize
you can edit the provider and new keys will be generated.

==== Поворот ключей извлечением сертификата

Вы можете поворачивать ключи извлекая сертификат из созданной RSA пары ключей и используя этот сертификат в новом хранилище.

.Предпосылки
* Сгенерированная пара ключей

//-

.Процедура
. Выберите область в консоли администратора.
. Нажмите *Настройки реалма*.
. Нажмите на вкладку *Ключи*.
+
Появится список *Активных* ключей.
. В строке с ключом RSA щелкните *Сертификат* под *Публичными ключами*.
+
Сертификат появляется в текстовой форме.
. Сохраните сертификат в файл и вложите его в эти строки.
+
[source,bash,subs=+attributes]
----
----Begin Certificate----
<Output>
----End Certificate----
----
. Используйте команду *keytool* для преобразования ключевого файла в формат PEM.
. Удалить текущий сертификат публичного ключа RSA из хранилища ключей.
+
[source,bash,subs=+attributes]
----
keytool -delete -keystore <keystore>.jks -storepass <password> -alias <key>
----
. Импорт нового сертификата в ключевое хранилище
+
[source,bash,subs=+attributes]
----
keytool -importcert -file domain.crt -keystore <keystore>.jks -storepass <password>  -alias <key>
----
. Пересобрать приложение.
+
[source,bash,subs=+attributes]
----
mvn clean install wildfly:deploy
----

==== Добавление существующей пары ключей и сертификата

Чтобы добавить полученную в другом месте пару ключей и сертификат, выберите `Providers` и выберите `rsa` из выпадающего списка. Вы можете изменить
приоритетом, чтобы убедиться, что новая пара ключей станет активной парой ключей.

.Предпосылки
* Файл закрытого ключа. Файл должен быть в формате PEM.

//-

.Процедура
. Выберите область в консоли администратора.
. Нажмите *Настройки реалма*.
. Нажмите на вкладку *Ключи*.
. Нажмите на вкладку *Поставщики*.
. Нажмите *Добавить провайдера* и выберите *rsa*.
. Введите число в поле *Приоритет*. Это число определяет, станет ли новая пара ключей активной парой ключей.
. Нажмите *Обзор...* рядом с *Private RSA Key*, чтобы загрузить файл закрытого ключа.
. Если у вас есть подписанный сертификат на ваш закрытый ключ, нажмите *Обзор...* рядом с *X509 Сертификат*, чтобы загрузить файл сертификата. {project_name} автоматически генерирует самоподписанный сертификат, если вы не загружаете сертификат.
. Нажмите *Сохранить*.

==== Загрузка ключей из Java Keystore

Чтобы добавить пару ключей и сертификат, хранящийся в файле Java Keystore на хосте, выберите `Providers` и выберите `java-keystore`
из выпадающего списка. Вы можете изменить приоритет, чтобы убедиться, что новая пара ключей станет активной парой ключей.

Для загрузки соответствующей цепочки сертификатов необходимо импортировать ее в файл Java Keystore с тем же псевдонимом `Key Alias`, который используется для загрузки ключевой пары.

.Процедура
. Выберите область в консоли администратора.
. Нажмите *Настройки реалма* в меню.
. Нажмите на вкладку *Ключи*.
. Нажмите на вкладку *Поставщики*.
. Нажмите *Добавить провайдера* и выберите *java-keystore*.
. Введите число в поле *Приоритет*. Это число определяет, станет ли новая пара ключей активной парой ключей.
. Введите желаемый *Алгоритм*. Обратите внимание, что алгоритм должен соответствовать типу ключа (например, `RS256` требует закрытого ключа RSA, `ES256` закрытый ключ ЕС или `AES` секретный ключ AES).
. Введите значение для *Keystore*. Путь к ключевому файлу. Ключевое хранилище должно быть расположено в папке с именем Realm в основном каталоге ключей (по умолчанию `data` в каталоге {project_name}с установочной папкой). Для области `test` ключевой файл должен находиться внутри `${kc.home.dir}/data/test`. Таким образом, файл ключевого хранилища изолирован между мирами. Если путь относительный, то файл будет расположен из этой папки.
+
[NOTE]
====
Каталог ключей может быть настроен с помощью опции `$$spi-keys--java-keystore--keystores-path$$`. Например:

```
kc.[sh|bat] start --spi-keys--java-keystore--keystores-path /path/to/keystores
```
====
. Введите *Keystore Password*. Параметр может ссылаться на значение из внешнего <_vault-administration,vault>>.
. Введите значение *Keystore Type* (`JKS`, `PKCS12` или `BCFKS`).
. Введите значение *псевдонима ключа* для загрузки из хранилища ключей.
. Введите *Ключевой пароль*. Параметр может ссылаться на значение из внешнего <_vault-administration,vault>>.
. Введите значение *Использование ключа* (`sig` для подписания или `enc` для шифрования). Обратите внимание, что использование должно соответствовать типу алгоритма (например, `RS256` это `sig`, но `RSA-OAEP` это `enc`)
. Нажмите *Сохранить*.

[WARNING]
====
Не все типы ключей поддерживают все типы ключей. Например, `JKS` во всех режимах и `PKCS12` в режиме fips (`BCFIPS` провайдер) не может хранить записи с секретным ключом.
====

==== Делать пассивные ключи

.Процедура
. Выберите область в консоли администратора.
. Нажмите *Настройки реалма* в меню.
. Нажмите на вкладку *Ключи*.
. Нажмите на вкладку *Поставщики*.
. Нажмите на поставщика ключа который вы хотите сделать пассивным.
. Включите *Активность* в *Выкл*.
. Нажмите *Сохранить*.

==== Отключение клавиш

.Процедура
. Выберите область в консоли администратора.
. Нажмите *Настройки реалма* в меню.
. Нажмите на вкладку *Ключи*.
. Нажмите на вкладку *Поставщики*.
. Нажмите на поставщика ключа который вы хотите сделать пассивным.
. *Включено* в *Выкл*.
. Нажмите *Сохранить*.

==== Собираемые ключи

У {project_name} есть ключи подписи, хранящиеся только локально, и они никогда не передаются клиентским приложениям, пользователям или другим объектам
. Однако, если вы думаете, что ваш ключ подписания области был скомпрометирован, сначала нужно создать новую пару ключей, как описано выше, и
а затем немедленно удалить скомпрометированную пару ключей.

В качестве альтернативы, вы можете удалить провайдера из таблицы «Поставщики».

.Процедура
. Нажмите *Клиент* в меню.
. Щелкните *security-admin-console*.
. Прокрутите вниз до раздела *Настройки доступа*.
. Заполните поле *Админ URL*.
. Нажмите на вкладку *Расширенные*.
. Нажмите *Установить* сейчас в разделе *Аннулирование*.
. Нажмите *Отправить*.

Отправка политики не до того, что клиентские приложения не принимают существующие токены, подписанные скомпрометированным ключом. Клиентское приложение вынуждено загружать новые пары ключей из {project_name} , так что токены, подписанные скомпрометированным ключом, будут недействительными.

[NOTE]
====
REST и конфиденциальные клиенты должны задать *Админ URL*, чтобы {project_name} мог отправлять клиентам pushed не перед запросом политики.
====