[[_master_realm_access_control]]
=== Управление доступом к миру

Область `master` в {project_name} - это особый мир, который отличается от других игровых миров.
Пользователям `master` мира {project_name} может быть предоставлено разрешение на управление нулевыми или более мирами, развернутыми на сервере {project_name}.
При создании реалма {project_name} автоматически создает различные роли, предоставляющие права доступа к этому новому реалму.
Доступ к конечным точкам консоли администратора и администратора REST можно контролировать путем сопоставления этих ролей с пользователями в области «master».
Можно создавать несколько суперпользователей, а также пользователей, которые могут управлять только конкретными мирами.

==== Глобальные роли

В области «master» есть две роли реального уровня.
К их числу относятся:

* админ
* царство-мир

Пользователи с ролью `admin` являются суперпользователями и имеют полный доступ к управлению любым реалмом на сервере.  Пользователям с ролью `create-realm`
разрешено создавать новые реалмы.  Они получат полный доступ к создаваемым ими новым мирам.

IMPORTANT: Администраторам с ролью `create-realm` без роли `admin` также потребуется роль `query-realms`, чтобы создать и перечислить миры в консоли администратора.

==== Определенные роли области

Пользователям "master" Realm могут быть предоставлены права управления одним или несколькими игровыми мирами в системе.
Каждая область {project_name} представлена клиентом в «master».
Имя клиента - `<realm name>-realm`.  These clients each have client-level roles defined which define varying
level of access to manage an individual realm.

Доступные роли:

* создать-клиент
* олицетворение
* авторизация менеджера
* управленческие клиенты
* управленческие события
* Идентификационные провайдеры
* управляющие организации
* управленческая область
* управляющие пользователи
* запросы-клиенты
* группы запросов
* организации-запросы
* миры запросов
* запросов-пользователей
* просмотр авторизации
* витрина клиентов
* просмотр событий
* провайдеры просмотра
* виз-организации
* область просмотра
* пользователи

Назначить роли, которые вы хотите для ваших пользователей, и они смогут использовать только эту часть консоли администрирования.

IMPORTANT: Администраторы с ролью `manage-users` смогут назначать роли администратора только тем пользователям, которые у них есть.  Таким образом, если администратор имеет роль `manage-users`, но не имеет роли `manage-realm`, он не сможет назначить эту роль.

==== Передача ролей администратору пользователям

При предоставлении роли администратора пользователям в реалме, вы должны явно назначить эти роли пользователю, либо прямым сопоставлением ролей
(включая роли, предоставляемые через сопоставления поставщиков идентификации), либо присвоением пользователя группе, имеющей соответствующие сопоставления ролей.
Это верно даже для пользователей в «master».

Несмотря на то, что вы можете создавать карты протоколов для клиента для сопоставления ролей администратора с токенами, роли администратора
будут проигнорированы, когда пользователь аутентифицируется и не будет включен в токен.  This is because admin roles are only
used for authorization to access the Admin Console and Admin REST endpoints, and are not intended to be used for
application access control.

По существу, доступ к API администратора предоставляется только пользователям с ролями администратора, явно назначенным через прямую роль
сопоставления или членство в группах, и не пользователям с ролями администратора сопоставляются только с протоколом клиента.