[[_per_realm_admin_permissions]]
=== Администрированные консоли Realm

У каждого реалма есть специальная консоль администратора, к которой можно получить доступ, зайдя в url `{kc_admins_path}/{realm-name}/console`.
Пользователям этого реалма могут быть предоставлены права управления реалмами, назначая соответствующие роли пользователя.

Каждая область имеет встроенный клиент под названием «realm-management».  You can view this client by going to the
`Clients` left menu item of your realm.  Этот клиент определяет роли клиентского уровня, которые определяют разрешения, которые могут быть предоставлены для управления реалмом.

* создать-клиент
* олицетворение
* авторизация менеджера
* управленческие клиенты
* управленческие события
* Идентификационные провайдеры
* управляющие организации
* управленческая область
* управляющие пользователи
* запросы-клиенты
* группы запросов
* организации-запросы
* миры запросов
* запросов-пользователей
* Админ реалма
* просмотр авторизации
* витрина клиентов
* просмотр событий
* провайдеры просмотра
* виз-организации
* область просмотра
* пользователи

Назначить роли, которые вы хотите для ваших пользователей, и они смогут использовать только эту часть консоли администрирования.