[[_client_policies]]
= Политики Клиента

Для упрощения безопасности клиентских приложений, полезно единообразно реализовывать следующие моменты.

* Установка политик для какой конфигурации может иметь клиент
* Проверка конфигурации клиента
* Соответствие необходимым стандартам безопасности и профилям, таким, как API финансового уровня (FAPI) и OAuth 2.1

Для унифицированной реализации этих точек вводится концепция _Клиентских Политик_.

== Варианты использования

Клиентские Политики понимают следующие моменты, упомянутые ниже.

Установка политик для какой конфигурации может иметь клиент:: Настройки конфигурации клиента могут быть принудительно применены политикой клиента во время создания/обновления клиента, но и во время запросов OpenID Connect к {project_name} серверу, которые связаны с конкретным клиентом.
{project_name} поддерживает аналогичную вещь также через *Условия регистрации клиентов*, описанные в *регистрационной службе* по ссылке:{securing_apps_link}[Руководство по обеспечению безопасности приложений и услуг].
Однако регистрация клиентов может охватывать только регистрацию OIDC Dynamic Клиентов. Клиентские Политики описывают не только то, что может сделать Клиентские Политики, но и другие клиентские
способы регистрации и настройки. Текущие тарифы на регистрацию Клиентов заменяются Политикой Клиента.
Проверка конфигурации клиента:: {project_name} поддерживает валидацию, следует ли клиент настройкам, как Proof Key для обмена кодов,
Request Object Algorithm, Токен "Владелец Ключа" и так далее на некоторых конечных пунктах, таких как "Конечная точка авторизации" токена и так далее.
Они могут быть определены каждым элементом настроек (в консоли администратора, переключателе, выпадающем меню и так далее). To make the client application secure, the administrator needs to set
many settings in the appropriate way, which makes it difficult for the administrator to secure the client application.
Клиентские Политики могут проверить эти конфигурации клиентов, упомянутые только выше, и они также могут быть использованы для автоматической настройки некоторых переключателей конфигурации клиента для удовлетворения
дополнительных требований безопасности. В будущем индивидуальные настройки конфигурации клиента могут быть заменены клиентскими политиками, непосредственно выполняющими требуемые проверки.
Проверьте <<ssrf,dedicated section>> чтобы увидеть вариант использования о том, как защитить сервер путем проверки uris клиента.
Соответствие необходимым стандартам безопасности и профилям, таким как FAPI и OAuth 2.1:: _Глобальные профили клиентов_ - это профили, предварительно настроенные в {project_name} по умолчанию. Они предварительно настроены на соответствие стандартным профилям безопасности, таким как *FAPI* и *OAuth 2. * в ссылке:{securing_apps_link}[защита приложений],
позволяет администратору защитить клиентское приложение в соответствии с определенным профилем безопасности. На данный момент {project_name} имеет глобальные
профили для поддержки FAPI и OAuth 2.1 спецификаций. The administrator will just need to configure the client policies to specify which clients should
be compliant with the FAPI and OAuth 2.1. Администратор может настраивать профили клиентов и политики клиентов, таким образом, чтобы клиенты {project_name} могли быть легко совместимы с различными профилями безопасности
типа SPA, Продвинутое приложение, Open Banking и так далее.

== Protocol

Концепция политики клиента не зависит от конкретного протокола. В настоящее время {project_name} особенно поддерживает профили клиентов по ссылке:{adminguide_link}#con-oidc_server_administration_guide[OpenID Connect (OIDC) протокол], но есть и
профиль клиента доступен по ссылке:{adminguide_link}#_saml[протокол SAML].

== Архитектура

Клиентские Политики состоят из четырех строительных блоков: "Условия", "Исполнитель", "Профиль" и "Политика".

=== Состояние

Условие определяет, к какому клиенту принимается политика и когда она принимается. Некоторые условия проверяются на момент создания/обновления клиента, когда другие условия
проверяются во время запросов клиента (OIDC запрос авторизации, Запрос конечной точки токена и так далее). Условие проверяет, удовлетворяет ли один из указанных критериев. Например,
некое условие проверяет конфиденциальность типа доступа клиента.

Условие не может быть использовано исключительно самостоятельно. Он может быть использован в <<_client_policy,policy>>, который описан позже.

Условие может быть сконфигурировано таким же как и другие настраиваемые провайдеры. Что может быть настроено в зависимости от природы каждого условия.

Предусмотрены следующие условия:

Способ создания/обновления клиента::
* Динамическая регистрация Клиента (анонимная или аутентифицированная с помощью начального токена доступа или токена регистрационного доступа)
* Админ REST API (консоль администратора и так далее)

Итак, например, при создании клиента, условие может быть сконфигурировано для оценки истинности при создании OIDC Dynamic Client Registration без токена доступа
(Anonymous Dynamic Client Registration). Поэтому это условие может использоваться, например, для обеспечения того, чтобы все клиенты, зарегистрированные через OIDC Dynamic Client Registration
были FAPI или OAuth 2. комплимент.

Автор клиента (отмеченный присутствием конкретной роли или группы):: On OpenID Connect dynamic client registration, an author of a client is the end user who was authenticated to get an access token for generating a new client, not Service
Account of the existing client that actually accesses the registration endpoint with the access token. При регистрации администратором REST API автор клиента является конечным пользователем
как администратор {project_name}.
Тип доступа клиента (конфиденциальный, публичный, только для предъявителя):: Например, когда клиент отсылает запрос на авторизацию, он утверждается в том случае, если клиент является конфиденциальным. Конфиденциальный клиент включил аутентификацию клиентов, когда публичный клиент отключил аутентификацию клиентов. Только носитель - устаревший тип клиента.
Область действия клиента:: Вычисляет истину, если клиент имеет определенную область действия клиента (по умолчанию или необязательная область, используемая в текущем запросе). Это может быть использовано например, для того, чтобы
запросы авторизации OIDC с помощью области `fapi-example-scope` были совместимы с FAPI.
Роль клиента:: Применяется для клиентов с ролью клиента указанного имени. Typically you can create a client role of specified name to requested clients and use it as a "marker role" to make
sure that specified client policy will be applied for requested clients.

NOTE: Часто существует вариант использования для требования применения конкретной клиентской политики для указанных клиентов, таких как `my-client-1` и `my-client-2`. The best way to achieve this result
is to use a *Client Role* condition in your policy and then a create client role of specified name to requested clients. This client role can be used as a "marker role" used solely
for marking that particular client policy for particular clients.

Имя домена клиента, хост или IP-адрес:: Применяется для определенных доменных имен клиента. Или в случаях, когда администратор регистрирует/обновляет клиента с определенного хоста или IP-адреса.
Атрибут клиента:: Применяется к клиентам с атрибутом клиента указанного имени и значения. Если вы укажете несколько атрибутов клиента, они будут оцениваться с использованием условий И .
Если вы хотите вычислить использование ИЛИ условий, установите это условие несколько раз.
Любой клиент:: Это условие всегда вычисляет истину. Он может быть использован, например, для обеспечения того, чтобы все клиенты в определенном мире соответствовали FAPI.
Состояние ACR:: Применяется, когда ACR значение запрошенное в запросе аутентификации соответствует значению, сконфигурированному в условии. Например, он может быть использован для выбора потока аутентификации на основе запрошенного ACR значения. Подробнее см. <<_client-policy-auth-flow, related documentation>> и https://openid.net/specs/openid-connect-core-1_0.html#acrSemantics[official OIDC specification].
Тип подарка:: Вычисляет истину при использовании определенного типа грантов. Например, он может использоваться в сочетании с клиентскими рамками для блокирования запроса на обмен токенов, когда запрашивается конкретная область действия.
Псевдоним поставщика идентификации:: Условие, которое проверяет поставщика идентификации, участвующего в запросе клиента. Список алиасов IdP может быть настроен. Условие вычисляет истину, если один из них связан с запросом. Она применяется только к операциям, в которых участвует IdP (например, субсидия JWT Authorization).

Смотрите <<_client_policy_conditions_evaluation,dedicated section>> для подробностей о том, как оцениваются условия.

=== Исполнитель

Исполнитель указывает, какое действие выполняется по клиенту, на который утверждается политика. Исполнитель выполняет одно или несколько указанных действий. Например,
некоторые исполнители проверяют соответствие значения параметра `redirect_uri` в запросе авторизации с одним из предварительно зарегистрированных URI перенаправления на
Endpoint авторизации и отклоняют этот запрос, если нет.

Исполнитель не может использоваться исключительно самим собой. Он может быть использован в <_client_policy_profile>>, который описан позже.

Исполнитель может быть сконфигурирован таким же, как и другие настраиваемые провайдеры. Что может быть настроено зависит от природы каждого исполнителя.

Исполнитель действует на различные события. Реализация исполнителя может игнорировать определенные типы событий (например, исполнитель для проверки OIDC объекта `request` действует только
в запросе авторизации OIDC). События:

* Создание клиента (включая создание с помощью динамической регистрации клиента)
* Обновление клиента
* Отправка запроса на авторизацию
* Отправка запроса токена
* Отправка запроса на обновление токена
* Отправка запроса на отзыв токена
* Отправка запроса на интроспективность токена
* Отправка запроса пользовательской информации
* Отправка запроса на выход с помощью ключа обновления (обратите внимание, что выход с токеном refresh является проприетарной функцией {project_name} не поддерживается любой спецификацией. Рекомендуется полагаться на <_oidc-logout,официальный OIDC logout>>).

При каждом событии исполнитель может работать в несколько фаз. For example, on creating/updating a client, the executor can modify the client configuration by autoconfigure specific client
settings. После этого исполнитель проверяет эту конфигурацию в фазе проверки.

Одна из целей этого исполнителя заключается в реализации требований безопасности профилей клиента, таких как FAPI и OAuth 2.1. Для этого необходимы следующие исполнители:

* Принудительная защита <<_client-credentials,метод аутентификации клиента>>
* Используются <_mtls-client-certificate-bound-tokens,Держатель-ключ-tokens>>
* Использовать <_proof-key-for-code-exchange,Proof Key для обмена кодами (PKCE)>>
* Использовать алгоритм защищенной подписи для <<_client-credentials,Signed JWT client authentication (private-key-jwt)>>
* Принудительно использовать URL перенаправления HTTPS и убедиться, что настроенный URI перенаправления не содержит шаблонов
* Принудительно использовать объект `request` OIDC, удовлетворяющий высокий уровень безопасности
* Принудительный тип ответа гибридного потока OIDC, включая идентификационный токен, используемый в качестве _отдельной подписи_ как описано в спецификации FAPI 1, , это означает, что ID токен возвращен в ответ авторизации не будет содержать данные профиля пользователя
* Принудительно использовать более безопасные параметры `state` и `nonce` для предотвращения CSRF
* Принудительный алгоритм защиты подписи при регистрации клиента
* Параметр `binding_message` используется для CIBA запросов
* Обеспечить <<_secret_rotation, клиентская секретная ротация>>
* Принудительный маркер доступа к регистрации клиента
* Обязательная проверка того, является ли клиент тем клиентом, которому было выдано намерение в случае использования, когда намерение выдается перед началом потока кода авторизации для получения токена доступа типа OpenBanking
* Принудительно запрещать неявный и гибридный поток
* Проверка на наличие необходимых параметров, включенных в запрос авторизации
* Принудительное <_dpop-bound-tokens,DPoP-привязка токено>> (доступно при включенной функции `dpop`)
* Обеспечить <<_using_lightweight_access_token, используя легкий токен>>
* Убедитесь, что <_refresh_token_rotation,token refresh rotation>> пропущен, и токен refresh не возвращается из ответа токена обновления
* Принудительно указать корректный URI перенаправления, который необходим для спецификации OAuth 2.1
* Принудительная привязка SAML перенаправления не может быть использована или SAML запросы и утверждения подписаны
* Принудительные рамки предоставлены по ссылке:{securing_apps_token_exchange_link}#_standard-token-exchange[Standard token exchange] или в гранте JWT Authorization Grant ограничены исходным кодом `subject_token` или `assertion` JWT. Этот исполнитель допускает лишь понижение пределов представленного утверждения. Возвращается ошибка, если запрашивается какая-либо дополнительная область, первоначально не предоставленная JWT.
* Принудительные претензии в отношении субсидий на утверждение (`subject_token` в Обмене Токенов и `assertion` в Гранте JWT Authorization). Исполнитель обеспечивает присутствие и специфические ценности претензии в JWT. Он использует регулярные выражения Java, поэтому он достаточно универсален.
* Добавьте по умолчанию **тему DN** для службы регистрации клиента, когда настроена аутентификация TLS (`tls_client_auth`) (см. *Использование службы регистрации клиента* по ссылке:{securing_apps_link}[securing apps] для дополнительной информации). Исполнитель `tls-client-auth-ca-subject-dn` может быть использован для предоставления нового обязательного атрибута в интерфейсе регистрации клиента. Он также может привести настроенное название ЦА, чтобы отклонить нежелательные значения.

Другим доступным исполнителем является `auth-flow-enforce`, который может быть использован для обеспечения потока аутентификации во время запроса аутентификации. Например, он может использоваться для выбора потока, основанного на определенных условиях, таких как конкретные области действия или ACR значения. Подробнее см. <<_client-policy-auth-flow, related documentation>>.

[[_client_policy_profile]]
=== Профиль

Профиль состоит из нескольких исполнителей, которые могут реализовать профиль безопасности, например FAPI и OAuth 2.1. Профиль может быть настроен администратором REST API (консоль администратора) вместе с его исполнителями.
Существуют три _глобальных профиля_ и они настроены в {project_name} по умолчанию с предварительно настроенными исполнителями в соответствии с FAPI 1 Baseline, FAPI 1 Advanced, FAPI CIBA, FAPI 2 и OAuth 2. спецификации.
Более подробная информация существует в разделе *FAPI* и *OAuth 2.1* по ссылке:{securing_apps_link}[защита приложений].

[[_client_policy_policy]]
=== Политика

Политика состоит из нескольких условий и профилей. Данная политика может быть принята для клиентов, удовлетворяющих всем условиям данной политики. Политика относится к нескольким профилям, и все
исполнители этих профилей выполняют свою задачу по отношению к клиенту, к которому применяется эта политика.

== Конфигурация

Политики, профили, условия, исполнители могут быть настроены администратором REST API, что также означает консоль администратора. Для этого есть вкладка _Realm_ -> _Realm Settings_ -> _Client Policies_
, это означает, что администратор может иметь политики клиентов в одном реалме.

_Глобальные профили клиентов_ автоматически доступны в каждом реалме. Однако по умолчанию нет клиентских политик
настроенных по умолчанию. Это означает, что администратор всегда должен создавать любую политику клиентов, если они хотят, например, чтобы клиенты своего реалма соответствовали FAPI. Глобальные
профили не могут быть обновлены, но администратор может легко использовать их в качестве шаблона и создать свой собственный профиль, если он хочет внести некоторые незначительные изменения в глобальные конфигурации профиля.
JSON Editor доступен в консоли администратора, что упрощает создание нового профиля на основе глобального профиля.

[[_client_policy_conditions_evaluation]]
== Оценка условий

Политика клиента оценивается таким образом, что сконфигурированные условия оцениваются в ходе конкретного запроса. Оценка одного условия может быть завершена в любом из следующих состояний:

* **Да** - Состояние было успешно оценено. Например, условие «client-scopes» вычисляется в «yes», когда определенная конфигурация клиентской границы присутствует в конкретном запросе конкретного клиента.
* **не** - Условие было оценено в false. Например, условие «client-scopes» вычисляется в «нет», когда конкретная сконфигурированная область действия клиента отсутствует в конкретном запросе конкретного клиента.
* **Воздержались** - Состояние не применимо к конкретному запросу и поэтому оценка состояния игнорируется (в режиме по умолчанию). Например, "identity-provider-condition`
оценивается только во время запросов при участии идентификатора провайдера (например, во время ссылки:{securing_apps_jwt_authorization_grant_link}[JWT Authorization grant requests]), но
проигнорировал большинство других запросов.

В случае, если условие настроено с включенной опцией **Негативная логика**, результат будет отменен. Таким образом, когда оценка закончилась словами «нет», она будет изменена на «да» или наоборот.
Условие, оцениваемое «abstain» по-прежнему считается «abstain», когда **отрицательная логика** включена.

По умолчанию, оценка политики удовлетворена, когда хотя бы одно условие вычисляет значение `yes` и ни одно из условий не вычисляет значение `no`. Условия, которые оценивают
`abstain` игнорируются. Однако при настройке клиентской политики в режиме `STRICT`, тогда все условия должны быть оценены до «да», и ни одно из условий не может оценивать «нет» или «abstain».
Когда оценка политики будет выполнена, профили клиентов, привязанные к конкретной политике клиента, будут инициированы. See the example in the
link:{developerguide_link}#_identity-brokering-apis-client-policies[identity provider API section] on how the `STRICT` mode can be useful to enforce certain rules.

WARNING: Некоторые типы условий вычисляются во всех типах запросов, однако некоторые типы условий вычисляются только во время некоторых запросов. For instance, some conditions
might be evaluated just during registration or update of new client, when some other conditions are evaluated at runtime during specific requests. In some cases, it may
not be obvious whether particular condition is evaluated or not. После настройки политики клиента настоятельно рекомендуется проверить ваши сценарии, чтобы убедиться, что политика клиента
работает как ожидалось.

== Устранение проблем

When checking evaluation of client policies, it is recommended to enable `TRACE` logging category `org.keycloak.services.clientpolicy` to have some more logging during
evaluation of client policies. Смотрите ссылку:{loggingguide_link}[{loggingguide_name}] для подробной информации о том, как включить регистрацию для конкретной категории.

== Совместимость с назад

Политики Клиентов могут заменить политику регистрации Клиентов, описанную в *Регистрационной службе* по ссылке:{securing_apps_link}[{securing_apps_name}].
Тем не менее, Регистрационные Политики Клиентов еще не существуют. This means that for example during a Dynamic Client Registration request to create/update a client, both client policies and
client registration policies are applied.

Текущие планы предусматривают удаление функции Регистрационных Политик Клиента и автоматическое перенесение существующих регистрационных политик Клиента в новые Политики Клиента.

== Пример секретной ротации Клиента

Смотрите пример настройки <<_proc-secret-rotation,client secret rotation>.

== Защита URI клиента

Для клиента можно зарегистрировать много URI для различных целей, таких как перенаправление URI для кода авторизации, JWKS URI для получения JWK Set, privacy URI, политика URI, логотип URI, идентификатор сектора URI и др.

Хорошей практикой является добавление как можно большей защиты для этих Унифицированных Идентификаторов Ресурсов для предотвращения вредоносного использования. Например, вы можете применять URI для разрешения только определённым хостам, принимать только HTTPS, или сопоставлять любой желаемый шаблон, используя регулярные выражения.

Клавиатура с клиентскими политиками, предоставляет конкретных исполнителей для защиты различных URI клиентов:

* *Безопасные URI клиентов*: Общеизвестный исполнитель, который обязывает все URI клиента принимать только HTTPS и не принимать любые шаблоны.
* *Безопасное перенаправление Унифицированных Идентификаторов Ресурсов*: Исполнитель, который позволяет разным уровням валидации для редиректов URI, такие как IPv4 и IPv6 адреса циклов, HTTP-схема подстановок, только разрешенные домены, или обеспечение OAuth 2. соблюдение.
* *Исполнитель шаблонов защищенных URI*: Этот исполнитель является наиболее универсальным и гибким для проверки URL-адресов клиентов. Он позволяет выбрать только из списка URI, которые вы хотите проверить, и затем проверяет их, предоставляя список разрешенных шаблонов с помощью регулярных выражений. Исследуйте это <<ssrf,dedicated section>> чтобы увидеть, как этот исполнитель может быть использован для предотвращения SSRF атаки.