[[_secret_rotation]]
= Ротация Секретного Клиента

:tech_feature_name: Ротация Секретного Клиента
:tech_feature_id: ротация клиента

include::../../../topics/templates/techpreview.adoc[]

Для клиента с <_client-credentials, Confidential>> <<_access-type, Client authentication>> {project_name} поддерживает функциональность поворачивания секретов клиента через <_client_policy, Client Policies>>.

Политика ротации клиентов обеспечивает большую безопасность для решения таких проблем, как утечка секретов. {project_name} поддерживает до двух одновременно активных секретов для каждого клиента. Политика управляет ротацией в следующих настройках:

* *Секретное истечение:* [seconds] - Когда секрет поворачивается, это истечение времени новой секреты. Сумма, _in seconds_, добавлена в дату секретного создания. Рассчитано при исполнении политики.
* *Срок действия повернутого секрета:* [seconds] - Когда секрет поворачивается, это значение является оставшимся временем истечения срока действия старой тайны. Это значение должно быть всегда меньше, чем секретный срок действия. Когда значение равно 0, старый секрет будет немедленно удален во время вращения клиента. Сумма, _in seconds_, добавлена в дату тайного вращения. Рассчитано при исполнении политики.
* *Оставшееся время ротации во время обновления:* [seconds] - Период времени, когда динамическое обновление должно выполнять вращение секретной информации клиента. Рассчитано при исполнении политики.

Когда происходит секретное вращение клиента, сгенерирован новый основной секрет, а старый главный секрет клиента становится вторичным секретом с новой датой истечения срока действия.

== Правила для вращения секретного ключа клиента

Вращения не происходят автоматически или через фоновый процесс. Для выполнения вращения требуется действие по обновлению клиента, либо через консоль администратора {project_name} через функцию *Перегенерировать Secret*, на вкладке учетные данные клиента, либо через REST API. При вызове действия по обновлению клиента, секретное вращение происходит в соответствии с правилами:

* Если значение *Секретного истечения* меньше, чем текущая дата.
* При динамическом запросе регистрации клиентов-обновлений клиента, секрет клиента будет автоматически повернут, если значение *Оставшееся время ротации во время обновления* совпадает с периодом между текущей датой и *секретной окончанием*.

Дополнительно через Администратор REST API можно принудительно вращать клиента в любое время.

[NOTE]
====
При создании новых клиентов, если активна секретная политика ротации клиента, поведение будет применяться автоматически.
====

WARNING: Чтобы применить режим ротации секретной информации к существующему клиенту, обновите этот клиент после того, как вы определите политику, чтобы это поведение применялось.