[[_service_accounts]]
= Использовать сервисную учетную запись

.Процедура
. Нажмите *Клиент* в меню.
. Выберите клиента.
. Нажмите на вкладку *Настройки*.
. Переключить <<_access-type, аутентификация клиента>> на *On*.
. Установите флажок *Сервисный аккаунт*, чтобы убедиться, что он включен.
. Нажмите *Сохранить*.
. Настройте <<_client-credentials, client credentials>>.
. Нажмите на вкладку *Клиентские фотографии*, выберите выделенную область клиента (обычно первую область клиента), более подробная информация <<_client_scopes_dedicated,в этом разделе>) и выберите вкладку *Scope* области действия клиента.
. Убедитесь, что у вас есть роли или переключение *Полная рамка* на *ВКЛЮЧЕНИЕ*. Обратите внимание, что этот параметр полезен только в целях разработки и в производстве, рекомендуется отключить этот переключатель и правильно настроить области ролей. Подробности об этом переключателе описаны в <_role_scope_mappings, этом разделе>> и в <_oidc_token_role_mappings,этом разделе>>.
. Нажмите на вкладку *Роли учетной записи* вашего клиента
. Настройте роли, доступные этой учетной записи для вашего клиента.

Роли из токенов доступа являются пересечением:

* Сопоставления рамок ролей клиента в сочетании с сопоставлениями ролей унаследованными от связанных клиентских рамок.
* Роли сервисных аккаунтов.

REST URL для вызова это `{kc_realms_path}/{realm-name}/protocol/openid-connect/token`. Этот URL-адрес должен быть вызван как POST запрос и требует, чтобы вы отправляли учетные данные клиента с запросом.

По умолчанию, Учетные данные клиента представлены clientId и clientSecret клиента в заголовке *Authorization: Basic* но вы также можете аутентифицировать клиента с подписанным JWT утверждением или любым другим пользовательским механизмом для аутентификации клиентов.

Вам также нужно установить параметр *grant_type* на "client_credentials" согласно спецификации OAuth2.

Например, POST вызов для получения сервисной учетной записи может выглядеть следующим образом:

[source,subs=+attributes]
----

    POST {kc_realms_path}/demo/protocol/openid-connect/token
    Authorization: Basic cHJvZHVjdC1zYS1jbGllbnQ6cGFzc3dvcmQ=
    Content-Type: application/x-www-form-urlencoded

    grant_type=client_credentials
----

Обратите внимание, что значение `cHJvZHVjdC1zYS1jbGllbnQ6cGFzc3dvcmQ=`, используемого в заголовке `Authorization`, — это значение кодировки Base64 clientId и clientSecret
в формате, предписанном заголовком `Authorization: Basic`. В этом примере идентификатор клиента является `product-sa-client` и секрет клиента был `password` и, следовательно, это значение было получено, например,
этой командой в Unix платформе:

[source,bash]
----
echo 'product-sa-client:password' | base64
----

Вместо использования заголовка `Authorization: Basic`, также можно отправить учетные данные в качестве параметров `client_id` и `client_secret` POST запроса. For other client credentials methods,
the format of the parameters would be different as described above.

Ответ будет похож на https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.3[Access Token Response] в спецификации OAuth 2.0.

[source]
----

HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Cache-Control: no-store
Pragma: no-cache

{
    "access_token":"eyJhbGciOiJSUzI1NiIs...",
    "token_type":"Bearer",
    "expires_in":60,
    "scope": "email profile"
}
----

По умолчанию возвращается только токен доступа. Не возвращен токен обновления, и ни одна сессия не создается
на стороне {project_name} по умолчанию после успешной аутентификации. Из-за отсутствия токена обновления, требуется повторная аутентификация по истечении срока действия токена доступа. Однако, эта ситуация не означает никаких дополнительных накладных расходов для сервера {project_name} , так как сеансы не создаются по умолчанию.

В этой ситуации нет необходимости. Тем не менее, полученные токены доступа могут быть отменены, посылая запросы на конечную точку OAuth2, как описано в разделе xref:con-oidc_{context}[OpenID Connect Endpoints].

[role="_additional-resources"]
Подробнее см. <<_client_credentials_grant,Client Credentials Grant>>.