=== Аутентификация реестра распространения v2

[NOTE]
====
Docker аутентификация по умолчанию отключена. Для включения аутентификации docker смотрите https://www.keycloak.org/server/features[Включение и отключение функций] {section}.
====

[role="_abstract"]
link:https://distribution.github.io/distribution/spec/auth/[Distribution Registry V2 Authentication] - это протокол, похожий на OIDC, который аутентифицирует пользователей в реестрах Distribution.  Реализация {project_name}этого протокола позволяет клиентам Docker использовать сервер аутентификации {project_name} для аутентификации в реестре. В этом протоколе используются стандартные токены и механизмы подписи, но он отклоняется от истинной реализации OIDC. Он отличается использованием очень специфического формата JSON для запросов и ответов, а также сопоставлением имен репозиториев и разрешений для механизма OAuth.

==== Процесс аутентификации Docker

Процесс аутентификации описан в link:https://distribution.github.io/distribution/spec/auth/token/[Docker API documentation]. Ниже приводится сводка с точки зрения сервера аутентификации {project_name}:

* Выполните `docker login`.
* Клиент Docker запрашивает ресурс из реестра Distribution.  Если ресурс защищен и в запросе нет токена аутентификации, сервер Distribution registry отвечает с HTTP-сообщением 401 с некоторой информацией о требуемых разрешениях и расположением сервера авторизации.
* Docker client конструирует запрос на аутентификацию на основе HTTP 401 из регистра Distribution. Клиент использует локально кэшированные учётные данные (из команды `docker login`) в рамках link:https://datatracker.ietf.org/doc/html/rfc2617[HTTP Basic Authentication] запроса на сервер аутентификации {project_name}.
* Сервер аутентификации {project_name} пытается аутентифицировать пользователя и вернуть тело JSON, содержащее токен управляющего OAuth-стилем.
* Клиент Docker получает токен предъявителя от JSON ответа и использует его в заголовке авторизации для запроса защищенного ресурса.
* Реестр распределения получает новый запрос на защищаемый ресурс с токеном с сервера {project_name}. Реестр проверяет токен и предоставляет доступ к запрошенному ресурсу (если это необходимо).

NOTE: {project_name} не создает сеанс SSO браузера после успешной аутентификации с помощью протокола Docker. Сессия SSO браузера не использует протокол Docker, так как она не может обновить токены или получить статус токена или сеанса с сервера {project_name} ; поэтому сеанс SSO не является обязательным. Подробнее см. в секции <<_transient-session, transient session>> .

==== {project_name} Distribution registry v2 Authentication Server URI Endpoints

У {project_name} есть одна конечная точка для всех запросов авторизации и v2.

`http(s)://authserver.host{kc_realms_path}/{realm-name}/protocol/docker-v2/auth`