==== Привязки SAML

[role="_abstract"]
{project_name} поддерживает три типа привязки.

===== Привязка перенаправления

_Redirect_ использует для обмена информацией серию URI браузера.

. Пользователь подключается к приложению с помощью браузера. Приложение обнаруживает, что пользователь не аутентифицирован.
. Приложение генерирует XML-документ запроса аутентификации и кодирует его в качестве параметра запроса в URI. URI используется для перенаправления на сервер {project_name}. В зависимости от ваших настроек, приложение также может подписать XML-документ и включить подпись в качестве параметра запроса в редирект URI на {project_name}.  Эта подпись используется для проверки клиента, который отправляет запрос.
. Браузер перенаправляет на {project_name}.
. Сервер извлекает XML-документ запроса авторизации и при необходимости проверяет цифровую подпись.
. Пользователь вводит свои учетные данные.
. После аутентификации сервер генерирует документ с ответом на аутентификацию XML. Документ содержит SAML утверждение, содержащее метаданные о пользователе, включая имя, адрес, адрес электронной почты и любые сопоставления ролей, которыми обладает пользователь.  Этот документ обычно подписывается с использованием XML-подписей и также может быть зашифрован.
. Документ проверки подлинности XML кодируется в качестве параметра запроса в URI перенаправления. URI возвращает браузер обратно в приложение.  Цифровая подпись также включена в параметр запроса.
. Приложение получает редиректный URI и извлекает XML-документ.
. Приложение проверяет подпись реалма, чтобы убедиться, что он получил действительный аутентификационный ответ.  Информация внутри SAML используется для принятия решений о доступе или отображения данных пользователя.

===== Привязка POST

Привязка _POST_ похожа на привязку _Redirect_ но привязка _POST_ обменивается XML-документами с помощью POST запросов вместо использования GET запросов. Для того, чтобы браузер посылал POST запрос на сервер {project_name} или приложение при обмене документами, в привязке _POST_ используется JavaScript. HTTP отвечает HTML-документом, содержащим HTML-форму, содержащую встроенный JavaScript.  При загрузке страницы JavaScript автоматически запускает форму.

Рекомендуется привязать _POST_ к двум ограничениям:

* *Security* -- С _Redirect_ связыванием, SAML ответ является частью URL. Это менее безопасно, так как можно зафиксировать ответ в журналах.
* *Размер* -- Отправка документа в HTTP полезной нагрузке предоставляет больше возможностей для больших объемов данных, чем в ограниченном URL.

===== ЭЦП

Enhanced Client или Proxy (ECP) - это профиль SAML v.2.0, который позволяет обмениваться атрибутами SAML вне контекста веб-браузера. Он часто используется клиентами REST или SOAP.

==== Конечные точки SAML URI сервера {project_name}

У {project_name} есть одна конечная точка для всех запросов SAML.

`http(s)://authserver.host{kc_realms_path}/{realm-name}/protocol/saml`

Все привязки используют эту конечную точку.