=== Подключить OpenID

[role="_abstract"]
link:https://openid.net/developers/how-connect-works/[OpenID Connect] (OIDC) — это протокол аутентификации, который является расширением link:https://datatracker.ietf.org/doc/html/rfc6749[OAuth 2.0].

OAuth 2.0 - это основа для создания протоколов авторизации и неполной. Однако OIDC представляет собой протокол проверки подлинности и авторизации в полном объеме, который использует стандарты link:https://www.jwt.io/[Json Web Token] (JWT).  Стандарты JWT определяют формат JSON и методы цифрового подписи и шифрования данных компактным и удобным в использовании веб-способом.

В целом OIDC реализует два варианта использования. Первый случай - это приложение, требующее аутентификации сервера  {project_name}. После успешной авторизации приложение получает _идентификационный токен_ и _access token_.
Маркер _identity содержит информацию о пользователе, включая имя пользователя, электронную почту и информацию о профиле. Область в цифровом формате подписывает ключ _access token_ содержащий информацию о доступе (например, сопоставления ролей пользователей), которую приложения используют для определения ресурсов, которые пользователи могут получить в приложении.

Второй вариант использования - это клиентский доступ к удаленным сервисам.

* Клиент запрашивает ключ _доступа от {project_name} для вызова удалённых сервисов от имени пользователя.
* {project_name} аутентифицирует пользователя и просит пользователя дать ему разрешение на доступ к запрашивающему клиенту.
* Клиент получает _access token_, который подписывается в цифровом виде.
* Клиент делает REST запросы на удаленных сервисах с помощью ключа _доступа.
* Удаленная служба REST извлекает ключ _доступа.
* Удаленная служба REST проверяет подпись токенов.
* Удаленная служба REST обязуется обрабатывать или отклонять запрос, основываясь на информации доступа в рамках токена.