[id="con-oidc-auth-flows_{context}"]
==== Потоки авторизации OIDC

[role="_abstract"]
OIDC имеет несколько методов или потоков, которые клиенты или приложения могут использовать для аутентификации пользователей и получения фишек _identity_ и _access_tokens. Метод зависит от типа приложения или клиента, запрашивающего доступ.

===== Код авторизации

Код авторизации - это браузерный протокол и подходит для аутентификации и авторизации браузерных приложений. Для получения токенов _identity_ и _access_ используется браузер.

. Пользователь подключается к приложению с помощью браузера. Приложение обнаруживает, что пользователь не вошел в приложение.
. Приложение перенаправляет браузер на {project_name} для аутентификации.
. Приложение передает обратный URL в качестве параметра запроса в браузере перенаправления. {project_name} использует параметр при успешной аутентификации.
. {project_name} аутентифицирует пользователя и создает одноразовый временный код.
. {project_name} перенаправляет на приложение, используя обратный URL и добавляет временный код в качестве параметра запроса в URL обратного вызова.
. Приложение извлекает временный код и делает фоновое обращение REST к {project_name}
для обмена кода на _identity_ и _access_ и _refresh_ токен. Чтобы предотвратить повторную атаку, временный код нельзя использовать более одного раза.

[NOTE]
====
Система уязвима к похищенному токену на время жизни этого токена. По соображениям безопасности и масштабирования токены доступа, как правило, устанавливаются на быстрое прекращение, так что последующие токен-запросы не выполняются. Если срок действия токена истек, приложение может получить новый токен доступа, используя дополнительный токен, отправленный по протоколу входа.
====

[[_confidential-clients]]
Клиенты _Confidential_ предоставляют клиентские секреты при обмене временных кодов на токены. _Публичные_ клиенты не требуются для предоставления клиентских секретов.
_Public_ clients are secure when HTTPS is strictly enforced and redirect URI, registered for the client are strictly controled. Клиенты HTML5/JavaScript должны быть _публичными_ клиентами, так как нет способа надежно передавать клиентскую тайну клиентам HTML5/JavaScript. Подробнее см. в разделе xref:assembly-managing-clients_{context}[Управление клиентами].

{project_name} также поддерживает спецификацию https://datatracker.ietf.org/doc/html/rfc7636[Proof Key for Code Exchange].

===== Неявный поток

Implicit Flow - это протокол, основанный на браузере. Он похож на код авторизации, но с меньшим количеством запросов и токенов обновления.

[NOTE]
====
Возможность утечки токенов в истории браузера, когда токены передаются через редиректные URI (см. ниже).

Кроме того, этот поток не предоставляет клиентам токены обновления. Поэтому токены доступа должны быть долгожительными или пользователи должны повторно авторизоваться по истечении срока их действия.

Мы не рекомендуем использовать этот поток. Этот поток поддерживается, так как он находится в спецификации OIDC и OAuth 2.0.
====

Протокол работает следующим образом:

. Пользователь подключается к приложению с помощью браузера. Приложение обнаруживает, что пользователь не вошел в приложение.
. Приложение перенаправляет браузер на {project_name} для аутентификации.
. Приложение передает обратный URL в качестве параметра запроса в браузере перенаправления. {project_name} использует параметр запроса при успешной аутентификации.
. {project_name} аутентифицирует пользователя и создает _identity_ и _access_ токен. {project_name}
перенаправляет на приложение, используя URL обратного вызова и дополнительно добавляет _identity_ и _access_ токены в качестве параметра запроса в URL обратного вызова.
. Приложение извлекает ключи _identity_ и _access_ из URL обратного вызова.

===== Предоставление паролей владельца ресурсов (грантов прямого доступа)

_Гранты прямого доступа_ используются клиентами REST для получения токенов от имени пользователей. Это HTTP-запрос POST, который содержит:

* Учетные данные пользователя. Учетные данные отправляются в пределах параметров формы.
* Идентификатор клиента.
* Секретный клиент (если он является конфиденциальным клиентом).

Ответ HTTP содержит _identity_, _access_, и _refresh_ маркеры.

[[_client_credentials_grant]]
===== Предоставление учетных данных клиента

_Учетные данные клиента Grant_ создают токен на основе метаданных и разрешений сервисной учетной записи, связанной с клиентом вместо получения токена, который работает от имени внешнего пользователя. _Учетные данные Грантов используются REST клиентами.

Для получения дополнительной информации обратитесь к главе <<_service_accounts,Service Accounts>>.

[[_refresh_token_grant]]
===== Разрешить обновление токена

По умолчанию {project_name} возвращает обновление токенов в ответах на большинство потоков. Некоторые исключения являются неявным потоком или предоставлением учетных данных клиента, описанным выше.

Обновленный токен привязан к сессии пользователя сеанса браузера SSO и может быть действителен в течение всего времени сеанса пользователя. Тем не менее, этот клиент должен отправить запрос refresh-token хотя бы один раз в течение
указанного интервала. В противном случае сеанс может считаться "бездействием" и может закончиться. Смотрите <_timeouts,timeouts section>> для получения дополнительной информации.

{project_name} поддерживает <<_offline-access,offline tokens>>, который может быть использован, как правило, когда клиенту нужно использовать токен обновления, даже если соответствующий сеанс SSO в браузере уже истек.

[[_refresh_token_rotation]]
====== Обновить поворот токена

Можно указать, что токен обновления считается недействительным после его использования. Это означает, что клиент должен всегда сохранять токен обновления из последнего ответа обновления, потому что старые токены обновления,
которые уже были использованы, не будут считаться действительными {project_name}. Это можно установить с помощью опции _Revoke Refresh token_ как указано в <_timeouts,timeouts section>.

{project_name} также поддерживает ситуацию, при которой не существует вращения токена обновления. В этом случае токен обновления возвращается во время входа в систему, но последующие ответы от запросов refresh-token не
возвращают новые токены обновления. Эта практика рекомендуется, например, в разделе *FAPI 2 черновой спецификации* и *FAPI 2 окончательной спецификации* по ссылке:{securing_apps_link}[защита приложений].
В {project_name}можно пропустить поворот токена обновления с использованием <<_client_policies,client policies>>. Вы можете добавить исполнителя `suppress-refresh-token-rotation` к некоторому клиенту
профилю и настроить клиентскую политику, чтобы указать, для каких клиентов запускался профиль, это означает, что для этих клиентов будет пропущен поворот токена обновления.

===== Разрешение на авторизацию устройства

Это используется клиентами, работающими на устройствах, подключенных к Интернету, которые имеют ограниченные возможности ввода или не имеют подходящего браузера. Вот краткое описание протокола:

. The application requests {project_name} a device code and a user code. {project_name} создает код устройства и код пользователя. {project_name} возвращает приложению ответ, включая код устройства и код пользователя.
. Приложение предоставляет пользователю код пользователя и верификационный URI. Пользователь получает доступ к URI проверки подлинности с помощью другого браузера. Вы можете указать короткую проверку подлинности_uri, которая будет перенаправлена на URI проверки {project_name} (/realms/realm_name/device) за пределами {project_name} - например в прокси.
. Приложение неоднократно опрашивает {project_name} , чтобы выяснить, завершил ли пользователь авторизацию. Если аутентификация пользователя завершена, приложение заменяет код устройства для _identity_, _access_ и _refresh_ токена.

[[_client_initiated_backchannel_authentication_grant]]
===== Клиент инициировал бэкканальную аутентификацию

Эта функция используется клиентами, которые хотят инициировать процесс аутентификации путем общения с поставщиком OpenID напрямую без перенаправления через браузер пользователя, например OAuth 2. выдан код авторизации. Вот краткое описание протокола:

. Клиент запрашивает {project_name} auth_req_id, который идентифицирует запрос на аутентификацию, сделанный клиентом. {project_name} создает auth_req_id.
. После получения этого auth_req_id, этому клиенту неоднократно нужно опросить {project_name} для получения токена доступа, Обновите токен и идентификационный токен от {project_name} в обмен на auth_req_id до тех пор, пока пользователь не будет аутентифицирован.

Администратор может настроить связанные с Клиентом Backchannel Authentication операции как «Политику CIBA» в каждом реалме.

Также обратитесь к другим местам документации {project_name} , таким как *Backchannel Authentication Endpoint* и *Backchannel Authentication Grant* по ссылке:{securing_apps_link}[защита приложений].

====== Политика CIBA

Администратор осуществляет следующие операции в `Admin Console` :

- Откройте вкладку `Authentication -> CIBA Policy`.
- Настройте элементы и нажмите «Сохранить».

Элементы, настраиваемые и их описание, следуют.

|===
|Конфигурация |Описание

|Способ доставки токенов канала
|Укажите, как CD (Consumption Device) получает результат аутентификации и соответствующие токены. Существует три режима: "опрос", "пинг" и "push". {project_name} поддерживает только "опрос". Значение по умолчанию: "poll". Эта конфигурация обязательна.
 Подробнее см. https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html#rfc.section.5[CIBA Specification].

|Истекает через
|Время истечения "auth_req_id" в секундах с момента получения запроса аутентификации. Значение по умолчанию: 120. Эта конфигурация обязательна.
 Подробнее см. https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html#successful_authentication_request_acknowdlegment[CIBA Specification].

|Интервал
|Интервал в секундах, в секундах CD (Consumption Device) должен подождать между запросами на опрос до конечной точки токена. Значение по умолчанию: 5. Эта конфигурация необязательна.
 Подробнее см. https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html#successful_authentication_request_acknowdlegment[CIBA Specification].

|Подсказка к запросу аутентификации
|Способ идентификации конечного пользователя, для которого запрашивается аутентификация. По умолчанию: "login_hint". Существуют три режима: "login_hint", "login_hint_token" и "id_token_hint". {project_name} поддерживает только "login_hint". Эта конфигурация обязательна.
 Подробнее см. https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html#rfc.section.7.1[CIBA Specification].
|===

====== Настройки провайдера

В гранте CIBA используются следующие два провайдера.

. Провайдер каналов аутентификации: обеспечивает связь между {project_name} и сущностью, которая фактически аутентифицирует пользователя через AD (устройство аутентификации).
. Поставщик пользовательского решения: получите `UserModel` из {project_name} от информации, предоставленной клиентом для идентификации пользователя.

У {project_name} есть оба поставщика по умолчанию. Однако администратору необходимо настроить канал аутентификации следующим образом:

[source,bash,subs="attributes+"]
----
kc.[sh|bat] start --spi-ciba-auth-channel--ciba-http-auth-channel--http-authentication-channel-uri=https://backend.internal.example.com{kc_base_path}
----

Элементы, настраиваемые и их описание, следуют.

|===
|Конфигурация |Описание

|http-authentication-channel-uri
|Указанный URI сущности, которая фактически аутентифицирует пользователя через AD (устройство аутентификации).
|===

====== Поставщик канала аутентификации

В стандартном документе CIBA не указывается, как аутентифицировать пользователя AD. Поэтому он может быть реализован по усмотрению товаров. {project_name} делегатов эта аутентификация внешнему элементу аутентификации. Для связи с субъектом аутентификации, {project_name} предоставляет поставщика каналов аутентификации.

Его реализация {project_name} предполагает, что сущность аутентификации находится под контролем администратора {project_name} , чтобы {project_name} доверял сущности аутентификации. Не рекомендуется использовать элемент аутентификации, который администратор {project_name} не может контролировать.

Поставщик каналов аутентификации предоставляется как поставщик SPI, чтобы пользователи {project_name} могли реализовать своего провайдера для удовлетворения своих окружений. {project_name} предоставляет своего провайдера по умолчанию под названием HTTP Authentication Channel Provider, который использует HTTP для связи с сущностью аутентификации.

If a user of {project_name} wants to use the HTTP Authentication Channel Provider, they need to know its contract between {project_name} and the authentication entity consisting of the following two parts.

Запрос/Ответ делегата аутентификации:: {project_name} отправляет запрос на аутентификацию сущности аутентификации.
Результаты проверки подлинности уведомления/ACK:: Аутентификационная сущность уведомляет о результатах аутентификации {project_name}.

Запрос/Ответ делегата аутентификации состоит из следующих сообщений.

Запрос на делегирование аутентификации:: Запрос отправлен от {project_name} сущности аутентификации для запроса аутентификации пользователя от AD.

----
POST [delegation_reception]
----

* Заголовки

|===
|Наименование |Значение |Описание

|Тип содержимого |приложение/json |Тело сообщения отформатировано.

|Авторизация |носитель [token] |[token] используется, когда сущность аутентификации уведомляет о результатах аутентификации {project_name}.
|===

* Параметры

|===
|Тип |Наименование |Описание

|Путь
|прием делегации_делегации |Конечный пункт, предоставленный субъектом проверки подлинности для получения запроса делегирования
|===

* Тело

|===
|Наименование |Описание

|подсказка для входа |Он рассказывает сущность аутентификации, которая аутентифицирована AD. +
По умолчанию, это "имя пользователя". +
Это поле является обязательным и определено стандартным документом CIBA.

|объем |Он указывает, какие области аутентификации сущность получает согласие авторизованного пользователя. +
Это поле является обязательным и определено стандартным документом CIBA.

|не требуется |Она показывает, должна ли сущность аутентификации получить от авторизованного пользователя согласие на область. +
 Это поле является обязательным.

|привязка сообщения |Его значение предназначено для отображения как на компакт-диске, так и в интерфейсе AD, с тем чтобы пользователь осознал, что аутентификация по AD вызывается на CD. +
Это поле является необязательным и определено стандартным документом CIBA.

|acr_values |Он показывает запрошенную аутентификацию контекстного класса справочника с CD. +
Это поле является необязательным и определено стандартным документом CIBA.
|===

Ответ делегации аутентификации:: Ответ возвращается от сущности аутентификации {project_name} , чтобы уведомить, что сущность аутентификации получила запрос аутентификации от {project_name}.
* Ответы

|===
|Код состояния HTTP |Описание

|201 |Оно уведомляет {project_name} о получении запроса на делегирование аутентификации.
|===

Уведомление о результатах аутентификации/ACK состоит из следующих сообщений.

Уведомление о результатах аутентификации:: Аутентификационная сущность посылает результат запроса аутентификации {project_name}.

[source,subs=+attributes]
----
POST {kc_realms_path}/[realm]/protocol/openid-connect/ext/ciba/auth/callback
----

* Заголовки

|===
|Наименование |Значение |Описание

|Тип содержимого |приложение/json |Тело сообщения отформатировано.

|Авторизация |носитель [token] |The [token] must be the one the authentication entity has received from {project_name} in Authentication Delegation Request.
|===

* Параметры

|===
|Тип |Наименование |Описание

|Путь
|Область |Название области
|===

* Тело

|===
|Наименование |Описание

|статус |Он показывает результат аутентификации пользователей AD. +
Это должен быть один из следующих статусов. +
  SUCCEED : Аутентификация по AD была успешно завершена. +
  НЕАВТОРИЗАЦИЯ: Аутентификация по AD не была завершена. +
  ОТМЕНА : Аутентификация по AD была отменена пользователем.
|===

Результат аутентификации ACK:: Ответ от {project_name} возвращается сущности аутентификации для уведомления {project_name} в результате аутентификации пользователя от элемента аутентификации.
* Ответы

|===
|Код состояния HTTP |Описание

|200 |Он уведомляет сущность аутентификации о получении уведомления о результатах аутентификации.
|===

====== Поставщик резолвера пользователей

Даже если один и тот же пользователь, его представление может отличаться на каждом CD, {project_name} и сущности аутентификации.

Для CD, {project_name} и аутентификации сущности, чтобы распознать одного и того же пользователя, этот поставщик резольвера преобразует среди них свои собственные представления пользователей.

User Resolver Provider предоставляется как SPI провайдер для того, чтобы пользователи {project_name} могли реализовать своего провайдера в соответствии со своим окружением. {project_name} предоставляет своего поставщика по умолчанию под названием Default User Resolver Provider, который имеет следующие характеристики.

* Поддерживается только параметр `login_hint` и используется по умолчанию.
* `username` UserModel {project_name} используется для представления пользователя на CD, {project_name} и аутентификации сущности.

==== OIDC выход

УИРК располагает четырьмя спецификациями, касающимися механизмов выхода:

. https://openid.net/specs/openid-connect-session-1_0.html[Управление сессиями]
. https://openid.net/specs/openid-connect-rpinitiated-1_0.html[Выход, инициативный]
. https://openid.net/specs/openid-connect-frontchannel-1_0.html[Front-Channel Logout]
. https://openid.net/specs/openid-connect-backchannel-1_0.html[Back-Channel Logout]

Снова так как все это описано в OIDC спецификации, мы лишь дадим краткий обзор здесь.

[[_oidc-logout-session-management]]
===== Управление сессиями

Это браузерный выход из системы. Приложение регулярно получает информацию о состоянии сеанса от {project_name}.
Когда сеанс завершится на {project_name} , приложение заметит и запустит собственный выход из системы.

Это особенно полезно для браузерных приложений, например, когда приложение защищено по ссылке:{securing_apps_javascript_adapter_link}[{securing_apps_javascript_adapter_name}]
В результате, выход из одной вкладки браузера может вызвать автоматический выход из всех вкладок браузера с приложениями, защищенными адаптером javascript.

[[]]
===== Выход из RP

Это также браузерный выход, в котором начинается выход с перенаправления пользователя на конкретную конечную точку {project_name}.
Это перенаправление обычно происходит, когда пользователь нажимает ссылку «Выйти из системы» на странице некоторых приложений, который ранее использовал {project_name} для аутентификации пользователя.

Once the user is redirected to the logout endpoint, {project_name} is going to send logout requests to
clients attached to the current browser SSO session to let them invalidate their local user sessions, and potentially redirect the user to some URL
once the logout process is finished. Пользователю может быть предложено подтвердить выход в системе, если параметр `id_token_hint` не используется.
Если в клиенте включено подтверждение выхода xref:_logout-confirmation[Logout confirmation], то {project_name} переводит страницу подтверждения после успешного выхода из системы, информируя пользователя о том, что он вышёл из системы. Если указана допустимая опция `post_logout_redirect_uri`, эта страница содержит опцию для перехода на этот URL.
После выхода пользователь автоматически перенаправляется на указанный `post_logout_redirect_uri` при условии, что он указан в качестве параметра.
Обратите внимание, что при включении параметра `post_logout_redirect_uri` необходимо включить параметр `client_id_token_hint`. Также параметр `post_logout_redirect_uri`
должен соответствовать одному из указанных в конфигурации клиента `Valid Post Logout Redirect URIs`.

В зависимости от конфигурации клиента, запросы на выход могут быть отправлены клиентам через фронт-канал или через бэк-канал. Для клиентов браузера интерфейса, которые полагаются на
Управление сессиями, описанное в предыдущем разделе, {project_name} не нужно отправлять им запросы о выходе из системы; эти клиенты автоматически обнаруживают, что SSO сеанс
в браузере выходит из системы.

===== Выход из фронт-канала

Чтобы настроить получение запросов на выход через фронт-канал, посмотрите на <<_front-channel-logout, Front-Channel Logout>>. При использовании этого метода рассмотрим следующее:

* Запросы на выход из системы, отправленные {project_name} клиентам полагаются на браузер и встроенные `iframes`, которые отображаются для страницы выхода из системы.
* На том основании, что `iframes` выход на фронт-канал может повлиять политика безопасности контента (CSP) и запросы на выход из системы могут быть заблокированы.
* Если пользователь закрывает браузер перед отображением страницы выхода или перед выходом из системы фактически отправляются клиентам, их сеансы на
может не быть аннулированы.

[NOTE]
====
Рассмотрим возможность использования бэк-канала, поскольку он обеспечивает более надежный и безопасный подход к выходу пользователей и прекращает сеансы
на клиентах.
====

Если клиент не включен с выходом на фронт-канал, затем {project_name} попытается сначала отправить запросы выхода через бэк-канал
с использованием <<_back-channel-logout-url, Back-Channel Logout URL>>. Если не определено, сервер собирается вернуться к использованию <_admin-url, Admin URL>>.

Если даже адрес администратора не указан, {project_name} не будет распространять его на клиент. Это действие может быть по-прежнему достаточно для многих клиентских приложений. For
instance, when the client application is a frontend javascript application, it may rely on the <<_oidc-logout-session-management, Session Management>> and hence no need exists to send
a dedicated logout request to the client application. Другие клиентские приложения могут полагаться только на короткий <_timeouts,timeout>>. Это означает, что сеанс приложения
остается в силе в течение короткого времени после выхода SSO сеанса {project_name}. Однако, когда клиентское приложение пытается обновить маркер доступа, запрос обновления токена на {project_name}
не будет выполнен, так как сеанс SSO {project_name} уже вышёл.

===== Выход из бэк-канала

Это небраузерный выход из системы, который использует прямую связь между {project_name} и клиентами.
{project_name} посылает HTTP POST запрос, содержащий токен выхода для всех клиентов, вошедших в {project_name}. Эти
запросы отправляются по зарегистрированным URL-адресам выхода из пропусков на {project_name} и должны срабатывать выход на клиентской стороне.

Когда клиентское приложение поддерживает выход из бэкканала, что выход из системы, как правило, лучше, чем выход на фронт-канал, поскольку связь происходит непосредственно между клиентом и {project_name} без участия веб-браузера
, что обычно является более надежным. Also, when the {project_name} logout of specified user is triggered by the administrator from the <<viewing-user-sessions,Admin console>> (or other use of admin REST API)
or by the actual user from <<_account-service,the Account console>>, then {project_name} can propagate a backchannel logout request to the client applications attached to the session being
logged out. Этот сценарий не поддерживается в случае выхода на фронт-канал, так как {project_name} может распространять его через фронт-канал только тогда, когда выход срабатывает в том же браузере
сессии, который выходит из системы. Это не случается, например, когда сеанс конкретного пользователя выполнен администратором из консоли администратора.