=== SAML

[role="_abstract"]
link:https://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0.html[SAML 2.0] является аналогичной спецификации OIDC, но более зрелой.  Он исходит из спецификаций SOAP и веб-сервисов и обычно более подробно, чем OIDC.  SAML 2.0 — это протокол аутентификации, который обменивается XML-документами между серверами аутентификации и приложениями.  XML-подписи и шифрование используются для проверки запросов и ответов.

В общем, SAML реализует два варианта использования.

Первый вариант использования - это приложение, запрашивающее {project_name} сервер аутентифицирует пользователя.  После успешной авторизации приложение получит XML-документ. Этот документ содержит утверждение SAML, указывающее атрибуты пользователя. Область подписывает документ, содержащий информацию о доступе (например, сопоставления ролей пользователей), которую приложения используют для определения доступа пользователей к ресурсам.

Второй вариант использования - это клиентский доступ к удаленным сервисам.  Клиент запрашивает SAML утверждение от {project_name} для вызова удаленных сервисов от имени пользователя.