=== Собираемый доступ и обновление токенов

{project_name} включает в себя несколько действий по предотвращению кражи токенов доступа и токенов обновления. Решающее действие - обеспечение коммуникации SSL/HTTPS между {project_name} и его клиентами и приложениями. {project_name} не поддерживает SSL по умолчанию.

Еще одной мерой по снижению ущерба от утечки токенов доступа является сокращение продолжительности жизни токенов. Вы можете указать продолжительность жизни токена в <_timeouts, timeouts page>>. Краткие условия жизни токенов доступа заставляют клиентов и приложения обновлять токены доступа через короткое время. Если администратор обнаруживает утечку, администратор может вывести все сеансы пользователя, чтобы аннулировать эти токены или установить политику отзыва.

Убедитесь, что токены обновления всегда остаются конфиденциальными клиенту и никогда не передаваются.

Вы можете уменьшить повреждение токенов доступа и обновить токены, выдав эти токены в качестве держателя ключей. Смотрите <<_mtls-client-certificate-bound-tokens, OAuth 2.0 Mutual TLS Client Certificate Bound Access Token>> для получения дополнительной информации.

Если токен доступа или токен обновления скомпрометирован, зайдите в консоль администратора и пропустите политику отзыва для всех приложений. Отправка необязательной политики гарантирует, что все токены, выпущенные до этого времени, станут недействительными.
Отправка новой политики не является гарантией того, что приложения должны загружать новые открытые ключи из {project_name} и уменьшить ущерб от взломанного ключа подписи реалма. Смотрите <<realm_keys, keys chapter>> для получения дополнительной информации.

Вы можете отключить конкретные приложения, клиентов или пользователей, если они скомпрометированы.