=== Атаки CSRF

Подделка межсайтовых запросов (CSRF) использует HTTP-запросы пользователей, которые уже аутентифицированы. Любой сайт, использующий аутентификацию на основе cookie, уязвим для атак CSRF. Вы можете смягчить эти атаки, сопоставляя файлы cookie состояния с размещенной формой или параметром запроса.

Спецификация входа в OAuth 2.0 требует, чтобы cookie состояния совпадали с параметром передаваемого состояния. {project_name} полностью реализует эту часть спецификации, так что все логины защищены.

Консоль администратора {project_name} - это JavaScript/HTML5 приложение, которое делает REST звонки к бэкэнду {project_name} администратора REST API. Все эти вызовы требуют аутентификации токена предъявителя и состоят из вызовов JavaScript Ajax, поэтому CSRF невозможен. Вы можете настроить API администратора REST для проверки CORS оригиналов.

Консоль аккаунта в {project_name} может быть уязвима для CSRF. Для предотвращения атак CSRF, {project_name} устанавливает cookie состояния и встраивает значение этого cookie в поля скрытой формы или параметры запроса в ссылках действия. {project_name} проверяет параметр запроса/формы на соответствие cookie состояния, чтобы убедиться, что тот же пользователь совершил вызов.