=== Открытые редиректы

Открытый редиректор - это конечная точка, использующая параметр для автоматического перенаправления пользовательского агента на место, указанное значением параметра без проверки. Нападающий может использовать конечную точку авторизации конечную точку авторизации конечную и параметр URI перенаправления для использования сервера авторизации в качестве открытого редиректа, использование доверия пользователя к серверу авторизации для запуска фишинговой атаки.

{project_name} требует, чтобы все зарегистрированные приложения и клиенты регистрировали по крайней мере один шаблон перенаправления URI. Когда клиент просит {project_name} выполнить переадресацию, {project_name} проверяет редирект URI на соответствие списку зарегистрированных шаблонов URI. Клиенты и приложения должны зарегистрировать как можно более конкретный шаблон URI для предотвращения открытых атак редиректа.

Если приложение требует пользовательскую схему не http(s), она должна быть явной частью шаблона проверки (например, `custom:/app/\*`). По соображениям безопасности общий шаблон типа `*` не охватывает схемы не http(s).

Используя <<_client_policy, Client Policies>, администратор может убедиться, что клиенты не могут зарегистрировать открытые URL перенаправления, такие как `*`.