[[read_only_user_attributes]]
=== Атрибуты пользователей только для чтения

Типичные пользователи, хранящиеся в {project_name} , имеют различные атрибуты, связанные с их профилями пользователей. Такие атрибуты включают email, firstName или lastName.
Однако пользователи могут также иметь атрибуты, которые не являются типичными профильными данными, а скорее метаданными. Атрибуты метаданных, как правило, должны быть доступными только для чтения для пользователей
и типичные пользователи никогда не должны иметь возможность обновить эти атрибуты из пользовательского интерфейса {project_name} или аккаунта REST API. Some of the attributes should
be even read-only for the administrators when creating or updating user with the Admin REST API.

Метаданные атрибутов, как правило, являются атрибутами этих групп:

* Различные ссылки или метаданные, относящиеся к поставщикам хранения пользователей. Например, в случае интеграции LDAP атрибут `LDAP_ID` содержит
ID пользователя на сервере LDAP.
* Метаданные, предоставленные хранилищем пользователя. Например, `createdTimestamp` снабжен LDAP всегда должен быть доступен только для чтения пользователем или администратором.
* Метаданные, связанные с различными аутентификаторами. Например, атрибут `KERBEROS_PRINCIPAL` может содержать основное имя ядра конкретного пользователя. Аналогичный атрибут
`usercertificate` может содержать метаданные, связанные с привязкой пользователя к данным из X. 09 сертификат, который обычно используется при включенной аутентификации сертификата X.509.
* Метаданные, связанные с идентификатором пользователей приложениями/клиентами. For example `saml.persistent.name.id.for.my_app` can contain SAML NameID, which will
be used by the client application `my_app` as the identifier of the user.
* Метаданные, относящиеся к политикам авторизации, которые используются для контроля доступа на основе атрибута (АБАК). Values of those attributes may be used for the
authorization decisions. Поэтому важно, чтобы эти атрибуты не были обновлены пользователями.

С точки зрения долгосрочной перспективы, {project_name} будет иметь надлежащий SPI пользовательского профиля, который позволит точную конфигурацию каждого атрибута пользователя. Currently
this capability is not fully available yet. Таким образом, {project_name} имеет внутренний список пользовательских атрибутов, которые только для чтения для пользователей и только для чтения для администраторов настроены
на уровне сервера.

Это список атрибутов, доступных только для чтения, которые используются внутренними поставщиками по умолчанию {project_name} , и поэтому всегда доступны только для чтения:

* Пользователям: `KERBEROS_PRINCIPAL`, `LDAP_ID`, `LDAP_ENTRY_DN`, `CREATED_TIMESTAMP`, `createTimestamp`, `modifyTimestamp`, `userCertificate`, `saml.persistent.name.id.for.*`, `ENABLED`, `EMAIL_VERIFIED`
* Для администраторов: `KERBEROS_PRINCIPAL`, `LDAP_ID`, `LDAP_ENTRY_DN`, `CREATED_TIMESTAMP`, `createTimestamp`, `modifyTimestamp`

Системные администраторы имеют возможность добавить дополнительные атрибуты в этот список. В настоящее время конфигурация доступна на уровне сервера.

Вы можете добавить эту конфигурацию, используя опции `spi-user-profile--declarative-user-profile--read-only-attributes` и `spi-user-profile--declarative-user-profile--admin-read-only-attributes`. Например:

[source,bash,options="nowrap"]
----
kc.[sh|bat] start --spi-user-profile--declarative-user-profile--read-only-attributes=foo,bar*
----

В этом примере пользователи и администраторы не смогут обновить атрибут `foo`. Пользователи не смогут редактировать любые атрибуты, начиная с `bar`.
Итак, например, «бар» или «барьер». Конфигурация не чувствительна к регистру, поэтому атрибутам, например `FOO` или `BarRier` также будет отказано. Символ `\*` поддерживается
только в конце имени атрибута. , чтобы администратор мог эффективно запретить все атрибуты, начиная с указанного символа. '*' в середине атрибута считается
нормальным символом.