=== Ограничение области

==== Доступность рамок

По умолчанию новые клиентские приложения имеют неограниченные `роль`. Каждый токен доступа для этого клиента содержит все разрешения, которые имеет пользователь. Если злоумышленник ставит под угрозу клиента и получает токены доступа клиента, каждая система, к которой пользователь может получить доступ, скомпрометирована.

Ограничить роли токена доступа с помощью <_role_scope_mappings, Scope menu>> для каждого клиента. Кроме того, вы можете установить сопоставления рамок ролей на уровне Клиента и назначить клиентские области для вашего клиента, используя <<_client_scopes_linking, Меню рамок клиентов>>.

Удаление автономной области действия для клиента также устраняет возможность выпуска давно существующих автономных токенов для клиента и обеспечивает лучший контроль над сессиями со стороны пользователей.

==== Видимость рамок

По умолчанию, все области включены в конечную точку обнаружения OpenID Connect.
Чтобы уменьшить возможность обнаружения и воздействия OSINT, вы можете настроить каждую область для исключения, отключив *Включение в метаданные OpenID провайдера*.