=== Требование SSL/HTTPS

OAuth 2.0/OpenID Connect использует токены доступа для безопасности. Атакующие могут сканировать вашу сеть для токены доступа и использовать их для выполнения вредоносных операций, для которых токен имеет разрешение. Эта атака известна как атаки человека в середине тела. Используйте SSL/HTTPS для связи между сервером авторизации {project_name} и клиентами {project_name} для предотвращения атаки человека в центре города.

У {project_name} <<_ssl_modes,три режима для SSL/HTTPS>>. SSL сложно установить, так что {project_name} позволяет общаться по закрытым IP адресам, таким как localhost, 192.168.x.x и другие частные IP-адреса. В производстве, убедитесь, что SSL и SSL являются обязательными для всех операций.

На адаптере/клиентской стороне вы можете отключить менеджер доверия SSL. Менеджер доверия удостоверяет личность клиента, с которым {project_name} связывается, и гарантирует, что DNS доменное имя соответствует сертификату сервера. Производство, убедитесь, что каждый из ваших адаптеров использует надежный магазин, чтобы предотвратить атаки DNS человека в середине.