== Админ CLI

С помощью {project_name}вы можете выполнять задачи администрирования из интерфейса командной строки (CLI), используя инструмент CLI командной строки.

=== Установка администратора CLI

{project_name} поставляет дистрибутив сервера Admin CLI с сценариями выполнения в директории `bin`.

Скрипт Linux называется `kcadm.sh`, а сценарий для Windows называется `kcadm.bat`. Добавьте каталог сервера {project_name} в ваш `PATH` чтобы использовать клиент из любой точки в вашей файловой системе.

Например:

* Linux:
+
[options="nowrap"]
----
$ export PATH=$PATH:$KEYCLOAK_HOME/bin
$ kcadm.sh
----
* Окна:
+
[options="nowrap"]
----
c:\> set PATH=%PATH%;%KEYCLOAK_HOME%\bin
c:\> kcadm
----

[NOTE]
====
Вы должны установить переменную окружения `KEYCLOAK_HOME` на путь, в котором вы распаковали дистрибутив {project_name} Server.

Во избежание повторов, остальная часть этого документа использует только примеры Windows в тех местах, где отличия в CLI больше, чем просто в имени команды `kcadm`.
====

=== Использование администратора CLI

Администратор CLI делает HTTP-запросы к конечным точкам REST. Доступ к конечным точкам администратора REST требует аутентификации.

[NOTE]
====
Обратитесь к документации администратора REST API для получения подробной информации о атрибутах JSON для конкретных конечных точек.
====

. Запустите авторизованный сеанс авторизацией. Теперь вы можете выполнять операции создания, чтения, обновления и удаления (CRUD).
+
Например:
* Linux:
+
[options="nowrap",subs="attributes+"]
----
$ kcadm.sh config credentials --server http://localhost:8080{kc_base_path} --realm demo --user admin --client admin
$ kcadm.sh create realms -s realm=demorealm -s enabled=true -o
$ CID=$(kcadm.sh create clients -r demorealm -s clientId=my_client -s 'redirectUris=["http://localhost:8980/myapp/*"]' -i)
$ kcadm.sh get clients/$CID/installation/providers/keycloak-oidc-keycloak-json
----
* Окна:
+
[options="nowrap",subs="attributes+"]
----
c:\> kcadm config credentials --server http://localhost:8080{kc_base_path} --realm demo --user admin --client admin
c:\> kcadm create realms -s realm=demorealm -s enabled=true -o
c:\> kcadm create clients -r demorealm -s clientId=my_client -s "redirectUris=[\"http://localhost:8980/myapp/*\"]" -i > clientid.txt
c:\> set /p CID=<clientid.txt
c:\> kcadm get clients/%CID%/installation/providers/keycloak-oidc-keycloak-json
----
. В производственном окружении доступ к {project_name} , используя `https:`, чтобы избежать экспозиции токенов. Если доверенный центр сертификации, входящий в хранилище доверенных сертификатов Java, не выдал сертификат сервера, подготовить `truststore. ks` файл и инструкция администратора CLI использовать его.
+
Например:
* Linux:
+
[options="nowrap"]
----
$ kcadm.sh config truststore --trustpass $PASSWORD ~/.keycloak/truststore.jks
----
* Окна:
+
[options="nowrap"]
----
c:\> kcadm config truststore --trustpass %PASSWORD% %HOMEPATH%\.keycloak\truststore.jks
----

=== Варианты чувствительности

Чувствительные значения, такие как пароли, могут быть указаны как параметры команды. Это, как правило, не рекомендуется. Существуют также механизмы, с помощью которых вы можете получить чувствительное значение, пропустив параметр или предоставив значение. Наконец, все будут иметь соответствующую переменную env, которая может быть использована вместо этого. Проверьте справку команды, которую вы выполняете, чтобы увидеть все возможные параметры.

=== Аутентификация

Когда вы войдете с помощью Admin CLI, вы указываете:

* Адрес конечной точки сервера
* Область
* Имя пользователя

Другая опция — указать только clientId, который создает уникальную учетную запись службы для вас.

При входе с использованием имени пользователя, используйте пароль для указанного пользователя. При входе в систему с помощью ID клиента Вам нужен только секретный клиент, а не пароль пользователя. Вы также можете использовать `Signed JWT`, а не клиентскую тайну.

Убедитесь, что используемая для сессии учетная запись имеет соответствующие разрешения на вызов операций администратора REST API. Например, `realm-admin` клиент `realm-management` может администрировать область пользователя.

Для проверки подлинности имеются два основных механизма. Для запуска сеанса аутентификации используется `kcadm config credentials`.

[options="nowrap",subs="attributes+"]
----
$ kcadm.sh config credentials --server http://localhost:8080{kc_base_path} --realm master --user admin
----

Этот механизм сохраняет сеанс между вызовами команды «kcadm», сохраняя полученный токен доступа и связанный с ним токен обновления. Он может сохранять другие секреты в приватном файле конфигурации. Смотрите <<_working_with_alternative_configurations, следующую главу>> для получения дополнительной информации.

Второй механизм аутентифицирует каждую команду на время вызова. Этот механизм увеличивает нагрузку на сервер и время, затраченное на круглые поездки получения токенов. Преимущество этого подхода заключается в том, что нет необходимости сохранять токены между вызовами, поэтому ничего не сохраняется на диск. {project_name} использует этот режим, когда указан аргумент `--no-config`.

Например, при выполнении операции укажите всю информацию, необходимую для аутентификации.

[options="nowrap",subs="attributes+"]
----
$ kcadm.sh get realms --no-config --server http://localhost:8080{kc_base_path} --realm master --user admin
----

Запустите команду `kcadm.sh help` для получения дополнительной информации об использовании Admin CLI.

Запустите `kcadm.sh config credentials --help` для получения дополнительной информации о запуске аутентифицированного сеанса.

Если вы не указали опцию --password (обычно рекомендуется не предоставлять пароли в качестве части команды), вам будет предложено ввести пароль, если не указано значение переменной окружения KC_CLI_PASSWORD.

[[_working_with_alternative_configurations]]
=== Работа с альтернативными конфигурациями

По умолчанию Администратор CLI поддерживает конфигурационный файл `kcadm.config`. {project_name} помещает этот файл в домашний каталог пользователя.
В системах основанных на Linux полный путь: `$HOME/.keycloak/kcadm.config`.
В Windows полный путь: `%HOMEPATH%\.keycloak\kcadm.config`.

Вы можете использовать параметр `--config`, чтобы указать на другой файл или местоположение, так что вы можете поддерживать несколько заверенных сессий параллельно.

[NOTE]
====
Выполнение операций, связанных с одним файлом конфигурации из одного потока.
====

Убедитесь, что конфигурационный файл недоступен другим пользователям системы. Он содержит токены доступа и секреты, которые должны быть частными. {project_name} создает каталог `~/.keycloak` и его содержимое автоматически с надлежащими ограничениями доступа. Если директория уже существует, {project_name} не обновляет права доступа.

Можно не хранить секреты внутри конфигурационного файла, но это неудобно и увеличивает количество запросов к токену. Используйте опцию `--no-config` со всеми командами и укажите информацию аутентификации, которую требует команда `config credentials` с каждым вызовом `kcadm`.

=== Основные операции и URI ресурсов

Администратор CLI может выполнять CRUD операции против конечных точек API Admin REST с дополнительными командами, которые упрощают определенные задачи.

Основной шаблон использования указан здесь:

[options="nowrap"]
----
$ kcadm.sh create ENDPOINT [ARGUMENTS]
$ kcadm.sh get ENDPOINT [ARGUMENTS]
$ kcadm.sh update ENDPOINT [ARGUMENTS]
$ kcadm.sh delete ENDPOINT [ARGUMENTS]
----

Команды `create`, `get`, `update` и `delete` соответствуют HTTP глаголам `POST`, `GET`, `PUT` и `DELETE`, соответственно.
ENDPOINT является URI целевого ресурса и может быть абсолютным (начиная с `http:` или `https:`) или относительным, что {project_name} использует для создания абсолютных URL-адресов в следующем формате:

[options="nowrap"]
----
SERVER_URI/admin/realms/REALM/ENDPOINT
----

Например, если вы аутентифицируетесь с сервером http://localhost:8080{kc_base_path} и область `master`, используя `users` как ENDPOINT создаёт URL-адрес ресурса http://localhost:8080{kc_admins_path}/realms/master/users.

Если вы установили ENDPOINT в `clients`, эффективный URI ресурса это http://localhost:8080{kc_admins_path}/realms/master/clients.

У {project_name} есть конечная точка `realms`, которая является контейнером миров. Она преисполнена:

[options="nowrap"]
----
SERVER_URI/admin/realms
----

У {project_name} есть конечная точка `serverinfo`. Эта конечная точка не зависит от игровых миров.

При аутентификации в качестве пользователя с полномочиями администратора вам может потребоваться выполнение команд в нескольких мирах. Если это так, укажите параметр `-r` для указания CLI какому реализму будет выполняться явно. Вместо того, чтобы использовать `REALM`, как указано в параметре `--realm` с параметром `kcadm.sh configals`, команда использует `TARGET_REALM`.

[options="nowrap"]
----
SERVER_URI/admin/realms/TARGET_REALM/ENDPOINT
----

Например:

[options="nowrap",subs="attributes+"]
----
$ kcadm.sh config credentials --server http://localhost:8080{kc_base_path} --realm master --user admin
$ kcadm.sh create users -s username=testuser -s enabled=true -r demorealm
----

В этом примере вы запускаете сеанс, аутентифицированный как пользователь `admin` в сфере `master`. Затем вы выполните POST вызов с URL-адресом ресурса `http://localhost:8080{kc_admins_path}/realms/demorealm/users`.

Команды `create` и `update` отправляют тело JSON на сервер. Вы можете использовать `-f FILENAME` для чтения готового документа из файла. Когда вы можете использовать опцию `-f -`, {project_name} читает текст сообщения из стандартного ввода. Вы можете указать отдельные атрибуты и их значения, как показано в примере «создать пользователей». {project_name} записывает атрибуты в JSON тело и отправляет их на сервер.

[NOTE]
====
Значение в парах name=value, используемых в опциях --set, -s, считается JSON. Если он не может быть обработан как JSON, то он будет отправлен на сервер в виде текстового значения.

Если значение заключено в кавычки после обработки оболочки, но не является допустимым JSON, котировки будут удалены и остальные значения будут отправлены в виде текста. Это поведение является устаревшим, пожалуйста, укажите ваше значение без кавычек или допустимую строку JSON с двойными кавычками.
====

В {project_name} доступно несколько методов для обновления ресурса с помощью команды `update`. Вы можете определить текущее состояние ресурса и сохранить его в файл, отредактируйте этот файл и отправьте его на сервер для обновления.

Например:

[options="nowraps"]
----
$ kcadm.sh get realms/demorealm > demorealm.json
$ vi demorealm.json
$ kcadm.sh update realms/demorealm -f demorealm.json
----

Этот метод обновляет ресурс на сервере с атрибутами отправленного JSON документа.

Другой метод — выполнить обновление на лету с помощью опций `-s, --set`, чтобы установить новые значения.

Например:

[options="nowraps"]
----
$ kcadm.sh update realms/demorealm -s enabled=false
----

Этот метод устанавливает атрибут «включено» в «false».

По умолчанию команда `update` выполняет `get` и объединяет новые значения атрибута с существующими значениями. В некоторых случаях конечная точка может поддерживать команду `put`, но не команду `get`. Вы можете использовать параметр `-n` для выполнения обновления no-merge, которое выполняет команду `put` без первого запуска команды `get`.

=== Операции Realm

[discrete]
==== Создание новой области

Используйте команду `create` на конечной точке `realms`, чтобы создать новый включенный реалм. Установите атрибуты на «реалм» и «включено».

[options="nowrap"]
----
$ kcadm.sh create realms -s realm=demorealm -s enabled=true
----

{project_name} отключает миры по умолчанию. Вы можете использовать Realm немедленно для аутентификации, включив его.

Описание для нового объекта может быть также в формате JSON.

[options="nowrap"]
----
$ kcadm.sh create realms -f demorealm.json
----

Вы можете отправить JSON документ с атрибутами Realm непосредственно из файла или по каналу документа на стандартный вход.

Например:

* Linux:
+
[options="nowrap"]
----
$ kcadm.sh create realms -f - << EOF
{ "realm": "demorealm", "enabled": true }
EOF
----
* Окна:
+
[options="nowrap"]
----
c:\> echo { "realm": "demorealm", "enabled": true } | kcadm create realms -f -
----

[discrete]
==== Список существующих областей

Эта команда возвращает список всех миров.

[options="nowrap"]
----
$ kcadm.sh get realms
----

[NOTE]
====
{project_name} фильтрует список миров на сервере, чтобы вернуть только пользователь.
====

Список всех атрибутов области может быть подробным, и большинство пользователей заинтересованы в подмножестве атрибутов, такие как имя области и доступный статус области Вы можете указать атрибуты, возвращаемые с помощью параметра `--fields`.

[options="nowrap"]
----
$ kcadm.sh get realms --fields realm,enabled
----

Можно отобразить результат как значения, разделенные запятыми.

[options="nowrap"]
----
$ kcadm.sh get realms --fields realm --format csv --noquotes
----

[discrete]
==== Получение определенного реалма

Добавьте имя области в URI коллекции, чтобы получить индивидуальный мир.

[options="nowrap"]
----
$ kcadm.sh get realms/master
----

[discrete]
==== Обновление области

. Используйте параметр `-s`, чтобы установить новые значения для атрибутов, когда вы не хотите изменять атрибуты этого реалма.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh update realms/demorealm -s enabled=false
----
. Если вы хотите установить все атрибуты, доступные для записи, на новые значения:
.. Выполните команду `get`.
.. Редактировать текущие значения в файле JSON.
.. Resubmit.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get realms/demorealm > demorealm.json
$ vi demorealm.json
$ kcadm.sh update realms/demorealm -f demorealm.json
----

[discrete]
==== Удаление области

Выполните следующую команду для удаления реалма:

[options="nowrap"]
----
$ kcadm.sh delete realms/demorealm
----

[discrete]
==== Включение всех опций страницы входа в мир

Задайте атрибуты, которые управляют конкретными способностями «true».

Например:

[options="nowrap"]
----
$ kcadm.sh update realms/demorealm -s registrationAllowed=true -s registrationEmailAsUsername=true -s rememberMe=true -s verifyEmail=true -s resetPasswordAllowed=true -s editUsernameAllowed=true
----

[discrete]
==== Список ключей реалма

Используйте операцию «get» на конечной точке целевого мира «ключ».

[options="nowrap"]
----
$ kcadm.sh get keys -r demorealm
----

[discrete]
==== Создание новых ключей реалма

. Получить идентификатор мишени перед добавлением новой пары ключей, генерируемой RSA.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get realms/demorealm --fields id --format csv --noquotes
----
. Добавить нового ключевого поставщика с более высоким приоритетом по сравнению с существующими провайдерами, как это показали `kcadm.sh get keys -r demorealm`.
+
Например:
* Linux:
+
[options="nowrap"]
----
$ kcadm.sh create components -r demorealm -s name=rsa-generated -s providerId=rsa-generated -s providerType=org.keycloak.keys.KeyProvider -s parentId=959844c1-d149-41d7-8359-6aa527fca0b0 -s 'config.priority=["101"]' -s 'config.enabled=["true"]' -s 'config.active=["true"]' -s 'config.keySize=["2048"]'
----
* Окна:
+
[options="nowrap"]
----
c:\> kcadm create components -r demorealm -s name=rsa-generated -s providerId=rsa-generated -s providerType=org.keycloak.keys.KeyProvider -s parentId=959844c1-d149-41d7-8359-6aa527fca0b0 -s "config.priority=[\"101\"]" -s "config.enabled=[\"true\"]" -s "config.active=[\"true\"]" -s "config.keySize=[\"2048\"]"
----
. Установите атрибут `parentId` в значение идентификатора целевого мира.
+
Теперь активным ключом является только недавно добавленный ключ, о чем свидетельствует `kcadm.sh get keys -r demorealm`.

[discrete]
==== Добавление новых ключей реалма из файла хранилища ключей Java

. Добавьте нового поставщика ключей для добавления новой пары ключей предварительно подготовленной в JKS файле.
+
Например, на:
* Linux:
+
[options="nowrap"]
----
$ kcadm.sh create components -r demorealm -s name=java-keystore -s providerId=java-keystore -s providerType=org.keycloak.keys.KeyProvider -s parentId=959844c1-d149-41d7-8359-6aa527fca0b0 -s 'config.priority=["101"]' -s 'config.enabled=["true"]' -s 'config.active=["true"]' -s 'config.keystore=["/opt/keycloak/keystore.jks"]' -s 'config.keystorePassword=["secret"]' -s 'config.keyPassword=["secret"]' -s 'config.keyAlias=["localhost"]'
----
* Окна:
+
[options="nowrap"]
----
c:\> kcadm create components -r demorealm -s name=java-keystore -s providerId=java-keystore -s providerType=org.keycloak.keys.KeyProvider -s parentId=959844c1-d149-41d7-8359-6aa527fca0b0 -s "config.priority=[\"101\"]" -s "config.enabled=[\"true\"]" -s "config.active=[\"true\"]" -s "config.keystore=[\"/opt/keycloak/keystore.jks\"]" -s "config.keystorePassword=[\"secret\"]" -s "config.keyPassword=[\"secret\"]" -s "config.keyAlias=[\"localhost\"]"
----
. Убедитесь, что вы изменили значения атрибутов `keystore`, `keystorePassword`, `keyPassword` и `alias`, чтобы они соответствовали вашему указанному ключевому магазину.
. Установите атрибут `parentId` в значение идентификатора целевого мира.

[discrete]
==== Создание пассивного ключа или отключение ключа

. Определите ключ, который вы хотите сделать пассивным.
+
[options="nowrap"]
----
$ kcadm.sh get keys -r demorealm
----
. Используйте атрибут `providerId` ключа для построения URI конечной точки, например, `components/PROVIDER_ID`.
. Выполнить `update`.
+
Например:
* Linux:
+
[options="nowrap"]
----
$ kcadm.sh update components/PROVIDER_ID -r demorealm -s 'config.active=["false"]'
----
* Окна:
+
[options="nowrap"]
----
c:\> kcadm update components/PROVIDER_ID -r demorealm -s "config.active=[\"false\"]"
----
+
Вы можете обновить другие атрибуты ключа:
* Установите новое значение `enabled`, чтобы отключить ключ, например, `config.enabled=["false"]`.
* Установите новое значение `priority` для изменения приоритета ключа, например, `config.priority=["110"]`.

[discrete]
==== Удаление старого ключа

. Убедитесь, что ключ, который вы удаляете, неактивен и вы отключили его. Это действие призвано предотвратить неудачу существующих токенов, принадлежащих приложениям и пользователям.
. Определите ключ для удаления.
+
[options="nowrap"]
----
$ kcadm.sh get keys -r demorealm
----
. Используйте `providerId` ключа для выполнения удаления.
+
[options="nowrap"]
----
$ kcadm.sh delete components/PROVIDER_ID -r demorealm
----

[discrete]
==== Настройка журнала событий для Realm

Используйте команду `update` в конечной точке `events/config`.

Атрибут `eventsListeners` содержит список ID EventListenerProviderFactory с указанием всех слушателей событий, которые получают события. Доступны атрибуты, которые управляют встроенным хранилищем событий, так что вы можете запрашивать последние события с помощью Admin REST API. {project_name} имеет отдельный контроль над протоколом вызовов службы (`eventsEnabled`) и аудиторскими событиями, инициированными консолью администратора или администратором REST API (`adminEventsEnabled`). Вы можете настроить срок действия события `eventsExpiration`, чтобы предотвратить заполнение базы данных. {project_name} устанавливает `eventsExpiration` на time-to-live в секундах.

Вы можете настроить встроенный слушатель событий, который получает все события и журналы событий через JBoss-loging. Использование `org.keycloak.events` logger, {project_name} записывает ошибки как `WARN` и другие события как `DEBUG`.

Например:

* Linux:
+
[options="nowrap"]
----
$ kcadm.sh update events/config -r demorealm -s 'eventsListeners=["jboss-logging"]'
----
* Окна:
+
[options="nowrap"]
----
c:\> kcadm update events/config -r demorealm -s "eventsListeners=[\"jboss-logging\"]"
----

Например:

Вы можете включить хранилище для всех доступных событий ERROR, не включая аудит событий, в течение двух дней, так что вы можете получить события через администратор REST.

* Linux:
+
[options="nowrap"]
----
$ kcadm.sh update events/config -r demorealm -s eventsEnabled=true -s 'enabledEventTypes=["LOGIN_ERROR","REGISTER_ERROR","LOGOUT_ERROR","CODE_TO_TOKEN_ERROR","CLIENT_LOGIN_ERROR","FEDERATED_IDENTITY_LINK_ERROR","REMOVE_FEDERATED_IDENTITY_ERROR","UPDATE_EMAIL_ERROR","UPDATE_PROFILE_ERROR","UPDATE_PASSWORD_ERROR","UPDATE_TOTP_ERROR","UPDATE_CREDENTIAL_ERROR","VERIFY_EMAIL_ERROR","REMOVE_TOTP_ERROR","REMOVE_CREDENTIAL_ERROR","SEND_VERIFY_EMAIL_ERROR","SEND_RESET_PASSWORD_ERROR","SEND_IDENTITY_PROVIDER_LINK_ERROR","RESET_PASSWORD_ERROR","IDENTITY_PROVIDER_FIRST_LOGIN_ERROR","IDENTITY_PROVIDER_POST_LOGIN_ERROR","CUSTOM_REQUIRED_ACTION_ERROR","EXECUTE_ACTIONS_ERROR","CLIENT_REGISTER_ERROR","CLIENT_UPDATE_ERROR","CLIENT_DELETE_ERROR"]' -s eventsExpiration=172800
----
* Окна:
+
[options="nowrap"]
----
c:\> kcadm update events/config -r demorealm -s eventsEnabled=true -s "enabledEventTypes=[\"LOGIN_ERROR\",\"REGISTER_ERROR\",\"LOGOUT_ERROR\",\"CODE_TO_TOKEN_ERROR\",\"CLIENT_LOGIN_ERROR\",\"FEDERATED_IDENTITY_LINK_ERROR\",\"REMOVE_FEDERATED_IDENTITY_ERROR\",\"UPDATE_EMAIL_ERROR\",\"UPDATE_PROFILE_ERROR\",\"UPDATE_PASSWORD_ERROR\",\"UPDATE_TOTP_ERROR\",\"UPDATE_CREDENTIAL_ERROR\",\"VERIFY_EMAIL_ERROR\",\"REMOVE_TOTP_ERROR\",\"REMOVE_CREDENTIAL_ERROR\",\"SEND_VERIFY_EMAIL_ERROR\",\"SEND_RESET_PASSWORD_ERROR\",\"SEND_IDENTITY_PROVIDER_LINK_ERROR\",\"RESET_PASSWORD_ERROR\",\"IDENTITY_PROVIDER_FIRST_LOGIN_ERROR\",\"IDENTITY_PROVIDER_POST_LOGIN_ERROR\",\"CUSTOM_REQUIRED_ACTION_ERROR\",\"EXECUTE_ACTIONS_ERROR\",\"CLIENT_REGISTER_ERROR\",\"CLIENT_UPDATE_ERROR\",\"CLIENT_DELETE_ERROR\"]" -s eventsExpiration=172800
----

Вы можете сбросить типы сохраненных событий на *все доступные типы событий*. Установка значения на пустой список совпадает с перечислением всех.

[options="nowrap"]
----
$ kcadm.sh update events/config -r demorealm -s enabledEventTypes=[]
----

Вы можете включить хранилище аудиторских событий.

[options="nowrap"]
----
$ kcadm.sh update events/config -r demorealm -s adminEventsEnabled=true -s adminEventsDetailsEnabled=true
----

Вы можете получить последние 100 событий. События упорядочены от новейших до старых.

[options="nowrap"]
----
$ kcadm.sh get events --offset 0 --limit 100
----

Вы можете удалить все сохраненные события.

[options="nowrap"]
----
$ kcadm delete events
----

[discrete]
==== Очистка тайников

. Используйте команду «создать» с одной из этих конечных точек для очистки кэша:
* `clear-realm-cache`
* `clear-user-cache`
* `clear-keys-cache`
. Установите `realm` в то же значение, что и целевой реалм.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create clear-realm-cache -r demorealm -s realm=demorealm
$ kcadm.sh create clear-user-cache -r demorealm -s realm=demorealm
$ kcadm.sh create clear-keys-cache -r demorealm -s realm=demorealm
----

[discrete]
==== Импортирование реалма из экспортированного файла .json

. Используйте команду `create` на конечной точке `partialImport`.
. Установите `ifResourceExists` в `FAIL`, `SKIP`, или `OVERWRITE`.
. Используйте `-f` для представления файла `.json` экспортируемого реалма.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create partialImport -r demorealm2 -s ifResourceExists=FAIL -o -f demorealm.json
----
+
Если реалм еще не существует, создайте его первым.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create realms -s realm=demorealm2 -s enabled=true
----

=== Ролевые операции

[discrete]
==== Создание роли области

Используйте конечную точку «роли» для создания роли реалма.

[options="nowrap"]
----
$ kcadm.sh create roles -r demorealm -s name=user -s 'description=Regular user with a limited set of permissions'
----

[discrete]
==== Создание роли клиента

. Определить клиента.
. Используйте команду `get` для просмотра списка доступных клиентов.
+
[options="nowrap"]
----
$ kcadm.sh get clients -r demorealm --fields id,clientId
----
. Создайте новую роль, используя атрибут «clientId» для построения конечного URI, например, «clients/ID/roles».
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create clients/a95b6af3-0bdc-4878-ae2e-6d61a4eca9a0/roles -r demorealm -s name=editor -s 'description=Editor can edit, and publish any article'
----

[discrete]
==== Список ролей реалма

Используйте команду `get` в конечной точке `roles`, чтобы перечислить существующие роли реалма.

[options="nowrap"]
----
$ kcadm.sh get roles -r demorealm
----

Вы можете также использовать команду `get-roles`.

[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm
----

[discrete]
==== Список ролей клиента

У {project_name} есть специальная команда `get-roles`, которая упрощает листинг реалма и роли клиентов. Команда представляет собой расширение команды `get` и ведет себя так же, как и команда `get`, но с дополнительной семантикой для ролей.

Используйте команду `get-roles`, передав ей опцию clientId (`--cclientid`) или опцию `id` (`--cid`) для идентификации роли клиента в списке.

Например:

[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --cclientid realm-management
----

[discrete]
==== Получение конкретной роли области

Используйте команду `get` и роль `name` для построения конечного URI для определенной роли реалма, `roles/ROLE_NAME`, где `user` — это имя существующей роли.

Например:

[options="nowrap"]
----
$ kcadm.sh get roles/user -r demorealm
----

Вы можете использовать команду `get-roles`, передав ей имя роли (опция `--rolename`) или ID (опция `--roleid`).

Например:

[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --rolename user
----

[discrete]
==== Получение роли клиента

Используйте команду `get-roles`, передав ей атрибут clientId (`--cclientid`) или атрибут ID (`--cid`) для идентификации клиента, и передайте имя роли (опция `--rolename`) или атрибут ID роли (`--roleid`), чтобы определить определенную роль клиента.

Например:

[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --cclientid realm-management --rolename manage-clients
----

[discrete]
==== Обновление роли области

Используйте команду `update` с URI конечной точки, который используется для получения определенной роли реалма.

Например:

[options="nowrap"]
----
$ kcadm.sh update roles/user -r demorealm -s 'description=Role representing a regular user'
----

[discrete]
==== Обновление роли клиента

Используйте команду `update` с конечным URI, который вы использовали для получения определенной роли клиента.

Например:

[options="nowrap"]
----
$ kcadm.sh update clients/a95b6af3-0bdc-4878-ae2e-6d61a4eca9a0/roles/editor -r demorealm -s 'description=User that can edit, and publish articles'
----

[discrete]
==== Удаление роли области

Используйте команду `delete` с конечным URI, который используется для получения определенной роли реалма.

Например:

[options="nowrap"]
----
$ kcadm.sh delete roles/user -r demorealm
----

[discrete]
==== Удаление роли клиента

Используйте команду `delete` с конечным URI, который вы использовали для получения определенной роли клиента.

Например:

[options="nowrap"]
----
$ kcadm.sh delete clients/a95b6af3-0bdc-4878-ae2e-6d61a4eca9a0/roles/editor -r demorealm
----

[discrete]
==== Перечисление назначенных, доступных и эффективных ролей для сводной роли

Используйте команду `get-roles`, чтобы перечислить назначенные, доступные и эффективные роли для составной роли.

. Чтобы перечислить *назначенные* роли области для составной роли, укажите составную роль по имени (опция `--rname`) или ID (опция `--rid`).
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --rname testrole
----
. Используйте параметр `--effective`, чтобы вывести список *эффективных* ролей.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --rname testrole --effective
----
. Используйте опцию `--available` для отображения ролей реалма, которые можно добавить в составную роль.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --rname testrole --available
----

[discrete]
==== Перечисление назначенных, доступных и эффективных ролей клиентов для сводной роли

Используйте команду `get-roles` чтобы перечислить назначенные, доступные и эффективные роли для составной роли.

. Чтобы перечислить *назначенные* роли клиента составной роли, вы можете указать целевую композитную роль по имени (опция `--rname`) или ID (опция `--rid`) и клиенту по атрибуту clientId (опция `--cclientid`) или ID (опция `--cid`).
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --rname testrole --cclientid realm-management
----
. Используйте параметр `--effective`, чтобы вывести список *эффективных* ролей.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --rname testrole --cclientid realm-management --effective
----
. Используйте опцию `--available` для отображения ролей реалма, которые вы можете добавить в составную роль.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --rname testrole --cclientid realm-management --available
----

[discrete]
==== Добавление ролей области в составную роль

{project_name} предоставляет команду `add-roles` для добавления ролей реалмов и ролей клиентов.

В этом примере добавляется роль пользователя в комбинированную роль `testrole`.

[options="nowrap"]
----
$ kcadm.sh add-roles --rname testrole --rolename user -r demorealm
----

[discrete]
==== Удаление ролей области из составной роли

{project_name} предоставляет команду `remove-roles` для удаления ролей Realm и ролей клиентов.

Следующий пример удаляет роль пользователя из составной роли "testrole".

[options="nowrap"]
----
$ kcadm.sh remove-roles --rname testrole --rolename user -r demorealm
----

[discrete]
==== Добавление ролей клиента в роль области

{project_name} предоставляет команду `add-roles` для добавления ролей реалмов и ролей клиентов.

Следующий пример добавляет в составную роль "testrole" роли клиента "realm-management", "create-client" и "view-users".

[options="nowrap"]
----
$ kcadm.sh add-roles -r demorealm --rname testrole --cclientid realm-management --rolename create-client --rolename view-users
----

[discrete]
==== Добавление ролей клиента в роли клиента

. Определите ID роли составного клиента, используя команду get-roles`.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --cclientid test-client --rolename operations
----
. Предположим, что клиент существует с атрибутом clientId под названием `test-client`, роль клиента под названием `support`, и роль клиента "операции", которая становится составной ролью, имеющей идентификатор "fc400897-ef6a-4e8c-872b-1581b7fa8a71".
. Используйте следующий пример, чтобы добавить другую роль в составную роль.
+
[options="nowrap"]
----
$ kcadm.sh add-roles -r demorealm --cclientid test-client --rid fc400897-ef6a-4e8c-872b-1581b7fa8a71 --rolename support
----
. Список ролей составной роли, используя команду `get-roles --all`.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles --rid fc400897-ef6a-4e8c-872b-1581b7fa8a71 --all
----

[discrete]
==== Удаление ролей клиента из составной роли

Используйте команду "remove-roles", чтобы удалить роли клиента из составной роли.

Используйте следующий пример, чтобы удалить две роли, определенные в «realm-management» клиента, роль «create-client» и роль «view-users» из составной роли «testrole».

[options="nowrap"]
----
$ kcadm.sh remove-roles -r demorealm --rname testrole --cclientid realm-management --rolename create-client --rolename view-users
----

[discrete]
==== Добавление ролей клиента в группу

Используйте команду «Addroles», чтобы добавить роли Realm и роли клиента.

Следующий пример добавляет роли, определенные в `realm-management`, `create-client` и `view-users`, в группу `Group` (`--gname`). Кроме того, вы можете указать группу по ID (опция `--gid`).

Смотрите <<_group_operations, Group operations>> для получения дополнительной информации.

[options="nowrap"]
----
$ kcadm.sh add-roles -r demorealm --gname Group --cclientid realm-management --rolename create-client --rolename view-users
----

[discrete]
==== Удаление ролей клиента из группы

Используйте команду "remove-roles", чтобы удалить роли клиента из группы.

Следующий пример удаляет две роли, определенные в «realm-management» клиента, «create-client» и «view-users» из группы «Group».

Смотрите <<_group_operations, Group operations>> для получения дополнительной информации.

[options="nowrap"]
----
$ kcadm.sh remove-roles -r demorealm --gname Group --cclientid realm-management --rolename create-client --rolename view-users
----

=== Операции с клиентом

[discrete]
==== Создание клиента

. Запустите команду `create` на конечной точке `clients` для создания нового клиента.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create clients -r demorealm -s clientId=myapp -s enabled=true
----
. Укажите секрет для аутентификации адаптеров.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create clients -r demorealm -s clientId=myapp -s enabled=true -s clientAuthenticatorType=client-secret -s secret=d0b8122f-8dfb-46b7-b68a-f5cc4e25d000
----

[discrete]
==== Список клиентов

Используйте команду `get` на конечной точке `clients` для просмотра списка клиентов.

Этот пример фильтрует вывод только атрибутов `id` и `clientId`:

[options="nowrap"]
----
$ kcadm.sh get clients -r demorealm --fields id,clientId
----

[discrete]
==== Получение определенного клиента

Используйте идентификатор клиента для построения конечного URI, предназначенного для конкретного клиента, например «clients/ID».

Например:

[options="nowrap"]
----
$ kcadm.sh get clients/c7b8547f-e748-4333-95d0-410b76b3f4a3 -r demorealm
----

[discrete]
==== Получение текущего секрета для определенного клиента

Используйте идентификатор клиента для построения конечного URI, например, `clients/ID/client-secret`.

Например:

[options="nowrap"]
----
$ kcadm.sh get clients/$CID/client-secret -r demorealm
----

[discrete]
==== Сгенерировать новый секретный ключ для определенного клиента

Используйте идентификатор клиента для построения конечного URI, например, `clients/ID/client-secret`.

Например:

[options="nowrap"]
----
$ kcadm.sh create clients/$CID/client-secret -r demorealm
----

[discrete]
==== Обновление текущего секретного ключа для определенного клиента

Используйте идентификатор клиента для построения конечного URI, например, «clients/ID».

Например:

[options="nowrap"]
----
$ kcadm.sh update clients/$CID -s "secret=newSecret" -r demorealm
----

[discrete]
==== Получение файла конфигурации адаптера (keycloak.json) для определенного клиента

Используйте идентификатор клиента для построения конечного URI, предназначенного для определенного клиента, например, `clients/ID/installation/providers/keycloak-oidc-keycloak-json`.

Например:

[options="nowrap"]
----
$ kcadm.sh get clients/c7b8547f-e748-4333-95d0-410b76b3f4a3/installation/providers/keycloak-oidc-keycloak-json -r demorealm
----

[discrete]
==== Получение конфигурации подсистемного адаптера WildFly для определенного клиента

Используйте идентификатор клиента для построения конечного URI, предназначенного для определенного клиента, например, `clients/ID/installation/providers/keycloak-oidc-jboss-subsystem`.

Например:

[options="nowrap"]
----
$ kcadm.sh get clients/c7b8547f-e748-4333-95d0-410b76b3f4a3/installation/providers/keycloak-oidc-jboss-subsystem -r demorealm
----

[discrete]
==== Получение примера Docker-v2 для конкретного клиента

Используйте идентификатор клиента для построения конечного URI, предназначенного для определенного клиента, например, `clients/ID/installation/providers/docker-v2-compose-yaml`.

Ответ находится в формате `.zip`. zip`.

Например:

[options="nowrap",subs="attributes+"]
----
$ kcadm.sh get http://localhost:8080{kc_admins_path}/realms/demorealm/clients/8f271c35-44e3-446f-8953-b0893810ebe7/installation/providers/docker-v2-compose-yaml -r demorealm > keycloak-docker-compose-yaml.zip
----

[discrete]
==== Обновление клиента

Используйте команду `update` с тем же URI конечной точкой, что вы используете, чтобы получить определенного клиента.

Например:

* Linux:
+
[options="nowrap"]
----
$ kcadm.sh update clients/c7b8547f-e748-4333-95d0-410b76b3f4a3 -r demorealm -s enabled=false -s publicClient=true -s 'redirectUris=["http://localhost:8080/myapp/*"]' -s baseUrl=http://localhost:8080/myapp -s adminUrl=http://localhost:8080/myapp
----
* Окна:
+
[options="nowrap"]
----
c:\> kcadm update clients/c7b8547f-e748-4333-95d0-410b76b3f4a3 -r demorealm -s enabled=false -s publicClient=true -s "redirectUris=[\"http://localhost:8080/myapp/*\"]" -s baseUrl=http://localhost:8080/myapp -s adminUrl=http://localhost:8080/myapp
----

[discrete]
==== Удаление клиента

Используйте команду `delete` с тем же URI конечной точкой, что вы используете, чтобы получить определенного клиента.

Например:

[options="nowrap"]
----
$ kcadm.sh delete clients/c7b8547f-e748-4333-95d0-410b76b3f4a3 -r demorealm
----

[discrete]
==== Добавление или удаление ролей для клиентской учетной записи

Учётная запись клиента - это учетная запись пользователя с именем пользователя `service-account-CLIENT_ID`. Вы можете выполнять операции с этой учетной записью одного пользователя в качестве обычной учетной записи.

=== Операции пользователя

[discrete]
==== Создание пользователя

Запустите команду `create` на конечной точке `users` для создания нового пользователя.

Например:

[options="nowrap"]
----
$ kcadm.sh create users -r demorealm -s username=testuser -s enabled=true
----

[discrete]
==== Список пользователей

Используйте конечную точку `users` для списка пользователей. Целевой пользователь должен изменить свой пароль при следующем входе в систему.

Например:

[options="nowrap"]
----
$ kcadm.sh get users -r demorealm --offset 0 --limit 1000
----

Вы можете фильтровать пользователей по имени `username`, `firstName`, `lastName`, или `email`.

Например:

[options="nowrap"]
----
$ kcadm.sh get users -r demorealm -q q=email:google.com
$ kcadm.sh get users -r demorealm -q q=username:testuser
----

[NOTE]
====
Фильтрация не использует точное совпадение. Этот пример соответствует значению атрибута `username` относительно шаблона `\*testuser*`.
====

Для клиентов, групп и пользователей вы можете фильтровать по нескольким атрибутам, указав более сложный параметр запроса `q`.  вы можете использовать что-то вроде -q q="field1:value1 field2:value2". {project_name} возвращает пользователей, которые соответствуют условию только для всех атрибутов.

[discrete]
==== Получение конкретного пользователя

Используйте ID пользователя для создания конечного URI, например, `users/USER_ID`.

Например:

[options="nowrap"]
----
$ kcadm.sh get users/0ba7a3fd-6fd8-48cd-a60b-2e8fd82d56e2 -r demorealm
----

[discrete]
==== Обновление пользователя

Используйте команду `update` с тем же URI конечной точкой, что вы используете, чтобы получить конкретного пользователя.

Например:

* Linux:
+
[options="nowrap"]
----
$ kcadm.sh update users/0ba7a3fd-6fd8-48cd-a60b-2e8fd82d56e2 -r demorealm -s 'requiredActions=["VERIFY_EMAIL","UPDATE_PROFILE","CONFIGURE_TOTP","UPDATE_PASSWORD"]'
----
* Окна:
+
[options="nowrap"]
----
c:\> kcadm update users/0ba7a3fd-6fd8-48cd-a60b-2e8fd82d56e2 -r demorealm -s "requiredActions=[\"VERIFY_EMAIL\",\"UPDATE_PROFILE\",\"CONFIGURE_TOTP\",\"UPDATE_PASSWORD\"]"
----

[discrete]
==== Удаление пользователя

Используйте команду `delete` с тем же URI конечной точкой, что вы используете, чтобы получить конкретного пользователя.

Например:

[options="nowrap"]
----
$ kcadm.sh delete users/0ba7a3fd-6fd8-48cd-a60b-2e8fd82d56e2 -r demorealm
----

[discrete]
==== Сброс пароля пользователя

Используйте специальную команду «set-password», чтобы сбросить пароль пользователя.

Например:

[options="nowrap"]
----
$ kcadm.sh set-password -r demorealm --username testuser --new-password NEWPASSWORD --temporary
----

Эта команда устанавливает временный пароль для пользователя. Целевой пользователь должен изменить пароль при следующем входе в систему.

Вы можете использовать `--userid` для указания пользователя с помощью атрибута `id`.

Вы можете достичь того же результата, используя команду `update` на конечной точке, построенной из той, которую вы использовали для получения конкретного пользователя, например `users/USER_ID/reset-password`.

Например:

[options="nowrap"]
----
$ kcadm.sh update users/0ba7a3fd-6fd8-48cd-a60b-2e8fd82d56e2/reset-password -r demorealm -s type=password -s value=NEWPASSWORD -s temporary=true -n
----

Параметр `-n` гарантирует, что {project_name} выполняет команду `PUT` без выполнения команды `GET` перед командой `PUT`. Это необходимо, потому что конечная точка `reset-password` не поддерживает `GET`.

[discrete]
==== Список назначенных, доступных и эффективных ролей для пользователя

Вы можете использовать команду `get-roles`, чтобы перечислить назначенные, доступные и эффективные роли реалма для пользователя.

. Укажите целевого пользователя по имени пользователя или ID, чтобы перечислить *назначенные* роли игрока.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --uusername testuser
----
. Используйте параметр `--effective`, чтобы вывести список *эффективных* ролей.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --uusername testuser --effective
----
. Используйте опцию `--available` для отображения ролей реалма, которые вы можете добавить пользователю.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --uusername testuser --available
----

[discrete]
==== Список назначенных, доступных и эффективных ролей клиента для пользователя

Используйте команду `get-roles` чтобы перечислить назначенные, доступные и эффективные роли клиента для пользователя.

. Укажите конечного пользователя по имени пользователя (опция `--uusername`) или ID (опция `--uid`) и клиента по атрибуту clientId (опция `--cclientid`) или ID (опция `--cid`), чтобы перечислить *назначенные* роли клиента.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --uusername testuser --cclientid realm-management
----
. Используйте параметр `--effective`, чтобы вывести список *эффективных* ролей.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --uusername testuser --cclientid realm-management --effective
----
. Используйте опцию `--available` для отображения ролей реалма, которые вы можете добавить пользователю.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --uusername testuser --cclientid realm-management --available
----

[discrete]
==== Добавление ролей реалма пользователю

Используйте команду «Addroles», чтобы добавить пользователю роли реалма.

Используйте следующий пример, чтобы добавить роль `user` пользователю `testuser`:

[options="nowrap"]
----
$ kcadm.sh add-roles --uusername testuser --rolename user -r demorealm
----

[discrete]
==== Удаление ролей реалма пользователя

Используйте команду «remove-roles» для удаления ролей реалма у пользователя.

Используйте следующий пример, чтобы удалить роль `user` из пользователя `testuser`:

[options="nowrap"]
----
$ kcadm.sh remove-roles --uusername testuser --rolename user -r demorealm
----

[discrete]
==== Добавление ролей клиента к пользователю

Используйте команду `add-roles`, чтобы добавить роли клиента к пользователю.

Используйте следующий пример, чтобы добавить две роли, определенные в `realm-management`, роль `create-client` и роль `view-users` пользователю `testuser`.

[options="nowrap"]
----
$ kcadm.sh add-roles -r demorealm --uusername testuser --cclientid realm-management --rolename create-client --rolename view-users
----

[discrete]
==== Удаление ролей клиента у пользователя

Используйте команду "remove-roles", чтобы удалить роли клиента у пользователя.

Используйте следующий пример, чтобы удалить две роли, определенные в Realm-management клиенте:

[options="nowrap"]
----
$ kcadm.sh remove-roles -r demorealm --uusername testuser --cclientid realm-management --rolename create-client --rolename view-users
----

[discrete]
==== Список пользовательских сессий

. Укажите ID пользователя,
. Используйте ID для создания конечного URI, например `users/ID/sessions`.
. Используйте команду `get`, чтобы получить список пользовательских сессий.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get users/6da5ab89-3397-4205-afaa-e201ff638f9e/sessions -r demorealm
----

[discrete]
==== Выход пользователя из определенной сессии

. Определить ID сеанса, как описано ранее.
. Используйте идентификатор сеанса для создания конечного URI, например, `sessions/ID`.
. Используйте команду `delete`, чтобы аннулировать сессию.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh delete sessions/d0eaa7cc-8c5d-489d-811a-69d3c4ec84d1 -r demorealm
----

[discrete]
==== Выход пользователя из всех сессий

Используйте идентификатор пользователя для построения конечного URI, например, `users/ID/logout`.

Используйте команду `create` для выполнения `POST` с этой конечной точкой URI.

Например:

[options="nowrap"]
----
$ kcadm.sh create users/6da5ab89-3397-4205-afaa-e201ff638f9e/logout -r demorealm -s realm=demorealm -s user=6da5ab89-3397-4205-afaa-e201ff638f9e
----

[[_group_operations]]
=== Операции группы

[discrete]
==== Создание группы

Используйте команду `create` в конечной точке `groups` для создания новой группы.

Например:

[options="nowrap"]
----
$ kcadm.sh create groups -r demorealm -s name=Group
----

[discrete]
==== Список групп

Используйте команду `get` на конечной точке `groups` в списке групп.

Например:

[options="nowrap"]
----
$ kcadm.sh get groups -r demorealm
----

[discrete]
==== Получение определенной группы

Используйте ID группы для построения конечного URI, например, `groups/GROUP_ID`.

Например:

[options="nowrap"]
----
$ kcadm.sh get groups/51204821-0580-46db-8f2d-27106c6b5ded -r demorealm
----

[discrete]
==== Обновление группы

Используйте команду `update` с тем же URI конечной точкой, что вы используете, чтобы получить определенную группу.

Например:

[options="nowrap"]
----
$ kcadm.sh update groups/51204821-0580-46db-8f2d-27106c6b5ded -s 'attributes.email=["group@example.com"]' -r demorealm
----

[discrete]
==== Удаление группы

Используйте команду `delete` с тем же URI конечной точки, что вы используете, чтобы получить определенную группу.

Например:

[options="nowrap"]
----
$ kcadm.sh delete groups/51204821-0580-46db-8f2d-27106c6b5ded -r demorealm
----

[discrete]
==== Создание подгруппы

Найдите ID родительской группы по группам. Используйте этот ID для построения конечного URI, например, `groups/GROUP_ID/children`.

Например:

[options="nowrap"]
----
$ kcadm.sh create groups/51204821-0580-46db-8f2d-27106c6b5ded/children -r demorealm -s name=SubGroup
----

[discrete]
==== Перемещение группы в другую группу

. Найдите ID существующей родительской группы и ID существующей дочерней группы.
. Используйте ID родительской группы для построения конечного URI, например, `groups/PARENT_GROUP_ID/children`.
. Запустите команду «создать» на этой конечной точке и передайте ID дочерней группы как тело JSON.

Например:

[options="nowrap"]
----
$ kcadm.sh create groups/51204821-0580-46db-8f2d-27106c6b5ded/children -r demorealm -s id=08d410c6-d585-4059-bb07-54dcb92c5094 -s name=SubGroup
----

[discrete]
==== Получить группы для определенного пользователя

Используйте идентификатор пользователя для определения членства пользователя в группах для создания конечного URI, например, `users/USER_ID/groups`.

Например:

[options="nowrap"]
----
$ kcadm.sh get users/b544f379-5fc4-49e5-8a8d-5cfb71f46f53/groups -r demorealm
----

[discrete]
==== Добавление пользователя в группу

Используйте команду `update` с конечным URI в составе ID пользователя и ID группы, например `users/USER_ID/groups/GROUP_ID`, чтобы добавить пользователя в группу.

Например:

[options="nowrap"]
----
$ kcadm.sh update users/b544f379-5fc4-49e5-8a8d-5cfb71f46f53/groups/ce01117a-7426-4670-a29a-5c118056fe20 -r demorealm -s realm=demorealm -s userId=b544f379-5fc4-49e5-8a8d-5cfb71f46f53 -s groupId=ce01117a-7426-4670-a29a-5c118056fe20 -n
----

[discrete]
==== Удаление пользователя из группы

Используйте команду `delete` на том же URI конечной точке, который вы используете для добавления пользователя в группу, например `users/USER_ID/groups/GROUP_ID`, чтобы удалить пользователя из группы.

Например:

[options="nowrap"]
----
$ kcadm.sh delete users/b544f379-5fc4-49e5-8a8d-5cfb71f46f53/groups/ce01117a-7426-4670-a29a-5c118056fe20 -r demorealm
----

[discrete]
==== Список назначенных, доступных и эффективных ролей для группы

Используйте специальную команду `get-roles`, чтобы перечислить назначенные, доступные и эффективные роли в реалме.

. Укажите целевую группу по имени (опция `--gname`), путь (опция `--gpath`), или ID (опция `--gid`), чтобы перечислить *назначенные* роли в группе.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --gname Group
----
. Используйте параметр `--effective`, чтобы вывести список *эффективных* ролей.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --gname Group --effective
----
. Используйте опцию `--available` для отображения ролей реалма, которые вы можете добавить в группу.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --gname Group --available
----

[discrete]
==== Список назначенных, доступных и эффективных ролей клиентов для группы

Используйте команду `get-roles` чтобы перечислить назначенные, доступные и эффективные роли клиента для группы.

. Укажите целевую группу по имени (опция `--gname`) или ID (опция `--gid`),
. Укажите клиент, по параметру clientId (опция `--cclientid`) или ID (опция `--id`) для отображения *назначенных* ролей для пользователя.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --gname Group --cclientid realm-management
----
. Используйте параметр `--effective`, чтобы вывести список *эффективных* ролей.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --gname Group --cclientid realm-management --effective
----
. Используйте опцию `--available` для отображения ролей реалма, которые все еще можно добавить в группу.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh get-roles -r demorealm --gname Group --cclientid realm-management --available
----

=== Операции поставщика удостоверений личности

[discrete]
==== Список доступных поставщиков идентификации

Используйте конечную точку `serverinfo` для списка доступных провайдеров идентификации.

Например:

[options="nowrap"]
----
$ kcadm.sh get serverinfo -r demorealm --fields 'identityProviders(*)'
----

[NOTE]
====
{project_name} обрабатывает конечную точку `serverinfo`, аналогично конечной точке `realms`. {project_name} не разрешает конечную точку относительно мишенного мира, так как он существует вне любого конкретного реалма.
====

[discrete]
==== Список настроенных поставщиков идентификации

Используйте конечную точку `identity-provider/instances`.

Например:

[options="nowrap"]
----
$ kcadm.sh get identity-provider/instances -r demorealm --fields alias,providerId,enabled
----

[discrete]
==== Получение определенного поставщика идентификации

Используйте атрибут `alias` поставщика идентификации для построения URI конечной точки, например `identity-provider/instances/ALIAS`, для получения определенного поставщика идентификационных данных.

Например:

[options="nowrap"]
----
$ kcadm.sh get identity-provider/instances/facebook -r demorealm
----

[discrete]
==== Удаление определенного поставщика идентификации

Используйте команду `delete` с тем же URI конечной точкой, что вы используете, чтобы получить конкретный сконфигурированный поставщик идентификации для удаления определенного поставщика идентификации.

Например:

[options="nowrap"]
----
$ kcadm.sh delete identity-provider/instances/facebook -r demorealm
----

[discrete]
==== Настройка поставщика идентификации OpenID Connect Keycloak

. Используйте `keycloak-oidc` в качестве `providerId` при создании нового экземпляра поставщика идентификации.
. Укажите атрибуты `config`: `authorizationUrl`, `tokenUrl`, `clientId` и `clientSecret`.
+
Например:
+
[options="nowrap",subs=+attributes]
----
$ kcadm.sh create identity-provider/instances -r demorealm -s alias=keycloak-oidc -s providerId=keycloak-oidc -s enabled=true -s 'config.useJwksUrl="true"' -s config.authorizationUrl=http://localhost:8180{kc_realms_path}/demorealm/protocol/openid-connect/auth -s config.tokenUrl=http://localhost:8180{kc_realms_path}/demorealm/protocol/openid-connect/token -s config.clientId=demo-oidc-provider -s config.clientSecret=secret
----

[discrete]
==== Настройка поставщика идентификации OpenID Connect

Настройте провайдера обобщенного OpenID Connect таким же образом, как и ваш провайдер Keycloak OpenID Connect, за исключением значения атрибута `providerId` в `oidc`.

[discrete]
==== Настройка оператора идентификации SAML 2

. Используйте «saml» в качестве «providerId».
. Предоставьте атрибуты `config`: `singleSignOnServiceUrl`, `nameIDPolicyFormat` и `signatureAlgorithm`.

Например:

[options="nowrap",subs=+attributes]
----
$ kcadm.sh create identity-provider/instances -r demorealm -s alias=saml -s providerId=saml -s enabled=true -s 'config.useJwksUrl="true"' -s config.singleSignOnServiceUrl=http://localhost:8180{kc_realms_path}/saml-broker-realm/protocol/saml -s config.nameIDPolicyFormat=urn:oasis:names:tc:SAML:2.0:nameid-format:persistent -s config.signatureAlgorithm=RSA_SHA256
----

[discrete]
==== Настройка провайдера идентификации Facebook

. Используйте `facebook` как `providerId`.
. Укажите атрибуты `config`: `clientId` и `clientSecret`. Вы можете найти эти атрибуты на странице настройки приложения Facebook Developers для вашего приложения. Смотрите <_facebook, Facebook identity broker>> страницу для получения дополнительной информации.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create identity-provider/instances -r demorealm -s alias=facebook -s providerId=facebook -s enabled=true  -s 'config.useJwksUrl="true"' -s config.clientId=FACEBOOK_CLIENT_ID -s config.clientSecret=FACEBOOK_CLIENT_SECRET
----

[discrete]
==== Настройка провайдера идентификации Google

. Используйте «google» в качестве «providerId».
. Укажите атрибуты `config`: `clientId` и `clientSecret`. Эти атрибуты можно найти на странице настройки приложений Google Developers для вашего приложения. Смотрите <_google, идентификационный брокер>> на странице <_google.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create identity-provider/instances -r demorealm -s alias=google -s providerId=google -s enabled=true  -s 'config.useJwksUrl="true"' -s config.clientId=GOOGLE_CLIENT_ID -s config.clientSecret=GOOGLE_CLIENT_SECRET
----

[discrete]
==== Настройка провайдера идентификации Twitter

. Используйте «twitter» в качестве «providerId».
. Укажите `config` атрибуты `clientId` и `clientSecret`. Эти атрибуты можно найти на странице настройки приложения Twitter для вашего приложения. Смотрите страницу <_twitter, идентификационный брокер Twitter>> для получения дополнительной информации.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create identity-provider/instances -r demorealm -s alias=google -s providerId=google -s enabled=true  -s 'config.useJwksUrl="true"' -s config.clientId=TWITTER_API_KEY -s config.clientSecret=TWITTER_API_SECRET
----

[discrete]
==== Configuring a GitHub identity provider

. Используйте `github` как `providerId`.
. Укажите `config` атрибуты `clientId` и `clientSecret`. Вы можете найти эти атрибуты на странице Настройки приложения разработчика GitHub. Смотрите <_github, идентификационный брокер>> страницу GitHub.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create identity-provider/instances -r demorealm -s alias=github -s providerId=github -s enabled=true  -s 'config.useJwksUrl="true"' -s config.clientId=GITHUB_CLIENT_ID -s config.clientSecret=GITHUB_CLIENT_SECRET
----

[discrete]
==== Configuring a LinkedIn identity provider

. Используйте `linkedin` как `providerId`.
. Укажите `config` атрибуты `clientId` и `clientSecret`. Эти атрибуты вы можете найти на странице приложения LinkedIn Developer Console для вашего приложения. См. <_linkedin, LinkedIn identity broker>> страницу .
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create identity-provider/instances -r demorealm -s alias=linkedin -s providerId=linkedin -s enabled=true  -s 'config.useJwksUrl="true"' -s config.clientId=LINKEDIN_CLIENT_ID -s config.clientSecret=LINKEDIN_CLIENT_SECRET
----

[discrete]
==== Configuring a Microsoft Live identity provider

. Используйте «microsoft» в качестве «providerId».
. Укажите `config` атрибуты `clientId` и `clientSecret`. Эти атрибуты можно найти на странице регистрации Microsoft Application Application Registration Portal для вашего приложения. Смотрите страницу <<_microsoft, идентификационный брокер>> .
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create identity-provider/instances -r demorealm -s alias=microsoft -s providerId=microsoft -s enabled=true  -s 'config.useJwksUrl="true"' -s config.clientId=MICROSOFT_APP_ID -s config.clientSecret=MICROSOFT_PASSWORD
----

[discrete]
==== Настройка поставщика идентификаций стека переполнения

. Используйте команду `stackoverflow` как `providerId`.
. Укажите атрибуты `clientId`, `clientSecret` и `key`. Эти атрибуты можно найти на странице OAuth приложений стека. Смотрите страницу <_stackoverflow, Stack Overflow identity broker>> .
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create identity-provider/instances -r demorealm -s alias=stackoverflow -s providerId=stackoverflow -s enabled=true  -s 'config.useJwksUrl="true"' -s config.clientId=STACKAPPS_CLIENT_ID -s config.clientSecret=STACKAPPS_CLIENT_SECRET -s config.key=STACKAPPS_KEY
----

=== Операции провайдера хранения

[discrete]
==== Настройка провайдера хранилища Kerberos

. Используйте команду `create` против конечной точки `components`.
. Укажите идентификатор области в качестве значения атрибута `parentId`.
. Укажите `kerberos` в качестве значения атрибута `providerId` и `org.keycloak.storage.UserStorageProvider` в качестве значения атрибута `providerType`.
. Например:
+
[options="nowrap"]
----
$ kcadm.sh create components -r demorealm -s parentId=demorealmId -s id=demokerberos -s name=demokerberos -s providerId=kerberos -s providerType=org.keycloak.storage.UserStorageProvider -s 'config.priority=["0"]' -s 'config.debug=["false"]' -s 'config.allowPasswordAuthentication=["true"]' -s 'config.editMode=["UNSYNCED"]' -s 'config.updateProfileFirstLogin=["true"]' -s 'config.allowKerberosAuthentication=["true"]' -s 'config.kerberosRealm=["KEYCLOAK.ORG"]' -s 'config.keyTab=["http.keytab"]' -s 'config.serverPrincipal=["HTTP/localhost@KEYCLOAK.ORG"]' -s 'config.cachePolicy=["DEFAULT"]'
----

[discrete]
==== Настройка провайдера хранения данных LDAP

. Используйте команду `create` против конечной точки `components`.
. Укажите `ldap` в качестве значения атрибута `providerId` и `org.keycloak.storage.UserStorageProvider` в качестве значения атрибута `providerType`.
. Введите ID области как значение атрибута `parentId`.
. Используйте следующий пример для создания Kerberos-Integrated LDAP провайдера.
+
[options="nowrap"]
----
$ kcadm.sh create components -r demorealm -s name=kerberos-ldap-provider -s providerId=ldap -s providerType=org.keycloak.storage.UserStorageProvider -s parentId=3d9c572b-8f33-483f-98a6-8bb421667867  -s 'config.priority=["1"]' -s 'config.fullSyncPeriod=["-1"]' -s 'config.changedSyncPeriod=["-1"]' -s 'config.cachePolicy=["DEFAULT"]' -s config.evictionDay=[] -s config.evictionHour=[] -s config.evictionMinute=[] -s config.maxLifespan=[] -s 'config.batchSizeForSync=["1000"]' -s 'config.editMode=["WRITABLE"]' -s 'config.syncRegistrations=["false"]' -s 'config.vendor=["other"]' -s 'config.usernameLDAPAttribute=["uid"]' -s 'config.rdnLDAPAttribute=["uid"]' -s 'config.uuidLDAPAttribute=["entryUUID"]' -s 'config.userObjectClasses=["inetOrgPerson, organizationalPerson"]' -s 'config.connectionUrl=["ldap://localhost:10389"]'  -s 'config.usersDn=["ou=People,dc=keycloak,dc=org"]' -s 'config.authType=["simple"]' -s 'config.bindDn=["uid=admin,ou=system"]' -s 'config.bindCredential=["secret"]' -s 'config.searchScope=["1"]' -s 'config.useTruststoreSpi=["always"]' -s 'config.connectionPooling=["true"]' -s 'config.pagination=["true"]' -s 'config.allowKerberosAuthentication=["true"]' -s 'config.serverPrincipal=["HTTP/localhost@KEYCLOAK.ORG"]' -s 'config.keyTab=["http.keytab"]' -s 'config.kerberosRealm=["KEYCLOAK.ORG"]' -s 'config.debug=["true"]' -s 'config.useKerberosForPasswordAuthentication=["true"]'
----

[discrete]
==== Удаление экземпляра провайдера хранения данных

. Используйте атрибут `id` хранилища для создания конечной точки URI, например `components/ID`.
. Выполните команду `delete` с этой конечной точкой.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh delete components/3d9c572b-8f33-483f-98a6-8bb421667867 -r demorealm
----

[discrete]
==== Запуск синхронизации всех пользователей для определенного провайдера хранения данных

. Используйте атрибут `id` хранилища для создания URI конечной точки, например `user-storage/ID_OF_USER_STORAGE_INSTANCE/sync`.
. Добавьте параметр запроса `action=triggerFullSync`.
. Выполните команду `create`.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create user-storage/b7c63d02-b62a-4fc1-977c-947d6a09e1ea/sync?action=triggerFullSync
----

[discrete]
==== Запуск синхронизации измененных пользователей для определенного провайдера хранения данных

. Используйте атрибут `id` хранилища для создания URI конечной точки, например `user-storage/ID_OF_USER_STORAGE_INSTANCE/sync`.
. Добавьте параметр запроса `action=triggerChangedUsersSync`.
. Выполните команду `create`.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create user-storage/b7c63d02-b62a-4fc1-977c-947d6a09e1ea/sync?action=triggerChangedUsersSync
----

[discrete]
==== Проверить подключение к хранилищу LDAP

. Запустите команду `get` на конечной точке `testLDAPConnection`.
. Предоставьте параметры запроса `bindCredential`, `bindDn`, `connectionUrl` и `useTruststoreSpi`.
. Установил параметр запроса `action` в `testConnection`.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create testLDAPConnection -s action=testConnection -s bindCredential=secret -s bindDn=uid=admin,ou=system -s connectionUrl=ldap://localhost:10389 -s useTruststoreSpi=always
----

[discrete]
==== Тестировать аутентификацию пользователя LDAP

. Запустите команду `get` на конечной точке `testLDAPConnection`.
. Предоставьте параметры запроса `bindCredential`, `bindDn`, `connectionUrl` и `useTruststoreSpi`.
. Установил параметр запроса `action` в `testAuthentication`.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create testLDAPConnection -s action=testAuthentication -s bindCredential=secret -s bindDn=uid=admin,ou=system -s connectionUrl=ldap://localhost:10389 -s useTruststoreSpi=always
----

=== Добавление картографа

[discrete]
==== Добавление твердой роли LDAP mapper

. Запустите команду `create` на конечной точке `components`.
. Установите атрибут `providerType` в `org.keycloak.storage.ldap.mappers.LDAPStorageMapper`.
. Установите атрибут `parentId` на ID экземпляра LDAP провайдера.
. Установите атрибут `providerId` в `hardcoded-ldap-role-mapper`. Убедитесь, что вы указали параметр конфигурации `role`.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create components -r demorealm -s name=hardcoded-ldap-role-mapper -s providerId=hardcoded-ldap-role-mapper -s providerType=org.keycloak.storage.ldap.mappers.LDAPStorageMapper -s parentId=b7c63d02-b62a-4fc1-977c-947d6a09e1ea -s 'config.role=["realm-management.create-client"]'
----

[discrete]
==== Добавление MS Active Directory mapper

. Запустите команду `create` на конечной точке `components`.
. Установите атрибут `providerType` в `org.keycloak.storage.ldap.mappers.LDAPStorageMapper`.
. Установите атрибут `parentId` на ID экземпляра LDAP провайдера.
. Установите атрибут `providerId` в `msad-user-account-control-mapper`.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create components -r demorealm -s name=msad-user-account-control-mapper -s providerId=msad-user-account-control-mapper -s providerType=org.keycloak.storage.ldap.mappers.LDAPStorageMapper -s parentId=b7c63d02-b62a-4fc1-977c-947d6a09e1ea
----

[discrete]
==== Добавление атрибута пользователя LDAP mapper

. Запустите команду `create` на конечной точке `components`.
. Установите атрибут `providerType` в `org.keycloak.storage.ldap.mappers.LDAPStorageMapper`.
. Установите атрибут `parentId` на ID экземпляра LDAP провайдера.
. Установите атрибут `providerId` в `user-attribute-ldap-mapper`.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create components -r demorealm -s name=user-attribute-ldap-mapper -s providerId=user-attribute-ldap-mapper -s providerType=org.keycloak.storage.ldap.mappers.LDAPStorageMapper -s parentId=b7c63d02-b62a-4fc1-977c-947d6a09e1ea -s 'config."user.model.attribute"=["email"]' -s 'config."ldap.attribute"=["mail"]' -s 'config."read.only"=["false"]' -s 'config."always.read.value.from.ldap"=["false"]' -s 'config."is.mandatory.in.ldap"=["false"]'
----

[discrete]
==== Добавление группы LDAP карты

. Запустите команду `create` на конечной точке `components`.
. Установите атрибут `providerType` в `org.keycloak.storage.ldap.mappers.LDAPStorageMapper`.
. Установите атрибут `parentId` на ID экземпляра LDAP провайдера.
. Установите атрибут `providerId` в `group-ldap-mapper`.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create components -r demorealm -s name=group-ldap-mapper -s providerId=group-ldap-mapper -s providerType=org.keycloak.storage.ldap.mappers.LDAPStorageMapper -s parentId=b7c63d02-b62a-4fc1-977c-947d6a09e1ea -s 'config."groups.dn"=[]' -s 'config."group.name.ldap.attribute"=["cn"]' -s 'config."group.object.classes"=["groupOfNames"]' -s 'config."preserve.group.inheritance"=["true"]' -s 'config."membership.ldap.attribute"=["member"]' -s 'config."membership.attribute.type"=["DN"]' -s 'config."groups.ldap.filter"=[]' -s 'config.mode=["LDAP_ONLY"]' -s 'config."user.roles.retrieve.strategy"=["LOAD_GROUPS_BY_MEMBER_ATTRIBUTE"]' -s 'config."mapped.group.attributes"=["admins-group"]' -s 'config."drop.non.existing.groups.during.sync"=["false"]' -s 'config.roles=["admins"]' -s 'config.groups=["admins-group"]' -s 'config.group=[]' -s 'config.preserve=["true"]' -s 'config.membership=["member"]'
----

[discrete]
==== Добавление полного имени LDAP mapper

. Запустите команду `create` на конечной точке `components`.
. Установите атрибут `providerType` в `org.keycloak.storage.ldap.mappers.LDAPStorageMapper`.
. Установите атрибут `parentId` на ID экземпляра LDAP провайдера.
. Установите атрибут `providerId` в `full-name-ldap-mapper`.
+
Например:
+
[options="nowrap"]
----
$ kcadm.sh create components -r demorealm -s name=full-name-ldap-mapper -s providerId=full-name-ldap-mapper -s providerType=org.keycloak.storage.ldap.mappers.LDAPStorageMapper -s parentId=b7c63d02-b62a-4fc1-977c-947d6a09e1ea -s 'config."ldap.full.name.attribute"=["cn"]' -s 'config."read.only"=["false"]' -s 'config."write.only"=["true"]'
----

=== Операции аутентификации

[discrete]
==== Установка политики паролей

. Установите атрибут `passwordPolicy` области к выражению перечисления, которое включает в себя конкретный ID провайдера политики и опциональную конфигурацию.
. Используйте следующий пример, чтобы установить стандартные значения политики пароля. Значения по умолчанию включают:
* 210,000 итераций хэширования
* хотя бы один специальный символ
* хотя бы один символ в верхнем регистре
* хотя бы один символ
* не равно `username` пользователя
* быть не менее восьми символов
+
[options="nowrap"]
----
$ kcadm.sh update realms/demorealm -s 'passwordPolicy="hashIterations and specialChars and upperCase and digits and notUsername and length"'
----
. Для использования значений, отличных от значений по умолчанию, передайте конфигурацию в скобках.
. Используйте следующий пример, чтобы установить политику паролей:
* 300,000 итераций хэша
* как минимум два специальных символа
* не менее двух заглавных символов
* не менее двух строчных символов
* не менее двух цифр
* быть не менее девяти символов
* не равно `username` пользователя
* не повторять хотя бы четыре изменения назад
+
[options="nowrap"]
----
$ kcadm.sh update realms/demorealm -s 'passwordPolicy="hashIterations(300000) and specialChars(2) and upperCase(2) and lowerCase(2) and digits(2) and length(9) and notUsername and passwordHistory(4)"'
----

[discrete]
==== Получение текущей политики паролей

Текущая конфигурация мира может быть использована для фильтрации всех выводов, кроме атрибута `passwordPolicy`.

Например, покажите `passwordPolicy` для `demorealm`.

[options="nowrap"]
----
$ kcadm.sh get realms/demorealm --fields passwordPolicy
----

[discrete]
==== Список потоков аутентификации

Запустите команду `get` на конечной точке `authentication/flows`.

Например:

[options="nowrap"]
----
$ kcadm.sh get authentication/flows -r demorealm
----

[discrete]
==== Получение определенного потока аутентификации

Запустите команду `get` на конечной точке `authentication/flows/FLOW_ID`.

Например:

[options="nowrap"]
----
$ kcadm.sh get authentication/flows/febfd772-e1a1-42fb-b8ae-00c0566fafb8 -r demorealm
----

[discrete]
==== Список исполнителей для потока

Запустите команду `get` на конечной точке `authentication/flows/FLOW_ALIAS/executions`.

Например:

[options="nowrap"]
----
$ kcadm.sh get authentication/flows/Copy%20of%20browser/executions -r demorealm
----

[discrete]
==== Добавление конфигурации в выполнение

. Получить выполнение для потока.
. Обратите внимание на ID потока.
. Запустите команду `create` на конечной точке `authentication/executions/{executionId}/config`.

Например:

[options="nowrap"]
----
$ kcadm.sh create "authentication/executions/a3147129-c402-4760-86d9-3f2345e401c7/config" -r demorealm -b '{"config":{"x509-cert-auth.mapping-source-selection":"Match SubjectDN using regular expression","x509-cert-auth.regular-expression":"(.*?)(?:$)","x509-cert-auth.mapper-selection":"Custom Attribute Mapper","x509-cert-auth.mapper-selection.user-attribute-name":"usercertificate","x509-cert-auth.crl-checking-enabled":"","x509-cert-auth.crldp-checking-enabled":false,"x509-cert-auth.crl-relative-path":"crl.pem","x509-cert-auth.ocsp-checking-enabled":"","x509-cert-auth.ocsp-responder-uri":"","x509-cert-auth.keyusage":"","x509-cert-auth.extendedkeyusage":"","x509-cert-auth.confirmation-page-disallowed":""},"alias":"my_otp_config"}'
----

[discrete]
==== Получение конфигурации для выполнения

. Получить выполнение для потока.
. Обратите внимание на атрибут `authenticationConfig`, который содержит идентификатор конфигурации.
. Запустите команду `get` на конечной точке `authentication/config/ID`.

Например:

[options="nowrap"]
----
$ kcadm get "authentication/config/dd91611a-d25c-421a-87e2-227c18421833" -r demorealm
----

[discrete]
==== Обновление конфигурации для выполнения

. Получить исполнение для потока.
. Получить атрибут `authenticationConfig` потока
. Обратите внимание на идентификатор конфигурации из атрибута.
. Запустите команду `update` на конечной точке `authentication/config/ID`.

Например:

[options="nowrap"]
----
$ kcadm update "authentication/config/dd91611a-d25c-421a-87e2-227c18421833" -r demorealm -b '{"id":"dd91611a-d25c-421a-87e2-227c18421833","alias":"my_otp_config","config":{"x509-cert-auth.extendedkeyusage":"","x509-cert-auth.mapper-selection.user-attribute-name":"usercertificate","x509-cert-auth.ocsp-responder-uri":"","x509-cert-auth.regular-expression":"(.*?)(?:$)","x509-cert-auth.crl-checking-enabled":"true","x509-cert-auth.confirmation-page-disallowed":"","x509-cert-auth.keyusage":"","x509-cert-auth.mapper-selection":"Custom Attribute Mapper","x509-cert-auth.crl-relative-path":"crl.pem","x509-cert-auth.crldp-checking-enabled":"false","x509-cert-auth.mapping-source-selection":"Match SubjectDN using regular expression","x509-cert-auth.ocsp-checking-enabled":""}}'
----

[discrete]
==== Удаление конфигурации для выполнения

. Получить выполнение для потока.
. Получить атрибут `authenticationConfig`.
. Обратите внимание на идентификатор конфигурации из атрибута.
. Запустите команду `delete` на конечной точке `authentication/config/ID`.

Например:

[options="nowrap"]
----
$ kcadm delete "authentication/config/dd91611a-d25c-421a-87e2-227c18421833" -r demorealm
----