== Назначение прав доступа, используя роли и группы

Роли и группы имеют аналогичную цель, которая заключается в предоставлении пользователям доступа и прав на использование приложений. Группы - это набор пользователей, к которым вы применяете роли и атрибуты. Роли определяют права доступа к конкретным приложениям.

Роль обычно применяется к одному типу пользователя. Например, организация может включать `admin`, `user`, `manager` и `employee`. Приложение может назначить доступ и права доступа роли, а затем назначить несколько пользователей этой роли, чтобы пользователи имели одинаковые права доступа и права. Например, в консоли администратора есть роли, которые дают пользователям доступ к различным частям консоли администратора.

Существует глобальное пространство имён ролей, и каждый клиент также имеет своё собственное выделенное пространство имён, где роли могут быть определены.

include:roles-groups/proc-creating-realm-roles.adoc[leveloffset=2]

include:roles-groups/con-client-roles.adoc[leveloffset=2]

include:roles-groups/proc-converting-composite-roles.adoc[leveloffset=2]

include:roles-groups/proc-assigning-role-mappings.adoc[leveloffset=2]

include:roles-groups/proc-using-default-roles.adoc[leveloffset=2]

include:roles-groups/con-role-scope-mappings.adoc[leveloffset=2]

include:roles-groups/proc-managing-groups.adoc[leveloffset=2]

include:roles-groups/con-comparing-groups-roles.adoc[leveloffset=3]

include:roles-groups/proc-specifying-default-groups.adoc[leveloffset=3]