[[_identity_broker]]
== Интеграция идентичных провайдеров

Идентификационный брокер - это посреднический сервис, связывающий поставщиков услуг с поставщиками идентификационных данных. Идентификационный брокер создает отношения с внешним идентификационным провайдером для использования идентификационных данных провайдера для доступа к внутренним услугам, предоставляемым поставщиком услуг.

С точки зрения пользователей брокеры по предоставлению идентификационных данных обеспечивают централизованный подход к управлению идентификационными данными в доменах и сферах. Вы можете связать учетную запись с одним или несколькими идентификационными данными от провайдеров идентификации или создать учетную запись, основанную на информации о личности.

Провайдер идентификации использует конкретный протокол, используемый для аутентификации и отправки информации аутентификации и авторизации пользователям. Это может быть:

* Социальные провайдеры таких как Facebook, Google или Twitter.
* Бизнес-партнер, чьи пользователи должны получить доступ к вашим услугам.
* Облачный сервис идентификации, который вы хотите интегрировать.

Как правило, {project_name} использует идентификационные провайдеры следующих протоколов:

* `SAML v2.0`
* `OpenID Connect v1.0`
* `OAuth v2.0`