[[_authentication-sessions]]
=== Сессии аутентификации

При первом открытии страницы входа в веб-браузер, {project_name} создает объект, называемый сеансом аутентификации, в котором хранится некоторая полезная информация о запросе.
Всякий раз, когда в одном браузере открыта новая страница входа с другой вкладки, {project_name} создает новую запись под названием Аутентификация, которая хранится в сеансе аутентификации.
Запросы на аутентификацию могут поступать от любых типов клиентов, таких как Admin CLI. В этом случае также создается новая сессия аутентификации с одной сессией аутентификации.
Пожалуйста, обратите внимание, что сеансы аутентификации могут быть созданы и другими способами, чем использование потока браузера.

Сессия аутентификации обычно истекает через 30 минут по умолчанию. Точное время указывается при помощи переключателя *Время входа* на вкладке *Сессии* консоли администратора, когда <<_configuring-realms,configuring realms>>.

==== Аутентификация в других вкладках браузера

Как описано в предыдущем разделе, ситуацией может быть пользователь, который пытается аутентифицироваться на сервере {project_name} с нескольких вкладок одного браузера. Однако, когда пользователь аутентифицируется на одной вкладке браузера,
другие вкладки браузера автоматически перезапустит аутентификацию. Эта аутентификация возникает из-за небольшого javascript доступного на страницах входа в систему {project_name}. Перезагрузка обычно
аутентифицировать пользователя в других вкладках браузера и перенаправить на клиент, так как сейчас происходит сеанс SSO из-за того, что пользователь только что успешно аутентифицировался на первой вкладке браузера.
Some rare exceptions exist when a user is not automatically authenticated in other browser tabs, such as for instance when using an OIDC parameter _prompt=login_ or <<_step-up-flow, step-up authentication>>  requesting a stronger
authentication factor than the currently authenticated factor.

In some rare cases, it can happen that after authentication in the first browser tab, other browser tabs are not able to restart authentication because the authentication session is already
expired. В этом случае конкретная вкладка браузера перенаправит ошибку о сеансе аутентификации с истекшим сроком возврата клиенту конкретным протоколом. Для получения более подробной информации см. соответствующие разделы
*документации OIDC* по ссылке:{securing_apps_link}[защита приложений]. Когда клиентское приложение получает такую ошибку, он может немедленно повторно отправить запрос аутентификации OIDC/SAML {project_name} как
в обычном случае автоматически аутентифицировать пользователя из-за существующего SSO сеанса, как описано выше. В результате конечный пользователь аутентифицируется автоматически во всех вкладках браузера.
*адаптер JavaScript на клавиатуре* по ссылке:{securing_apps_link}[защита приложений] и <_identity_broker, {project_name} Identity provider>>
support to handle this error automatically and retry the authentication to the {project_name} server in such case.