=== Привязать существующего пользователя к идентификатору провайдера

В типичном использовании, провайдер идентификации автоматически регистрирует нового пользователя на {project_name} хранилище после того, как пользователь аутентифицирован
на {project_name} с идентификационным провайдером в первый раз. Подробности об этом описаны в <_identity_broker_first_login, First login flow>>.

Однако во многих случаях желательно связывать существующего пользователя {project_name} с идентификатором провайдера. Это полезно, так что пользователь может войти в систему с провайдером идентификации
во время своей следующей проверки подлинности в {project_name}. Другое использование заключается в том, что приложению может потребоваться использование существующих токенов от поставщика идентификации.
Например, приложение может захотеть использовать Facebook API, чтобы пользователь связал свою учетную запись {project_name} с учетной записью Facebook, чтобы получить токен Facebook от {project_name} и
использовать его, как описано в ссылке:{developerguide_link}#_identity-brokering-apis-tokens[corresponding section from {developerguide_name}].

Самый простой способ - использовать <<_account-service, Account console>>>, откуда пользователь может напрямую связать свою учетную запись с конкретным провайдером идентификации.
Также можно напрямую инициировать процесс соединения пользователя с поставщиком идентификации из вашего собственного приложения. Это возможно с использованием API инициированного Клиентом инициированного аккаунта.
Этот API используется под обложками встроенной консоли учетной записи {project_name}. For the details about this API, see
the link:{developerguide_link}#_client-initiated-account-linking[corresponding section from {developerguide_name}].