=== Поставщик по умолчанию

{project_name} может переадресовать поставщику идентификации, а не отображать форму входа. Чтобы включить это перенаправление:

.Процедура
. Нажмите *Authentication* в меню.
. Нажмите на *Браузер* поток.
. Нажмите на значок снаряжения *⚙️* на строке *Identity Provider Redirector*.
. Установите *По умолчанию* поставщику идентификационных данных*, на который вы хотите перенаправить пользователей.

Если {project_name} не найден поставщик идентификации по умолчанию, отображается форма входа.

Этот аутентификатор отвечает за обработку параметра запроса `kc_idp_hint`. Для получения дополнительной информации обратитесь к разделу <<_client_suggested_idp, предлагаемому клиентом поставщику идентификации.

NOTE: Аутентификатор будет перенаправлен на провайдера идентификации, а аутентификация делегирована поставщику идентификационных данных. Процесс аутентификации `browser` не будет продолжаться после успешного завершения входа с провайдером идентификации
 Если вы хотите выполнить дополнительные шаги после входа провайдера идентификации (например, двухфакторная аутентификация), может потребоваться настроить <<_identity_broker_post_login_flow, Post login flow>.