=== Процесс первого входа

Когда пользователи авторизуются через посредничество идентификации {project_name} импортирует и связывает аспекты пользователя в локальную базу данных. Когда {project_name} успешно аутентифицирует пользователей через внешнего поставщика идентификации, могут существовать две ситуации:

* {project_name} уже импортирован и привязан к учетной записи пользователя с авторизованным провайдером. В этом случае {project_name} аутентифицируется как существующий пользователь и перенаправляет обратно в приложение.
* Учётная запись этого пользователя в {project_name} не существует. Обычно вы регистрируетесь и импортируете новую учетную запись в базу данных {project_name} , но может появиться и существующая учетная запись {project_name} с таким же адресом электронной почты. Автоматическая привязка существующего локального аккаунта к внешнему поставщику идентификации является потенциальным препятствием для безопасности. Вы не всегда можете доверять полученной от внешнего поставщика информации.

При рассмотрении некоторых из этих ситуаций различные организации имеют разные требования. С {project_name}вы можете использовать опцию `First Login Flow` в настройках IDP, чтобы выбрать <<_authentication-flows, workflow>> для входа пользователя из внешнего IDP впервые. По умолчанию опция `First Login Flow` указывает на `first broker login` поток, но вы можете использовать ваш поток или различные потоки для разных поставщиков идентификации.

Поток находится в консоли администратора под вкладкой *Authentication*. Когда вы выберете `First Broker Login`, вы увидите аутентификаторы, используемые по умолчанию. Вы можете перенастроить существующий поток. Например, вы можете отключить некоторые аутентификаторы, отметить некоторые из них как `required` или настроить некоторые аутентификаторы.

ifeval::[{project_community}==true]

Вы также можете создать новый процесс аутентификации, написать собственные реализации Аутентификатора и использовать его в своем процессе. См. ссылку:{developerguide_link}[{developerguide_name}] для получения дополнительной информации.

endif::[]

==== Аутентификаторы первого процесса входа по умолчанию

Просмотр профиля::
* Этот аутентификатор отображает страницу информации профиля, так что пользователи могут просмотреть свой профиль, который {project_name} получает от поставщика идентификации.
* Вы можете установить опцию `Update Profile On First Login` в меню *Actions*.
* При *ВКЛЮЧЕНИи* пользователю предоставляется страница профиля, запрашивающая дополнительную информацию для объединения идентификаторов пользователя.
* При *отсутствии*, пользователи представлены на странице профиля, если идентификатор провайдера не предоставляет обязательную информацию, такие как email, имя или фамилия.
* Когда *ВЫКЛ* страница профиля не отображается, пока пользователь не переключится на более позднюю фазу на ссылку «Информация о профиле проверки» на странице, отображаемой аутентификатором «Подтверждение ссылки на существующую учетную запись».
Создать пользователя с уникальным:: Этот аутентификатор проверяет, существует ли учетная запись {project_name} с тем же адресом электронной почты или именем пользователя от поставщика идентификации.
Если нет, затем аутентификатор просто создает новую локальную учетную запись {project_name} и связывает ее с провайдером идентификации, и весь поток завершен.
В противном случае он переходит к следующему подпотоку «Обработка существующей учетной записи».
Если вы всегда хотите убедиться, что нет дубликатов аккаунта, вы можете отметить этот аутентификатор как `REQUIRED`. В этом случае пользователь
увидит страницу ошибки если есть существующая учетная запись {project_name} и пользователь должен будет связать учетную запись провайдера идентификации с помощью управления учетной записью.
* Этот аутентификатор проверяет, что уже существует учетная запись {project_name} с таким же адресом или именем пользователя, как и аккаунт идентификатора.
* Если учетная запись не существует, то аутентификатор создает локальную учетную запись {project_name} , связывает эту учетную запись с идентификационным провайдером и прекращает поток.
* Если учетная запись существует, то аутентификатор реализует следующий поток `Handle Existing Account`.
* Чтобы убедиться, что у вас нет дубликата аккаунта, вы можете отметить этот аутентификатор как `REQUIRED`. Пользователь видит страницу ошибки, если учетная запись {project_name} существует, и пользователи должны связать свою учетную запись провайдера идентификации с помощью управления учетной записью.
Подтвердите привязку существующей учетной записи::
* На информационной странице пользователи видят учетную запись {project_name} с тем же адресом. Пользователи могут снова просмотреть свой профиль и использовать другой адрес электронной почты или имя пользователя. Поток перезапускается и возвращается в «Профиль обзора».
* В качестве альтернативы, пользователи могут подтвердить, что они хотят связать свою учетную запись поставщика идентификации с существующей учетной записью {project_name}.
* Отключите этот аутентификатор, если вы не хотите, чтобы пользователи видели эту страницу подтверждения и перешли к связыванию учетной записи провайдера идентификации посредством проверки или повторной аутентификации.
Проверить существующую учетную запись по электронной почте::
* Этот аутентификатор является `ALTERNATIVE` по умолчанию. {project_name} использует этот аутентификатор, если в реалме настроена настройка SMTP.
* Аутентификатор отправляет письмо пользователям, чтобы подтвердить, что они хотят связать поставщика идентификации со своей учетной записью {project_name}.
* Отключите этот аутентификатор, если вы не хотите подтверждать привязку по электронной почте, но хотите чтобы пользователи повторно аутентифицировались с их паролем.
Проверить существующую учетную запись путем повторной аутентификации::
* Используйте этот аутентификатор, если почтовый аутентификатор недоступен. Например, вы не настроили SMTP для вашего реалма. Этот аутентификатор отображает экран входа для пользователей, чтобы связать их учетную запись {project_name} с идентификатором провайдера.
* Пользователи также могут переавторизоваться с другим провайдером идентификации, который уже связан с их учетной записью {project_name}.
* Вы можете заставить пользователей использовать OTP. Иначе это опционально и используется, если вы установили OTP для учетной записи пользователя.

==== Автоматически указывать существующий первый логин

[WARNING]
====
Аутентификатор AutoLink опасен в общем окружении, где пользователи могут самостоятельно регистрироваться с помощью произвольных имен пользователей или email адресов. Не используйте этот аутентификатор, если вы не тщательно не курируете регистрацию пользователей и не назначаете имена пользователей и адреса электронной почты.
====

Чтобы настроить первый поток входа, который связывает пользователей автоматически без запроса, создайте новый поток со следующими двумя аутентификаторами:

Создать пользователя с уникальным:: Этот аутентификатор гарантирует, что {project_name} обрабатывает уникальных пользователей. Установите требование аутентификации на *Альтернатива*.
Автоматически устанавливать существующего пользователя:: Этот аутентификатор ставит существующего пользователя в контекст аутентификации без проверки. Установите требование аутентификации на "Альтернатива".

[NOTE]
====
Эта настройка проста и доступна, но можно использовать другие аутентификаторы. Например:

* Вы можете добавить аутентификатор профиля проверки в начало потока, если вы хотите, чтобы конечные пользователи подтвердили свои данные профиля.
* Вы можете добавить механизмы аутентификации в этот поток, вынуждая пользователя верифицировать их учетные данные. Добавление механизмов аутентификации требует сложного потока. Например, в подпотоке "Альтернатива" можно установить "Автоматически устанавливать существующего пользователя" и "Форму пароля".
====

[[_disabling_automatic_user_creation]]
==== Отключение автоматического создания пользователя

Первый процесс входа по умолчанию ищет учетную запись {project_name} , соответствующую внешней личности и предлагает связать ее. Если соответствующий {project_name} аккаунт не существует, поток автоматически создаст его.

Это поведение по умолчанию может быть неподходящим для некоторых настроек. Одним из примеров является использование LDAP-хранилища пользователей только для чтения, где все пользователи уже созданы. В этом случае вы должны отключить автоматическое создание пользователя.

Чтобы отключить создание пользователя:

.Процедура
. Нажмите *Authentication* в меню.
. Выберите из списка *First Broker Login*.
. Установите *Создать Пользователя Если Уникальный* *ОТКЛЮЧИТЕ*.
. Установите *Подтверждение привязки существующей учетной записи* к *ОТКЛЮЧИТЕ*.

Эта конфигурация также подразумевает, что сам {project_name} не сможет определить, какая внутренняя учётная запись будет соответствовать внешнему идентификатору.
Поэтому «Подтвердить существующую учетную запись путем повторной аутентификации» аутентификатор попросит пользователя указать имя пользователя и пароль.

NOTE: Включение или отключение создания пользователя провайдером идентификации полностью независимым от области <<con-user-registration_{context}, User Registration switch>>. You can have enabled user-creation
by identity provider and at the same time disabled user self-registration in the realm login settings or vice-versa.

[[_detect_existing_user_first_login_flow]]
==== Обнаружить существующий пользователь первый логин

Для того, чтобы настроить первый логин в которых:

- только зарегистрированные пользователи могут войти в этот реалм,
- пользователи автоматически привязываются без запроса,

создать новый поток со следующими двумя аутентификаторами:

Обнаружить существующего пользователя брокера:: Этот аутентификатор обеспечивает обработку уникальных пользователей. Установите требование аутентификации на `REQUIRED`.
Автоматически устанавливать существующего пользователя:: Автоматически переводит существующего пользователя в контекст аутентификации без какой-либо проверки. Установите требование аутентификации на `REQUIRED`.

Вы должны установить `First Login Flow` конфигурации поставщика идентификационных данных на этот поток.
Вы можете установить `Sync Mode` в `force`, если хотите обновить профиль пользователя (Фамилия, Имя......) с атрибутами поставщика идентификации.

NOTE: Этот поток может быть использован, если вы хотите делегировать идентификацию другим поставщикам (таким, как GitHub, Facebook ...) но вы хотите управлять какими пользователями, которые могут войти.

В этой конфигурации {project_name} не может определить, какая учётная запись соответствует внешней идентификации. *Проверить существующую учетную запись путем повторной аутентификации* запрашивает у провайдера имя пользователя и пароль.

[[_override_existing_broker_link]]
==== Переопределить существующую ссылку брокера

Когда другой аккаунт должен быть привязан к той же учетной записи {project_name} в рамках того же поставщика идентификации, вы можете настроить следующий аутентификатор.

Подтвердите переопределение существующей ссылки:: Этот аутентификатор определит существующую брокерскую ссылку для пользователя и отобразит страницу подтверждения, чтобы подтвердить переопределение существующей брокерской ссылки. Установите требование аутентификации в НЕОБХОДИМО.

Типичное использование этого аутентификатора является сценарием, таким, как:

* Например, рассмотрите `john` пользователя {project_name} с электронным адресом `john@gmail.com`. Этот пользователь связан с `google` провайдером идентификации с именем пользователя `john@gmail.com` .
* Затем, для копии {project_name} пользователь `john` создает новую учетную запись Google с помощью электронной почты `john-new@gmail.com`
* Затем во время входа в {project_name}, пользователь авторизовался в `google` поставщика идентификации с новым именем пользователя, таким как `john-new@gmail. om`, который еще не связан с ни с одной учетной записью {project_name} (так как `john` учетной записи {project_name} все еще связан с пользователем `google` `john@gmail. om`) и, следовательно, инициируется поток входа в первый брокер.
* При первом брокер-входе пользователь {project_name} `john` аутентифицируется как-то (либо по умолчанию первым брокером аутентификации или аутентификации аутентификации типа `Detect existing broker user`)
* Теперь с этим аутентификатором в процессе аутентификации, возможно переопределить IDP ссылку на `google` поставщика идентификации пользователя {project_name} `john` ссылкой `google` на `google` пользователя `john-new@gmail. om` после того, как пользователь `john` подтвердит это.

При создании потоков аутентификации с этим аутентификатором, не забудьте добавить этот аутентификатор после других аутентификаторов, которые уже установлены пользователем {project_name} другими средствами (либо путем повторной аутентификации, либо после `обнаружения существующего брокера пользователя`, как упоминалось выше.