[[_client_suggested_idp]]
=== Идентификационный провайдер, предложенный клиентом

OIDC приложения могут обойти страницу входа в систему {project_name} , обратившись к поставщику идентификации, который они хотят использовать. Вы можете включить это, установив параметр `kc_idp_hint` запроса в конечной точке кода авторизации потока авторизации.

С адаптерами клиента {project_name} OIDC вы можете указать этот параметр запроса, когда вы получаете доступ к защищенному ресурсу приложения.

Например:

[source,bash,subs=+attributes]
----
GET /myapplication.com?kc_idp_hint=facebook HTTP/1.1
Host: localhost:8080
----

В этом случае у вашего реалма должен быть идентификатор провайдера с псевдонимом "facebook". Если этого провайдера не существует, отображается форма входа.

Если вы используете адаптер JavaScript, вы также можете достичь такого же поведения, как:

[source,javascript]
----
const keycloak = new Keycloak({
	url: "http://keycloak-server",
	realm: "my-realm",
	clientId: "my-app"
);

await keycloak.createLoginUrl({
	idpHint: 'facebook'
});
----

С помощью параметра запроса `kc_idp_hint` клиент может переопределить поставщика идентификации по умолчанию, если вы настроили его для аутентификации `Identity Provider Redirector`. Клиент может отключить автоматическое перенаправление, установив параметр запроса `kc_idp_hint` на пустое значение.