=== Оффлайн доступ

В ходе https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess[offline access] логины клиентское приложение запрашивает токен оффлайн вместо токена обновления. Клиентское приложение сохраняет этот оффлайн токен и может использовать его для будущих входов, если пользователь выходит из системы. Это действие полезно, если приложению нужно выполнять оффлайн действия от имени пользователя, даже если пользователь не в сети. Например, обычная резервная копия данных.

клиентское приложение отвечает за сохранение токена оффлайн в хранилище и использование его для получения новых токенов доступа с сервера {project_name}.

Разница между токеном обновления и токеном в автономном режиме заключается в том, что токен в автономном режиме никогда не истекает и не подлежит таймауту 'SSO Session Idle' и 'SSO Session Max'. Токен оффлайн действителен после выхода пользователя. Вы должны использовать токен оффлайн для действия фишки обновления по крайней мере один раз в тридцать дней или для значения <<_offline-session-idle, Offline Session Idle>>.

Если вы включите <_offline-session-max-limited, Offline Session Max Limited>, Токен оффлайн истекает через 60 дней, даже если вы используете токен оффлайн для операции с фишкой обновления. Вы можете изменить это значение, <<_offline-session-max, Offline Session Max>, в консоли администратора.

При использовании автономного доступа, простоя клиента и макс. таймауты могут быть переопределены в <<_client_advanced_settings_oidc,client level>>. Опции *Offline Session Idle* и *Offline Client Offline Session Max*, на вкладке клиента *Расширенные настройки*, позволяют сократить время ожидания для конкретного приложения. Обратите внимание, что значения сессий клиента также контролируют истечение срока действия токена обновления, но они никогда не влияют на глобальный сеанс автономной сети. Параметр *Client Offline Session Max* вычисляется только в клиенте, если <_offline-session-max-limited, Offline Session Max Limited>> *Включен* на уровне реалмов.

Если вы включите опцию <<_revoke-refresh-token, Revoke Refresh Token>>>, вы можете использовать только один раз в автономном режиме. После обновления вы должны сохранить новый токен оффлайн из ответа обновления вместо предыдущего.

Пользователи могут просматривать и отменять токены, предоставляемые {project_name} в <_account-service (Консоль учетных записей>). Администраторы могут отозвать токены оффлайн для отдельных пользователей в консоли администратора во вкладке «Конпредложения». Администраторы могут просматривать все токены, выпущенные на вкладке «Offline Access» каждого клиента. Администраторы могут отменить токены в автономном режиме, установив <_revocation-policy, revocation policy>>.

Чтобы присвоить токен оффлайн, пользователи должны иметь сопоставление ролей в роли `offline_access`. Клиенты должны также иметь эту роль в сфере их применения. Клиенты должны добавить `offline_access` клиента в качестве `Optional client scope` к роли, которая по умолчанию выполняется.

Клиенты могут запросить токен в автономном режиме, добавив параметр `scope=offline_access` при отправке запроса авторизации {project_name}. Адаптер OIDC {project_name} автоматически добавляет этот параметр, когда вы используете его для доступа к защищенному URL вашего приложения (например, $$http://localhost:8080/customer-portal/secured?scope=offline_access$$). Учетные записи прямого доступа и служб поддерживают оффлайн токены, если вы включите `scope=offline_access` в теле запроса аутентификации.

{project_name} ограничит внутренний кэш для оффлайн пользователей и клиентов по умолчанию до 10000 записей, , что позволит уменьшить общее использование памяти для автономных сессий.
Элементы, выселенные из памяти, будут загружаться по требованию из базы данных, если это необходимо.
Смотрите руководство по настройкам сервера, чтобы изменить это значение по умолчанию.