=== Временные сессии

Вы можете провести временные сессии в {project_name}. При использовании переходных сеансов, {project_name} не создает сеанс пользователя после успешной аутентификации. {project_name} создает временную, временную сессию для области действия текущего запроса, который успешно аутентифицирует пользователя. {project_name} может запускать <<_protocol-mappers, протокол mappers>> с использованием транзитных сессий после аутентификации.

Обычно «sid» и «session_state» токенов являются пустыми, когда токен выдается с временными сессиями. Таким образом, во время переходных сеансов клиентское приложение не может обновить токены или проверить конкретную сессию.
Иногда эти действия не требуются, поэтому вы можете избежать дополнительных ресурсов для продолжения сеансов пользователей. Эта сессия экономит ресурсы, связанные с производительностью, памятью и сетевой коммуникацией (в средах кластера и междата-центра).

На данный момент временные сеансы автоматически используются только во время <_service_accounts, аутентификации сервисного аккаунта>> с отключенным обновлением токена. Note that token refresh is
automatically disabled during service account authentication unless explicitly enabled by client switch `Use refresh tokens for client credentials grant`.