[[_workflow_steps_]]
= Определение шагов

Параметр «Шаг» позволяет определить цепочку шагов, которая представляет собой последовательность действий, которые должны выполняться в течение жизни выполнения рабочего процесса.
Каждый шаг представляет собой конкретное действие, которое может быть выполнено, например, отправка уведомления, обновление атрибутов пользователя или взаимодействие с внешними системами.

Каждый шаг в цепочке шагов определяется следующей структурой:

```yaml
steps:
  - uses: <step>
    with:
      <param>: <value>
      ...
    after: <duration>
  ...
```

В своей простейшей форме шаг определяется с использованием только поля «uses»:

```yaml
steps:
  - uses: disable-user
```

Однако некоторые шаги также поддерживают дополнительные настройки для настройки их поведения:

```yaml
steps:
  - uses: notify-user
    with:
      message: "Welcome to the platform!"
```

Ниже приводится более подробный обзор всех полей, доступных из определения шага:

`uses`:: Название шага, который необходимо выполнить. Это поле является обязательным.
`с`:: Пара ключ/значение для перехода на шаг. Доступные параметры зависят от используемого шага. Это поле необязательно.
`после`:: Необязательная длительность ожидания перед выполнением шага. Продолжительность определяется с использованием числа, за которым следует единица времени:
* `мс`: миллисекунды
* `s`: секунды (по умолчанию, если единица не указана)
* `м`: минуты
* `h`: часы
* `d`: дни

Кроме того, поддерживается формат длительности ISO-8601, например: `P1DT2H` (1 день и 2 часа). Если единица времени не указана, то
принимает секунды по умолчанию.

{project_name} предоставляет набор шагов, которые вы можете использовать в ваших рабочих процессах. The steps are targeted at performing actions
on the realm resource associated with the event, so that each realm resource type has its own set of steps.

[[_workflow_user_steps_]]
== Шаги пользователя

[cols="3*", options="header"]
|===
|Шаг
|Описание
|Конфигурация

|`add-required-action` |Добавить необходимое действие пользователю a|* `action`: Имя требуемого действия

|`remove-required-action` |Удалить требуемое действие из пользователя a|* `action`: Имя требуемого действия

|`грант-роль` |Предоставить пользователю одну или несколько ролей a|* `Роль`: Допускаются имена одной или нескольких ролей. Это может быть одно значение или список значений (например, `[value1, value2]`)

|`revoke-role` |Отозвать одну или несколько ролей пользователя a|* `Роль`: Одна или несколько ролей отозваны. Это может быть одно значение или список значений (например, `[value1, value2]`)

|«совместная группа» |Добавить пользователя в одну или несколько групп a|* `group`: Одно или несколько названий групп или путей к объединению. Это может быть одно значение или список значений (например, `[value1, value2]`)

|`leave-group` |Удалить пользователя из одной или нескольких групп a|* `group`: Одно или несколько названий групп или путей уйти. Это может быть одно значение или список значений (например, `[value1, value2]`)

|`set-user-attribute` |Установите один или несколько атрибутов для пользователя. Позволяет предоставлять несколько пар `<name>`/`<value> a|* `<name>`: Имя атрибута
* `<value>`: Значение атрибута

|`remove-user-attribute` |Удалить один или несколько атрибутов из пользователя a|* `attribute`: Одно или несколько имён атрибутов для удаления. Это может быть одно значение или список значений (например, `[value1, value2]`)

|`notify-user` |Уведомлять пользователя по электронной почте a|* `Тема`: Тема письма
* `сообщение`: Сообщение электронной почты в текстовом или HTML формате
* `to`: Адрес электронной почты получателя. Если не указано, будет использоваться адрес электронной почты пользователя

|`unlink-user` |Отвязать пользователя от одного или нескольких внешних провайдеров идентификации a|* `idp`: Один или несколько псевдонимов провайдера идентификатора для разделения ссылки. Это может быть:
** Одиночное значение
** Список значений (например, `[value1, value2]`)
** `*` отвязать пользователя от всех связанных поставщиков идентификации

|`выключить-user` |Отключить пользователя |Нет

|`delete-user` |Удалить пользователя |Нет
|===

[[_workflow_client_steps_]]
== Шаги клиента

[cols="3*", options="header"]
|===
|Шаг
|Описание
|Конфигурация

|`delete-client` |Удалить клиента |Нет

|`disable-client` |Отключить клиента |Нет
|===

[[_workflow_immediate_steps_]]
== Понимание быстрых шагов

Шаг может выполняться немедленно, когда он достигается в цепочке шагов. Сразу после завершения предыдущего шага выполняется немедленный шаг,
без промедления. Это поведение по умолчанию для шагов в рабочем процессе.

Например, в следующем определении рабочего процесса оба этапа являются немедленными шагами:

```yaml
steps:
  - uses: notify-user
  - uses: disable-user
```

== Понимание запланированных шагов

Шаг может быть запланирован для запуска после определенного времени, используя поле «after». A scheduled step is executed after waiting for the defined duration
once the previous step is completed.

Например, в следующем определении рабочего процесса шаг «disable-user» - это запланированный шаг, который будет запущен через 7 дней после уведомления пользователя:

```yaml
steps:
  - uses: notify-user
  - uses: disable-user
    after: 7d
```