[[_workflow_conditions_]]
= Определение условий

The optional `if` setting allows you to define the conditions, as expressions, that the target resource must meet in
order for the workflow to be triggered. Подробнее см. <<_workflow_expression_language_>>.

Условия обеспечивают четкий контроль над тем, следует ли создавать выполнение рабочего процесса.
Они позволяют вам проверить контекст события и состояние ресурса.
Например, вы можете создать условия для проверки:
* Если пользователь имеет определенный атрибут.
* Если определенная роль предоставлена пользователю или если пользователь присоединяется к конкретной группе.

Если условие вычисляет «true», то создается выполнение рабочего процесса. Если он вычисляет в `false`, то выполнение рабочего процесса не создается, даже несмотря на то, что
выражение из параметра `on` вычисляется в `true`.

Аналогично настройке `on`, условие пишется с помощью выражения, поддерживающего различные проверки ресурсов Realm, связанных с событием.
Например, учитывая событие `user_created`, вы можете определить условие для запуска рабочего процесса, только если пользователь имеет определенный атрибут:

```yaml
on: user-created
if: has-user-attribute(plan=gold)
```

В этом примере рабочий процесс будет срабатывать только при создании нового пользователя и у пользователя атрибут `plan` со значением `gold`.

{project_name} предоставляет набор встроенных условий, которые можно использовать в ваших рабочих процессах.
Условия также основываются на базе ресурсов, связанных с этим событием.

[[_workflow_user_functions_]]
== Функции пользователя

[cols="3*", options="header"]
|===
|Состояние
|Описание
|Параметры

|`has-user-attribute` |Если у пользователя установлен атрибут. |Название атрибута и по желанию значение атрибута с форматом свойств. Если несколько значений разделяются запятыми. Если значение отсутствует, проверяется только наличие атрибута.

|`has -role` |Если пользователю предоставлена определенная роль |Название роли.

|`has-identity-provider-link` |Если пользователь связан с провайдером идентификации. |Алиас удостоверения личности.

|`is-member-of` |Если пользователь является членом определенной группы. |Имя или путь к группе.
|===