[[_workflow_events_]]
= Запуск рабочих процессов при событиях

Параметр `on` определяет событие, которое вызовет рабочий процесс. You should choose the event accordingly to the realm resource and the intent
of the workflow.

Значение параметра «on» - это выражение, которое должно вычислять истину. В его базовой форме выражение просто
название события.

```yaml
on: user-created
```

Как видите, события являются функциями в выражении, и поэтому они также поддерживают параметры для более специфичных условий.
Например, для запуска рабочего процесса при добавлении пользователя в определенную группу, вы можете использовать следующее выражение:

```yaml
on: user-group-membership-added(/mygroup)
```

Вы также можете комбинировать несколько условий с помощью логических операторов. Например, для запуска рабочего процесса, когда пользователь создается или когда он аутентифицирован, вы можете использовать:

```yaml
on: user-created or user-authenticated
```

[NOTE]
====
Хотя настройка «вкл» может быть определена с помощью выражений, имейте в виду, что одно событие вызывает рабочий процесс.
====

Если этот параметр не указан, рабочий процесс не будет инициирован ни одним событием, но выполнение рабочего процесса
все еще может быть создано вручную для определенного ресурса реалма.

В настоящее время рабочие потоки поддерживают функции событий для следующих ресурсов:

[[_workflow_event_functions_]]
== Функции события

[cols="3*", options="header"]
|===
|Событие
|Описание
|Параметры

|`user-created` |Пользователь добавлен в реалм. |Нет

|`user-authenticated` |Пользователь аутентифицируется в реалме. |Идентификатор клиента при аутентификации от имени пользователя.

|`user-federated-identity-added` |Пользователь имеет федерацию или когда аккаунт связан с поставщиком идентификационных данных. |Псевдоним идентификатора провайдера.

|`user-federated-identity-removed` |Федеральная идентификация пользователя удаляется или не привязана к поставщику идентификации. |Псевдоним идентификатора провайдера.

|`user-role-granted` |Роль предоставляется пользователю. |Название роли.

|`user-role-revoked` |Роль отозвана у пользователя. |Название роли.

|`user-group-membership-added` |Пользователь присоединился к группе. |Имя или путь к группе

|`user-group-membership-removed` |Пользователь удален из группы. |Имя или путь к группе

|`client-created` |Клиент добавлен в реалм. |Нет

|`client-authenticated` |Клиент аутентифицируется в реалме. |Нет
|===