[[_understanding_workflow_definition_]]
= Понимание определения рабочего процесса

Рабочие процессы определяются в формате YAML. This format allows for a clear and human-readable way to specify the automation process
represented by a workflow.

В упрощенной форме определение рабочего процесса можно определить следующим образом:

```yaml
name: Onboarding new users
on: user-created
steps:
  - uses: notify-user
    with:
      message: |
        <p>Dear ${user.firstName} ${user.lastName}, </p>

        <p>Welcome to ${realm.displayName}!</p>

        <p>
           Best regards,<br/>
           ${realm.displayName} Team
        </p>
  - uses: add-required-action
    after: 30d
    with:
      action: UPDATE_PASSWORD
  - uses: restart
    with:
      position: 1
```

Приведенный выше пример очень прост, но иллюстрирует основную структуру и гибкость рабочего процесса для автоматизации административных задач.
Она состоит из трех основных разделов:

* `name`: Уникальное и удобное для пользователя имя для определения рабочего процесса в этой области.
* `on`: Событие, которое будет инициировать рабочий процесс. В этом случае рабочий процесс запускается при добавлении нового пользователя в реалм.
* `steps`: Набор из одного или нескольких шагов, которые будут выполнены при выполнении рабочего процесса. В этом примере определены три шага:
1. На первом шаге используется действие `notify-user` для отправки приветственного сообщения новому пользователю.
1. Второй шаг использует встроенное действие «add-required-action», чтобы потребовать от пользователя обновить свой пароль через 30 дней.
1. Третий шаг использует встроенное действие «restart» для перезапуска рабочего процесса со второго шага, чтобы пользователь был вынужден обновлять пароль каждые 30 дней.

Более подробный обзор всех параметров, доступных в определении рабочего процесса:

`name`:: Уникальное и удобное имя для идентификации рабочего процесса в этой области.
Это название имеет решающее значение для управления и ведения лесозаготовительных работ.
Этот параметр является обязательным.
`в`:: Определить условие, которое определяет событие, которое вызовет рабочий процесс.
Условие пишется с помощью языка выражения, поддерживающего различные проверки на событие.
Подробнее см. <<_workflow_events_>> .
Эта настройка необязательна.
`расписание`:: Определите график, который будет запускать рабочий процесс с определенными интервалами.
Смотрите <<_scheduling_workflows_>> для более подробной информации.
Эта настройка необязательна.
`if`:: Определите условие, которое должно быть выполнено для запуска рабочего процесса.
Условие пишется с помощью языка выражения, поддерживающего различные проверки ресурсов Realm
связанных с событием.
Выполнение рабочего процесса создается только в том случае, если выражение вычисляет `true`.
Если этот параметр опущен, событие, определенное в параметре `on`, всегда создаст выполнение рабочего процесса.
Подробнее см. <<_workflow_conditions_>> .
Эта настройка необязательна.
`шаги`:: Определите цепочку шагов, состоящую из одного или нескольких шагов, последовательно выполняемых в течение срока существования рабочего процесса.
Подробнее см. <<_workflow_steps_>> .
Этот параметр является обязательным.
«совпадение»:: Этот параметр контролирует поведение, когда происходит несколько событий, которые запускают один и тот же рабочий процесс для одного и того же ресурса Realm, в то время как выполнение рабочего процесса уже активно для этого ресурса. Эта настройка необязательна.
+ Доступные варианты:
* `restart-in-progress`: новое событие вызывает текущее исполнение рабочего процесса для перезапуска с самого начала.
* `cancel-in-progress`: Новое событие приводит к отмене текущего выполнения рабочего процесса и отключению от ресурса Realm.
`включена`:: Этот параметр включает или отключает рабочий процесс. Если установлено значение `false`, то новые выполнения рабочего процесса не будут созданы для рабочего процесса, и любое активное выполнение рабочего процесса будет приостановлено.
Этот параметр является необязательным, а по умолчанию — `true`.